import {IntakeError} from '../domain/intake.mjs';
const dispatchString={type:'string',minLength:1,maxLength:100},dispatchVersion={type:'integer',minimum:1};
const dispatchEnvironment={type:'object',properties:{type:{type:'string',enum:['native_cloud','coding_environment','computer','existing_thread']},id:{type:['string','null']}},required:['type'],additionalProperties:false};
const dispatchSchemas={
 preflight_dispatch_execution:{type:'object',properties:{jobId:dispatchString,expectedVersion:dispatchVersion,dispatchKey:dispatchString},required:['jobId','expectedVersion','dispatchKey'],additionalProperties:false},
 list_dispatch_jobs:{type:'object',properties:{},additionalProperties:false},
 enqueue_request_dispatch:{type:'object',properties:{requestId:dispatchString,eventId:dispatchString,expectedRequestVersion:dispatchVersion,environment:dispatchEnvironment,resources:{type:'array',maxItems:32,items:{type:'object',properties:{kind:{type:'string',enum:['browser','foreground','gpu','repository','service']},id:dispatchString},required:['kind','id'],additionalProperties:false}},priority:{type:'integer',minimum:0,maximum:10000}},required:['requestId','eventId','expectedRequestVersion','environment'],additionalProperties:false},
 claim_next_dispatch:{type:'object',properties:{eventId:dispatchString},required:['eventId'],additionalProperties:false},
 change_dispatch_priority:{type:'object',properties:{jobId:dispatchString,eventId:dispatchString,expectedVersion:dispatchVersion,priority:{type:'integer',minimum:0,maximum:10000}},required:['jobId','eventId','expectedVersion','priority'],additionalProperties:false},
 update_dispatch_execution:{type:'object',properties:{jobId:dispatchString,eventId:dispatchString,expectedVersion:dispatchVersion,action:{type:'string',enum:['begin','bind','running','observe','uncertain','checkpoint','offline','resume','complete','fail','cancel']},admissionEvidence:{type:'object',properties:{requestId:dispatchString,dispatchKey:dispatchString,threadId:{type:'string',minLength:1,maxLength:320},turnId:dispatchString,observedAt:{type:'string',minLength:1,maxLength:30},source:{type:'string',minLength:8,maxLength:160},reference:{type:'string',minLength:8,maxLength:600}},required:['requestId','dispatchKey','threadId','turnId','observedAt','source','reference'],additionalProperties:false},dispatchKey:{type:['string','null']},threadId:{type:['string','null']},turnId:{type:['string','null']},environment:dispatchEnvironment,summary:{type:'string',minLength:1,maxLength:1200},executionEvidence:{type:'object',properties:{kind:{type:'string',enum:['tool_result','progress_output','active_process']},observedAt:{type:'string',maxLength:30},source:{type:'string',minLength:1,maxLength:160},step:{type:'string',minLength:1,maxLength:600},reference:{type:'string',minLength:1,maxLength:1800},active:{type:'boolean'},terminal:{type:'boolean'}},required:['kind','observedAt','source','step','reference'],additionalProperties:false},verified:{type:'boolean'},noActiveWriter:{type:'boolean'},environmentAvailable:{type:'boolean'},reconciliation:{type:'string',enum:['confirmed_no_active_writer','confirmed_no_thread_created']},verifiedAbsent:{type:'boolean'},reconciliationEvidence:{type:'string',minLength:8,maxLength:1200},nextState:{type:'string',enum:['queued','blocked']},evidenceLinks:{type:'array',maxItems:8,items:{type:'object',properties:{label:{type:'string',maxLength:80},url:{type:'string',maxLength:1800}},required:['label','url'],additionalProperties:false}}},required:['jobId','eventId','expectedVersion','action','summary'],additionalProperties:false}
};
const dispatchDescriptions={preflight_dispatch_execution:'Recheck the current project/task execution gate and original resource leases immediately before invoking an authorized host. This read does not start work.',list_dispatch_jobs:'Read the owner-scoped durable queue. Configured capacity is a policy setting, not a platform concurrency guarantee.',enqueue_request_dispatch:'Queue a request only after its exact version was read and accepted. Existing task follow-ups require an established original thread/environment binding. This does not execute work.',claim_next_dispatch:'Atomically reserve one capacity slot and save a unique dispatch intent. A replayed receipt MUST NOT cause another external create. Unknown outcomes retain their reservation.',change_dispatch_priority:'Reorder queued or safely blocked work only. Active writers cannot be preempted or killed.',update_dispatch_execution:'Record a verified lifecycle transition with expected version and dispatch binding. A safe checkpoint requires explicit no-active-writer evidence. Never infer completion or release capacity from timeout/offline status alone.'};
export const dispatchMcpTools=Object.entries(dispatchSchemas).map(([name,inputSchema])=>({name,inputSchema,description:dispatchDescriptions[name],annotations:{readOnlyHint:['list_dispatch_jobs','preflight_dispatch_execution'].includes(name),destructiveHint:false,idempotentHint:true,openWorldHint:false}}));
function dispatchValid(value,schema){
 if(Array.isArray(schema.type))return schema.type.some(type=>dispatchValid(value,{...schema,type}));
 if(schema.type==='null')return value===null;
 if(schema.type==='boolean')return typeof value==='boolean';
 if(schema.type==='object')return Boolean(value)&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(k=>Object.hasOwn(schema.properties,k)&&dispatchValid(value[k],schema.properties[k]))&&(schema.required??[]).every(k=>Object.hasOwn(value,k));
 if(schema.type==='string')return typeof value==='string'&&value.length>=(schema.minLength??0)&&value.length<=(schema.maxLength??10000)&&(!schema.enum||schema.enum.includes(value));
 if(schema.type==='integer')return Number.isSafeInteger(value)&&value>=(schema.minimum??0)&&value<=(schema.maximum??Number.MAX_SAFE_INTEGER);
 if(schema.type==='array')return Array.isArray(value)&&value.length<=(schema.maxItems??100)&&value.every(x=>dispatchValid(x,schema.items));
 return false;
}
export async function callDispatchTool(service,owner,name,args){
 if(!dispatchSchemas[name]||!dispatchValid(args,dispatchSchemas[name]))throw new IntakeError('invalid_arguments');
 return name==='preflight_dispatch_execution'?service.preflight(owner,{id:args.jobId,version:args.expectedVersion,dispatchKey:args.dispatchKey}):name==='list_dispatch_jobs'?service.list(owner):name==='enqueue_request_dispatch'?service.enqueue(owner,args):name==='claim_next_dispatch'?service.claim(owner,args):name==='change_dispatch_priority'?service.priority(owner,args):service.update(owner,args);
}
