import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {createWorker} from '../worker.mjs';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
const sample=JSON.parse(await readFile(new URL('../fixtures/synthetic.json',import.meta.url),'utf8'));
function setup(t,{db=true,overrides={}}={}){const fixture=db?sqliteIntakeFixture():null;if(fixture)t.after(()=>fixture.close());const source=structuredClone(sample);const env={...(fixture?{DB:fixture.binding}:{}),DOT_BOARD_SNAPSHOT:JSON.stringify(source),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify([{id:'synthetic-project',name:source.tasks[0].project,aliases:[]}]),DOT_BOARD_INTAKE_MCP_ENABLED:'true',DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'true',DOT_BOARD_INTAKE_ENABLED:'true',DOT_BOARD_INTAKE_READER_VERIFIED:'false',DOT_BOARD_INTAKE_WRITER_VERIFIED:'false',...overrides};const worker=createWorker({});async function call(method='tools/call',{user='synthetic-owner',name='get_board_snapshot',args={},origin='https://example.com',extra={}}={}){const response=await worker.fetch(new Request('https://example.com/mcp',{method:'POST',headers:{'content-type':'application/json',origin,...(user?{'oai-authenticated-user-id':user}:{}),...extra},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params:method==='tools/call'?{name,arguments:args}:{}})}),env);const body=await response.json();return {status:response.status,body,data:body.result?.structuredContent};}return {fixture,source,env,worker,call};}
test('board snapshot discovery is fixed-schema, read-only and has no current private data',async t=>{const c=setup(t),r=await c.call('tools/list',{user:null});const tool=r.body.result.tools.find(x=>x.name==='get_board_snapshot');assert(tool);assert.deepEqual(tool.inputSchema,{type:'object',properties:{},additionalProperties:false});assert.equal(tool.annotations.readOnlyHint,true);assert.equal(tool.annotations.destructiveHint,false);assert.equal(tool.annotations.openWorldHint,false);assert(!JSON.stringify(r.body).includes(c.source.tasks[0].title));});
test('snapshot tool retains identity, enabled-bridge and origin gates',async t=>{const c=setup(t);assert.equal((await c.call('tools/call',{user:null})).status,401);assert.equal((await c.call('tools/call',{user:'x'.repeat(201)})).status,401);assert.equal((await c.call('tools/call',{origin:'https://other.example'})).status,403);c.env.DOT_BOARD_INTAKE_MCP_ENABLED='false';const denied=await c.call();assert.equal(denied.status,403);assert.equal(denied.body.error.message,'Intake bridge is not enabled');});
test('tool arguments cannot select another owner, raw source, environment variable or path',async t=>{const c=setup(t);for(const args of [{ownerId:'another-owner'},{raw:true},{env:'DOT_BOARD_SNAPSHOT'},{path:'/api/board'},{projectId:'other'}])assert.equal((await c.call('tools/call',{args})).body.error.code,-32602);});
test('snapshot tool returns the same safe projection as the existing board API',async t=>{const c=setup(t);const mcp=await c.call();assert.equal(mcp.status,200);assert.equal(mcp.body.result.isError,false);const api=await(await c.worker.fetch(new Request('https://example.com/api/board'),c.env)).json();const projected=mcp.data.snapshot;assert.deepEqual(projected.tasks,api.tasks);assert.deepEqual(projected.agents,api.agents);assert.deepEqual(projected.projectSummaries,api.projectSummaries);assert.deepEqual(projected.coverage,api.coverage);assert.equal(projected.snapshotRevision,api.snapshotRevision);assert.equal(projected.importedAt,api.importedAt);assert(projected.generatedAt);});
test('private source fields and unsafe labels never appear in the board MCP response',async t=>{const c=setup(t);c.source.unprojectedSecret='UNPROJECTED_SYNTHETIC_VALUE';c.source.tasks[0].rawReceipt={credential:'RAW_RECEIPT_SYNTHETIC_VALUE'};c.source.tasks[0].observation='/user_notes/synthetic-private-marker';c.source.tasks[0].privatePrompt='UNPROJECTED_PROMPT_VALUE';c.env.DOT_BOARD_SNAPSHOT=JSON.stringify(c.source);c.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify([{id:'unsafe-project',name:'/user_notes/synthetic-private-label'}]);const result=await c.call(),serialized=JSON.stringify(result.body);assert.equal(result.body.result.isError,false);for(const value of ['UNPROJECTED_SYNTHETIC_VALUE','RAW_RECEIPT_SYNTHETIC_VALUE','UNPROJECTED_PROMPT_VALUE','/user_notes/synthetic-private-marker','/user_notes/synthetic-private-label','DOT_BOARD_SNAPSHOT'])assert(!serialized.includes(value),value);assert.equal(result.data.snapshot.tasks.length,c.source.tasks.length);});
test('repeated reads preserve source revision, source times, task pause state and queue contents',async t=>{const c=setup(t);const before=JSON.stringify(c.env,(key,value)=>key==='DB'?undefined:value);const a=await c.call(),b=await c.call();assert.equal(a.data.snapshot.snapshotRevision,b.data.snapshot.snapshotRevision);assert.equal(a.data.snapshot.importedAt,c.source.importedAt);assert.equal(a.data.snapshot.tasks.find(x=>x.id==='sample-paused').state,'paused');assert.equal(c.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,0);assert.equal(c.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_events').get().n,0);assert.equal(JSON.stringify(c.env,(key,value)=>key==='DB'?undefined:value),before);assert.equal(c.env.DOT_BOARD_INTAKE_READER_VERIFIED,'false');assert.equal(c.env.DOT_BOARD_INTAKE_WRITER_VERIFIED,'false');});
test('reading board state does not require a D1 database or fake readiness flags',async t=>{const c=setup(t,{db:false,overrides:{DOT_BOARD_INTAKE_ENABLED:'false',DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'false'}});const r=await c.call();assert.equal(r.status,200);assert.equal(r.body.result.isError,false);assert.equal(r.data.snapshot.tasks.length,sample.tasks.length);});
test('unavailable source fails safely without leaking the parse error or environment value',async t=>{const c=setup(t);c.env.DOT_BOARD_SNAPSHOT='{SYNTHETIC_PRIVATE_PARSE_ERROR';const r=await c.call();assert.equal(r.body.result.isError,true);assert.equal(r.data.error,'board_unavailable');assert(!JSON.stringify(r.body).includes('SYNTHETIC_PRIVATE_PARSE_ERROR'));});
test('service-level snapshot method also requires an authenticated caller marker',async()=>{const service=createIntakeService({store:null,capabilities:{},readBoard:async()=>({status:200,body:{safe:true}})});await assert.rejects(service.boardSnapshot(null),error=>error.code==='authentication_required');assert.deepEqual(await service.boardSnapshot('synthetic-owner'),{snapshot:{safe:true}});});
test('compiled Worker exposes the same protected safe snapshot tool',async t=>{const build=spawnSync(process.execPath,['scripts/build.mjs'],{cwd:new URL('../',import.meta.url),encoding:'utf8'});assert.equal(build.status,0,build.stderr);const worker=(await import('../dist/server/index.js?snapshot-tool='+Date.now())).default;const c=setup(t,{db:false});const response=await worker.fetch(new Request('https://example.com/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':'synthetic-owner'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_board_snapshot',arguments:{}}})}),c.env);const result=await response.json();assert.equal(result.result.isError,false);assert.equal(result.result.structuredContent.snapshot.tasks.length,sample.tasks.length);});
