import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Worker} from 'node:worker_threads';
import {createD1BoardObservationStore} from '../src/adapters/d1-board-observations.mjs';
import {createBoardObservationService,boardObservationMetadata} from '../src/application/board-observation-service.mjs';
import {normalizeBoardObservation} from '../src/domain/board-observation.mjs';
import {sqliteBoardObservationFixture} from './sqlite-board-observation-fixture.mjs';

const now='2026-10-08T05:00:00.000Z',clock=()=>now;
const snapshot={schemaVersion:'dot-board.snapshot/2',importedAt:'2026-10-07T10:00:00.000Z',source:{label:'Synthetic fixture',mode:'synthetic'},coverage:{scope:'Selected test tasks'},tasks:[{id:'task-a',title:'Synthetic A',project:'Synthetic project',state:'unknown',stage:'Original stage',observation:'Original observation',observedAt:'2026-10-07T10:00:00.000Z',blocker:'Original blocker',nextAction:'Original next action',evidence:[],verification:{sourceReview:{state:'passed',observedAt:'2026-10-07T09:00:00.000Z'},deployment:{state:'pending',observedAt:'2026-10-07T09:30:00.000Z'},businessAcceptance:{state:'unknown',observedAt:null}}},{id:'task-b',title:'Unselected B',state:'partial',project:'Other',observedAt:'2026-10-07T10:15:00.000Z',blocker:'Unrelated blocker'}],agents:[{id:'agent-a',name:'Synthetic Agent',activity:{state:'unknown',observedAt:'2026-10-07T10:00:00.000Z'},source:{observedAt:'2026-10-07T10:00:00.000Z'}}]};
const bindings=[{taskId:'task-a',threadId:'private-thread-a',environment:null,readAllowed:true},{taskId:'task-b',threadId:'private-thread-b',environment:{type:'desktop',id:'private-environment-b'},readAllowed:true}];
const registry=[{id:'project-a',name:'Synthetic project',aliases:[],executionState:'deferred'}];
const input=(patch={})=>({taskId:'task-a',eventId:'event-1',expectedVersion:0,source:{threadId:'private-thread-a',environment:null,turnId:'private-turn-a',itemId:'private-item-a',observedAt:'2026-10-08T01:00:00.000Z'},changes:{state:'partial',observation:'Source-backed partial progress',blocker:'Remaining acceptance'},...patch});
function fixture(t,options={}){const db=sqliteBoardObservationFixture();t.after(()=>db.close());const store=createD1BoardObservationStore(db.binding,{clock,...options});return {...db,store,service:createBoardObservationService({store,clock})};}
const errorCode=code=>error=>error.code===code;
const record=(service,value=input(),base=snapshot,mapping=bindings,controls=registry,owner='owner-a')=>service.record(owner,value,base,mapping,controls);
const nextInput=(patch={})=>input({eventId:'event-2',expectedVersion:1,source:{...input().source,itemId:'private-item-second',observedAt:'2026-10-08T02:00:00.000Z'},...patch});
const evidence=[{label:'Synthetic verification result',url:'https://example.com/verified-result'}];
const completion=()=>input({changes:{state:'completed',observation:'Business result checked',evidence},acceptance:{verified:true,checkedScope:['Result matches acceptance criteria'],pendingChecks:[],noActiveWriter:true}});

test('available probes schema and empty state starts at version zero',async t=>{const f=fixture(t);assert.equal(await f.service.available(),true);assert.deepEqual(await f.service.state('owner-a','task-a'),{taskId:'task-a',version:0,observation:null});assert.equal(await createBoardObservationService().available(),false);assert.equal(await createD1BoardObservationStore(null).available(),false);});
test('append-only record keeps source identities owner-private and is restart-safe',async t=>{const f=fixture(t);const receipt=await record(f.service);assert.equal(receipt.version,1);assert.equal(receipt.duplicate,false);assert.deepEqual(receipt.observation.input.source,input().source);const restarted=createBoardObservationService({store:createD1BoardObservationStore(f.binding,{clock}),clock});assert.equal((await restarted.state('owner-a','task-a')).version,1);assert.throws(()=>f.db.prepare("UPDATE board_observation_events SET event_id='altered'").run(),/append_only/);assert.throws(()=>f.db.prepare('DELETE FROM board_observation_events').run(),/append_only/);});
test('same event and canonical payload is idempotent before and after newer events',async t=>{const {service}=fixture(t);await record(service);const duplicate=await record(service);assert.equal(duplicate.version,1);assert.equal(duplicate.duplicate,true);await record(service,nextInput());const reordered={changes:input().changes,source:input().source,expectedVersion:0,eventId:'event-1',taskId:'task-a'};assert.equal((await record(service,reordered)).version,1);assert.equal((await service.state('owner-a','task-a')).version,2);await assert.rejects(record(service,input({changes:{observation:'Changed same event'}})),errorCode('observation_event_conflict'));});
test('owners cannot inspect or overwrite another owner, and event IDs are owner scoped',async t=>{const {service,db}=fixture(t);await record(service);assert.equal((await service.state('owner-b','task-a')).version,0);assert.strictEqual(await service.overlay('owner-b',snapshot,bindings,registry),snapshot);const own=await record(service,input(),snapshot,bindings,registry,'owner-b');assert.equal(own.version,1);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM board_observation_events').get().count,2);for(const owner of [null,'',' invalid','owner\n'])await assert.rejects(service.state(owner,'task-a'),errorCode('authentication_required'));});
test('unknown task, read denial, duplicate mapping and exact environment mismatch fail closed',async t=>{const {service}=fixture(t);await assert.rejects(record(service,input({taskId:'missing'})),errorCode('unknown_observation_task'));for(const mapping of [[],[{...bindings[0],readAllowed:false}],[bindings[0],bindings[0]]])await assert.rejects(record(service,input(),snapshot,mapping),errorCode('observation_read_not_allowed'));await assert.rejects(record(service,input(),snapshot,[{...bindings[0],environment:undefined}]),errorCode('invalid_observation_binding'));for(const source of [{...input().source,threadId:'different-thread'},{...input().source,environment:{type:'cloud',id:null}}])await assert.rejects(record(service,input({source})),errorCode('observation_binding_mismatch'));});
test('known type with unknown environment id remains explicit null, without inventing identity',async t=>{const {service}=fixture(t);const environment={type:'cloud',id:null},mapping=[{...bindings[0],environment}];const value=input({source:{...input().source,environment}});const receipt=await record(service,value,snapshot,mapping);assert.deepEqual(receipt.observation.input.source.environment,environment);assert.equal(Object.hasOwn(receipt.observation.input,'requestId'),false);await assert.rejects(record(service,nextInput({source:{...nextInput().source,environment:{type:'cloud',id:'invented'}}}),snapshot,mapping),errorCode('observation_binding_mismatch'));});
test('invalid dates, future observations and equal-or-older base observations are rejected',async t=>{const {service}=fixture(t);for(const observedAt of ['not-a-date','2026-02-30T01:00:00.000Z','2026-10-08T01:00:00+00:00'])await assert.rejects(record(service,input({source:{...input().source,observedAt}})),errorCode('invalid_source_timestamp'));await assert.rejects(record(service,input({source:{...input().source,observedAt:'2026-10-08T05:00:00.001Z'}})),errorCode('future_source_timestamp'));for(const observedAt of ['2026-10-07T10:00:00Z','2026-10-07T09:59:59.999Z'])await assert.rejects(record(service,input({source:{...input().source,observedAt}})),errorCode('stale_base_observation'));});
test('late or equal source event never overrides a newer journal observation',async t=>{const {service}=fixture(t);await record(service);for(const observedAt of ['2026-10-08T00:59:59.999Z','2026-10-08T01:00:00Z'])await assert.rejects(record(service,nextInput({source:{...input().source,observedAt}})),errorCode('stale_source_observation'));assert.equal((await service.state('owner-a','task-a')).version,1);await assert.rejects(record(service,nextInput({expectedVersion:0})),errorCode('observation_version_conflict'));});
test('unknown keys are rejected at every input layer and running is never inferred',async t=>{const {service}=fixture(t);const mutations=[value=>value.requestId='unexpected',value=>value.source.extra=true,value=>value.source.environment={type:'cloud',id:null,extra:true},value=>value.changes.ownerRole='unauthorized',value=>value.changes.verification={},value=>value.changes.evidence=[{...evidence[0],extra:true}],value=>value.acceptance={verified:true,checkedScope:[],pendingChecks:[],noActiveWriter:true,extra:true}];for(const mutate of mutations){const value=input();mutate(value);await assert.rejects(record(service,value));}for(const state of ['running','reviewing','waiting','queued'])await assert.rejects(record(service,input({changes:{state,observation:'Unsupported inferred state'}})),errorCode('invalid_observation_state'));assert.equal((await service.state('owner-a','task-a')).version,0);});
test('completion requires explicit acceptance, nonempty checked scope and evidence, zero pending, no writer',async t=>{const {service}=fixture(t);const invalid=[value=>delete value.acceptance,value=>value.acceptance.verified=false,value=>value.acceptance.checkedScope=[],value=>value.acceptance.pendingChecks=['Still needs review'],value=>value.acceptance.noActiveWriter=false,value=>value.changes.evidence=[]];for(const mutate of invalid){const value=completion();mutate(value);await assert.rejects(record(service,value),errorCode('completion_requires_acceptance'));}const receipt=await record(service,completion());assert.equal(receipt.version,1);const out=await service.overlay('owner-a',snapshot,bindings,registry);assert.equal(out.tasks[0].state,'completed');assert.equal(out.tasks[0].verification.businessAcceptance.state,'passed');assert.equal(out.tasks[0].verification.businessAcceptance.observedAt,input().source.observedAt);});
test('turn completion alone cannot be submitted as business acceptance',async t=>{const {service}=fixture(t);await assert.rejects(record(service,input({changes:{state:'completed',observation:'turn.completed',evidence}})),errorCode('completion_requires_acceptance'));});
test('overlay changes only safe selected task fields; original snapshot and agent times are preserved',async t=>{const {service}=fixture(t);const before=structuredClone(snapshot);await record(service);const out=await service.overlay('owner-a',snapshot,bindings,registry);assert.equal(out.tasks[0].state,'partial');assert.equal(out.tasks[0].observedAt,input().source.observedAt);assert.equal(out.tasks[0].nextAction,snapshot.tasks[0].nextAction);assert.strictEqual(out.tasks[1],snapshot.tasks[1]);assert.strictEqual(out.agents,snapshot.agents);assert.equal(out.importedAt,snapshot.importedAt);assert.deepEqual(snapshot,before);assert.equal(boardObservationMetadata(out).agentRecordsUpdated,false);const publicJson=JSON.stringify(out);for(const secret of ['private-thread-a','private-turn-a','private-item-a','event-1','effectiveSources'])assert.equal(publicJson.includes(secret),false);});
test('source identifiers and unsafe text/links cannot leak through public fields',async t=>{const {service}=fixture(t);for(const changes of [{observation:'The source is private-thread-a'},{observation:'Progress',blocker:'private-item-a'},{observation:'Progress',evidence:[{label:'Proof',url:'https://example.com/private-turn-a'}]},{observation:'/workspace/private/path'},{observation:'Progress',evidence:[{label:'Proof',url:'http://example.com/proof'}]},{observation:'Progress',evidence:[{label:'Proof',url:'https://example.com/?token=secret'}]}])await assert.rejects(record(service,input({changes})));});
test('paused/canceled base and registry controls dominate; deferred registry does not pause work',async t=>{const {service}=fixture(t);await record(service,completion());for(const state of ['paused','canceled']){const base={...snapshot,tasks:[{...snapshot.tasks[0],state},snapshot.tasks[1]]};assert.equal((await service.overlay('owner-a',base,bindings,registry)).tasks[0].state,state);const controls=[{...registry[0],executionState:state}];assert.equal((await service.overlay('owner-a',snapshot,bindings,controls)).tasks[0].state,state);}assert.equal((await service.overlay('owner-a',snapshot,bindings,registry)).tasks[0].state,'completed');const pausedBase={...snapshot,tasks:[{...snapshot.tasks[0],state:'paused'},snapshot.tasks[1]]};const canceled=[{...registry[0],executionState:'canceled'}];assert.equal((await service.overlay('owner-a',pausedBase,bindings,canceled)).tasks[0].state,'canceled');});
test('removed, denied or remapped bindings and newer base observations suppress historical overlays',async t=>{const {service}=fixture(t);await record(service);for(const mapping of [[],[{...bindings[0],readAllowed:false}],[{...bindings[0],threadId:'new-private-thread'}],[{...bindings[0],environment:{type:'cloud',id:null}}]])assert.strictEqual(await service.overlay('owner-a',snapshot,mapping,registry),snapshot);const updated={...snapshot,tasks:[{...snapshot.tasks[0],observedAt:'2026-10-08T01:00:00Z'},snapshot.tasks[1]]};assert.strictEqual(await service.overlay('owner-a',updated,bindings,registry),updated);});
test('sparse observations retain prior partial state and blocker with original per-field provenance',async t=>{const {service}=fixture(t);await record(service);await record(service,nextInput({changes:{observation:'New result observed'}}));const out=await service.overlay('owner-a',snapshot,bindings,registry);assert.equal(out.tasks[0].state,'partial');assert.equal(out.tasks[0].blocker,'Remaining acceptance');assert.equal(out.tasks[0].observation,'New result observed');const state=await service.state('owner-a','task-a');assert.equal(state.observation.effectiveSources.state.observedAt,input().source.observedAt);assert.equal(state.observation.effectiveSources.observation.observedAt,nextInput().source.observedAt);});
test('newer base fields are not resurrected from inherited patches at record or overlay time',async t=>{const {service}=fixture(t);await record(service);await record(service,nextInput({changes:{observation:'New result observed'}}));const updated={...snapshot,tasks:[{...snapshot.tasks[0],state:'blocked',blocker:'New base blocker',observedAt:'2026-10-08T01:30:00.000Z'},snapshot.tasks[1]]};let out=await service.overlay('owner-a',updated,bindings,registry);assert.equal(out.tasks[0].state,'blocked');assert.equal(out.tasks[0].blocker,'New base blocker');assert.equal(out.tasks[0].observation,'New result observed');await record(service,input({eventId:'event-3',expectedVersion:2,source:{...input().source,observedAt:'2026-10-08T03:00:00.000Z'},changes:{observation:'Another fresh observation'}}),updated);out=await service.overlay('owner-a',updated,bindings,registry);assert.equal(out.tasks[0].state,'blocked');assert.equal(Object.hasOwn((await service.state('owner-a','task-a')).observation.effectiveChanges,'state'),false);});
test('inherited business acceptance keeps original verification time; changed evidence needs reacceptance',async t=>{const {service}=fixture(t);await record(service,completion());await record(service,nextInput({changes:{observation:'Follow-up source confirms no new changes'}}));const out=await service.overlay('owner-a',snapshot,bindings,registry);assert.equal(out.tasks[0].state,'completed');assert.equal(out.tasks[0].observedAt,nextInput().source.observedAt);assert.equal(out.tasks[0].verification.businessAcceptance.observedAt,input().source.observedAt);await assert.rejects(record(service,input({eventId:'event-3',expectedVersion:2,source:{...input().source,observedAt:'2026-10-08T03:00:00.000Z'},changes:{observation:'Changing proof',evidence:[]}})),errorCode('completion_proof_change_requires_acceptance'));});
test('capacity is bounded without deleting history; identical replay still works at capacity',async t=>{const {service,db}=fixture(t,{maxEventsPerTask:2});await record(service);await record(service,nextInput());await assert.rejects(record(service,input({eventId:'event-3',expectedVersion:2,source:{...input().source,observedAt:'2026-10-08T03:00:00.000Z'}})),errorCode('observation_journal_full'));assert.equal((await record(service)).duplicate,true);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM board_observation_events').get().count,2);});

async function race(t,values){
  const directory=mkdtempSync(join(tmpdir(),'board-observation-cas-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));const filename=join(directory,'journal.sqlite');const f=sqliteBoardObservationFixture(filename);t.after(()=>f.close());
  const workers=values.map(value=>new Worker(new URL('./board-observation-concurrency-worker.mjs',import.meta.url),{workerData:{filename,now,owner:'owner-a',input:value,snapshot,bindings,registry}}));
  t.after(async()=>{await Promise.all(workers.map(worker=>worker.terminate()));});
  await Promise.all(workers.map(worker=>new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);})));
  const results=workers.map(worker=>new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);}));workers.forEach(worker=>worker.postMessage('go'));
  return {results:await Promise.all(results),db:f.db};
}
test('real concurrent SQLite writers accept exactly one different event at expectedVersion zero',async t=>{const {results,db}=await race(t,Array.from({length:8},(_,index)=>input({eventId:'racing-event-'+index})));assert.equal(results.filter(result=>result.ok).length,1,JSON.stringify(results));assert.equal(results.filter(result=>result.code==='observation_version_conflict').length,7,JSON.stringify(results));assert.equal(db.prepare('SELECT COUNT(*) AS count FROM board_observation_events').get().count,1);});
test('real concurrent same-event retries are all successful and append exactly once',async t=>{const {results,db}=await race(t,Array.from({length:8},()=>input()));assert.equal(results.every(result=>result.ok),true,JSON.stringify(results));assert.equal(results.filter(result=>result.duplicate===false).length,1);assert.equal(db.prepare('SELECT COUNT(*) AS count FROM board_observation_events').get().count,1);});
test('strict validation never adds synthetic environment or request identifiers',()=>{const normalized=normalizeBoardObservation(input(),Date.parse(now));assert.equal(normalized.source.environment,null);assert.equal(Object.hasOwn(normalized,'requestId'),false);assert.equal(Object.hasOwn(normalized.source,'requestId'),false);});
test('observation-only update cannot refresh an old running inference',async t=>{const {service}=fixture(t);const running={...snapshot,tasks:[{...snapshot.tasks[0],state:'running'},snapshot.tasks[1]]};await record(service,input({changes:{observation:'Only a source result was read'}}),running);const out=await service.overlay('owner-a',running,bindings,registry);assert.equal(out.tasks[0].state,'unknown');assert.equal(out.agents[0].activity.observedAt,snapshot.agents[0].activity.observedAt);});
test('encoded private source IDs are rejected in public evidence URLs',async t=>{const {service}=fixture(t);await assert.rejects(record(service,input({changes:{observation:'Progress checked',evidence:[{label:'Proof',url:'https://example.com/private%2Dthread%2Da'}]}})),errorCode('private_source_reference_in_changes'));});
test('200-task reads use bounded parameter batches',async t=>{const f=fixture(t);await record(f.service);let count=0;const limited={prepare(sql){const statement=f.binding.prepare(sql);return {bind(...params){assert.ok(params.length<=81);count++;return statement.bind(...params);}};}};const store=createD1BoardObservationStore(limited,{clock});const rows=await store.latestForTasks('owner-a',['task-a',...Array.from({length:199},(_,index)=>'absent-'+index)]);assert.equal(rows.length,1);assert.equal(count,3);});
