import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';import {createCandidateEntry} from '../src/application/candidate-entry.mjs';import {boardConfig} from '../config/board.mjs';import {dispatchOne} from '../src/application/dispatch-host.mjs';import {projectDispatchJobs} from '../src/application/dispatch-projection.mjs';import {readBoard,buildBoard} from '../src/application/board-service.mjs';
const source=JSON.parse(readFileSync(new URL('../fixtures/synthetic.json',import.meta.url),'utf8')),now='2026-10-07T14:00:00Z';
function setup(t,{bundled=false}={}){
 let currentTime=now;const db=sqliteIntakeFixture();t.after(()=>db.close());const sent=[],background=[],registry=[{id:'p',name:source.tasks[0].project,aliases:[]}];
 const env={DOT_BOARD_CANDIDATE_ENABLED:'true',DOT_BOARD_OWNER_ID:'owner',DOT_BOARD_AUDIENCE:'synthetic-board',DB:db.binding,DOT_BOARD_SNAPSHOT:JSON.stringify(source),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify(registry),DOT_BOARD_INTAKE_ENABLED:'true',DOT_BOARD_INTAKE_MCP_ENABLED:'true',DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'true',DOT_BOARD_EVENTS_ENABLED:'true',DOT_BOARD_QUEUE_ENABLED:'true',DOT_BOARD_QUEUE_CAPACITY:'1'};
 const transport={resolve:async()=>['8.8.8.8'],send:async ({body})=>{const value=JSON.parse(body);if(value.type==='verification')return new Response(JSON.stringify({challenge:value.challenge}));sent.push(value);return new Response('',{status:202});}};
 const previousFetch=globalThis.fetch;t.after(()=>{globalThis.fetch=previousFetch;});globalThis.fetch=async(_url,q)=>transport.send(q);
 const factory=bundled?new Function(readFileSync(new URL('../dist/candidate/index.js',import.meta.url),'utf8').replace('export default ','const compiledDefault = ')+'\nreturn createCandidateEntry;')():createCandidateEntry;
 const worker=factory({authenticate:async request=>{const ownerId=request.headers.get('x-synthetic-verified-owner');return ownerId?{verified:true,ownerId,audience:'synthetic-board',expiresAt:'2099-01-01T00:00:00Z'}:null;},grantsFor:async ownerId=>({ownerId,audience:'synthetic-board',active:true,boardAccess:true,projectIds:['p']}),clock:()=>Date.parse(currentTime)});let seq=0;const id=()=>`integration-${++seq}`;
 const call=(path,{user='owner',method='GET',body}={})=>worker.fetch(new Request('https://example.com'+path,{method,headers:{...(user?{'x-synthetic-verified-owner':user,'oai-authenticated-user-id':'forged'}:{}),...(body?{'content-type':'application/json',origin:'https://example.com'}:{})},body:body?JSON.stringify(body):undefined}),env,{waitUntil:p=>background.push(p)});
 const rpc=async(method,params={},user='owner')=>{const response=await call('/mcp',{method:'POST',user,body:{jsonrpc:'2.0',id:id(),method,params}});return {status:response.status,body:await response.json()};};
 const tool=async(name,args={},user='owner')=>{const r=await rpc('tools/call',{name,arguments:args},user);if(r.body.error)throw Object.assign(Error(r.body.error.message),{code:r.body.error.message,status:r.status});if(r.body.result.isError)throw Error(JSON.stringify(r.body.result.structuredContent));return r.body.result.structuredContent;};
 const submit=async(contextTaskId=null)=>{const b=await(await call('/api/board')).json();const response=await call('/api/projects/p/requests',{method:'POST',body:{clientSubmissionId:'synthetic-browser-'+id(),body:'Synthetic new project task',contextTaskId,viewedSnapshotRevision:b.snapshotRevision,viewedSnapshotImportedAt:b.importedAt,contextSummary:'Synthetic browser context'}});assert.equal(response.status,201);await Promise.all(background.splice(0));return (await response.json()).request;};
 const accept=async request=>{let r=await tool('acknowledge_project_request',{requestId:request.id,eventId:id(),expectedVersion:request.version});r=await tool('record_project_request_event',{requestId:request.id,eventId:id(),expectedVersion:r.request.version,status:'accepted',summary:'Synthetic explicit acceptance'});return r.request;};
 const service={preflight:(_owner,job)=>tool('preflight_dispatch_execution',{jobId:job.id,expectedVersion:job.version,dispatchKey:job.dispatchKey}),claim:(_owner,args)=>tool('claim_next_dispatch',args),update:(_owner,args)=>tool('update_dispatch_execution',args)};
 return {db,env,worker,sent,call,rpc,tool,submit,accept,service,id,registry,advance:()=>currentTime=new Date(Date.parse(currentTime)+1000).toISOString(),time:()=>currentTime};
}
for(const bundled of [false,true])test((bundled?'compiled bundle: ':'source: ')+'synthetic browser → signed event → one host thread → receipt and board projection → original-thread followup',async t=>{
 const c=setup(t,{bundled}),before=await(await c.call('/api/board')).json();const discover=await c.rpc('server/discover');assert(discover.body.result.capabilities.events);assert.equal((await c.rpc('events/list',{},null)).status,401);
 const sub=await c.rpc('events/subscribe',{name:'project_request.created',arguments:{projectId:'p'},delivery:{mode:'webhook',url:'https://receiver.example.com/callback',secret:'whsec_'+Buffer.alloc(32,7).toString('base64')},cursor:null});assert(sub.body.result.id);
 let request=await c.submit();assert.equal(c.sent.length,1);assert.deepEqual(c.sent[0].data,{requestId:request.id,projectId:'p',version:1});assert(!JSON.stringify(c.sent[0]).includes(request.body));
 request=await c.accept(request);const queued=await c.tool('enqueue_request_dispatch',{requestId:request.id,eventId:c.id(),expectedRequestVersion:request.version,environment:{type:'native_cloud'},priority:20});
 const queueResponse=await c.call('/api/dispatch/queue');assert.equal(queueResponse.status,200);assert.equal((await queueResponse.json()).jobs.length,1);
 const calls=[],adapter={environmentStatus:async()=>({available:true}),create:async x=>{calls.push(['create',x]);return {threadId:'synthetic-thread',turnId:'synthetic-turn-1',environment:x.environment,started:true};},followup:async x=>{calls.push(['followup',x]);return {threadId:x.threadId,turnId:'synthetic-turn-2',environment:x.environment,started:true};}};
 const eventId='claim-'+c.sent[0].eventId;let run=await dispatchOne({service:c.service,ownerId:'owner',eventId,adapter,newId:c.id});await dispatchOne({service:c.service,ownerId:'owner',eventId,adapter,newId:c.id});assert.equal(calls.length,1);assert.equal(run.job.state,'running');
 let board=await(await c.call('/api/board')).json();const card=board.tasks.find(t=>t.id==='dispatch:'+queued.job.id);assert.equal(card.state,'unknown');assert.equal(board.projectTotals[0].registered,1);assert.deepEqual(board.projectTotals[0].current,[]);assert.equal(board.importedAt,before.importedAt);assert.deepEqual(board.tasks.filter(t=>!t.id.startsWith('dispatch:')),before.tasks);assert.equal(board.queueUpdates.records[0].phase,'running');assert(!JSON.stringify(board).includes('synthetic-thread'));
 run=await c.tool('update_dispatch_execution',{jobId:run.job.id,eventId:c.id(),expectedVersion:run.job.version,action:'observe',dispatchKey:run.job.dispatchKey,threadId:run.job.threadId,turnId:run.job.turnId,environment:{type:'native_cloud'},summary:'Synthetic check completed',executionEvidence:{kind:'tool_result',observedAt:now,source:'Synthetic runner',step:'Synthetic checks produced output',reference:'synthetic-output'}});board=await(await c.call('/api/board')).json();assert.equal(board.tasks.find(t=>t.id==='dispatch:'+queued.job.id).state,'running');assert.equal(board.projectTotals[0].current[0].taskNumber,1);
 assert.equal((await c.call('/api/board',{user:'other'})).status,403);await assert.rejects(c.tool('record_project_request_event',{requestId:request.id,eventId:c.id(),expectedVersion:run.job.requestVersion,status:'canceled',summary:'No bypass'}));
 c.advance();const result=await c.tool('update_dispatch_execution',{jobId:run.job.id,eventId:c.id(),expectedVersion:run.job.version,action:'complete',dispatchKey:run.job.dispatchKey,threadId:run.job.threadId,turnId:run.job.turnId,environment:{type:'native_cloud'},noActiveWriter:true,executionEvidence:{kind:'tool_result',observedAt:c.time(),source:'Synthetic terminal executor receipt',step:'This attempt ended with no active writer',reference:'synthetic-terminal-result',active:false,terminal:true},summary:'Synthetic result verified',evidenceLinks:[{label:'Synthetic result',url:'https://example.com/result'}]});assert.equal((await c.tool('get_project_request',{requestId:request.id})).request.status,'completed');
 let follow=await c.submit('dispatch:'+queued.job.id);follow=await c.accept(follow);await c.tool('enqueue_request_dispatch',{requestId:follow.id,eventId:c.id(),expectedRequestVersion:follow.version,environment:{type:'native_cloud'}});run=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter,newId:c.id});assert.equal(run.job.threadId,result.job.threadId);assert.equal(calls[1][0],'followup');assert.equal(calls.filter(x=>x[0]==='create').length,1);
});
test('disabled experimental gates preserve the exact seven intake tools and perform no callback',async t=>{const c=setup(t);delete c.env.DOT_BOARD_EVENTS_ENABLED;delete c.env.DOT_BOARD_QUEUE_ENABLED;const d=await c.rpc('server/discover');assert(!d.body.result.capabilities.events);assert.deepEqual((await c.rpc('tools/list')).body.result.tools.map(tool=>tool.name),['get_request_inbox','get_board_snapshot','list_request_projects','list_project_requests','get_project_request','acknowledge_project_request','record_project_request_event']);await c.submit();assert.equal(c.sent.length,0);assert.equal((await c.rpc('events/list')).body.error.code,-32601);assert.equal((await c.rpc('tools/call',{name:'claim_next_dispatch',arguments:{eventId:c.id()}})).body.error.code,-32602);assert.equal(c.db.db.prepare('SELECT COUNT(*) AS n FROM dispatch_jobs').get().n,0);});
test('missing experiment migration closes new intake but retains original board',async t=>{const c=setup(t);c.db.db.exec('DROP TABLE dispatch_operations');const caps=await(await c.call('/api/intake/capabilities')).json();assert.equal(caps.canSubmit,false);assert.equal((await c.call('/api/board')).status,200);});
test('projection bounds preserve originals, disclose omissions and keep unobserved agents unknown',async()=>{
 const original=structuredClone(source),before=structuredClone(source),project=source.tasks[0].project;const jobs=Array.from({length:500},(_,i)=>({id:'j'+i,requestId:'r'+i,ownerId:'owner',projectId:'p',state:'assigned',threadId:'hidden-thread-'+i,rootJobId:'j'+i,updatedAt:now,executionObservedAt:null,summary:'Synthetic assignment',priority:5,version:1}));const requests=jobs.map(j=>({id:j.requestId,body:'Synthetic queued task'}));const p=projectDispatchJobs(original,jobs,requests,[{id:'p',name:project}],{maxTasks:200,maxAgents:100,totalJobs:550});const board=buildBoard(p,boardConfig);assert.deepEqual(original,before);assert.equal(board.tasks.length,200);assert.equal(board.agents.length,100);assert.equal(board.importedAt,source.importedAt);assert.equal(board.queueUpdates.truncated,true);assert(board.queueUpdates.omittedQueueRecords>0);assert(board.agents.filter(a=>a.id.startsWith('dispatch-agent:')).every(a=>a.activity.state==='unknown'&&a.activity.observedAt===null));
 const full={...source,tasks:Array.from({length:200},(_,i)=>({...source.tasks[0],id:'original-'+i}))};const result=buildBoard(projectDispatchJobs(full,jobs,requests,[{id:'p',name:project}],{totalJobs:550}),boardConfig);assert.equal(result.queueUpdates.taskCount,0);assert.equal(result.queueUpdates.truncated,true);assert(readFileSync(new URL('../public/app.js',import.meta.url),'utf8').includes('board.queueUpdates?.totalQueueRecords||board.queueUpdates?.truncated'));
});
test('public queue priority/phase metadata participates in snapshot revision',async()=>{const j={id:'q',requestId:'r',ownerId:'owner',projectId:'p',state:'blocked',updatedAt:now,executionObservedAt:null,summary:'Synthetic blocked',priority:5,version:1},registry=[{id:'p',name:source.tasks[0].project}],requests=[{id:'r',body:'Synthetic request'}];const one=await readBoard(async()=>projectDispatchJobs(source,[j],requests,registry),boardConfig);const two=await readBoard(async()=>projectDispatchJobs(source,[{...j,priority:99}],requests,registry),boardConfig);assert.equal(one.status,200);assert.notEqual(one.body.snapshotRevision,two.body.snapshotRevision);assert.deepEqual(one.body.tasks,two.body.tasks);});
