import test from 'node:test';import assert from 'node:assert/strict';
import {createCloudThreadsAdapter,cloudThreadReadTools,cloudThreadWriteTools} from '../src/adapters/cloud-threads-adapter.mjs';
import {createCloudThreadDecoder} from '../src/adapters/cloud-thread-observation.mjs';
import {reconcileNativeDispatch} from '../src/application/native-dispatch-host.mjs';
const env={type:'computer',id:'synthetic-env'},input={operationId:'synthetic-op',requestId:'synthetic-request',environment:env};
const data=structuredContent=>({structuredContent,isError:false});
function fixture(options={}){
 const calls=[],records=new Map();let policy={ownerId:'synthetic-owner',requestId:input.requestId,environment:env,executionAllowed:true,readAllowed:true,allowCreate:true,allowFollowup:true,title:'Synthetic acceptance task',approvedPrompt:'Run the explicitly approved synthetic acceptance scope.',threadId:null,...options.policy};
 const provider={read:{list_environments:async a=>{calls.push(['environments',a]);return data({environments:[{environmentId:env.id,status:options.offline?'offline':'connected',is_authorized_for_tasks:true}]});},list_threads:async a=>{calls.push(['list',a]);return data({threads:[],nextCursor:null});},read:async a=>{calls.push(['read',a]);return data({threadId:a.threadId,latestTurn:{id:'old-turn',status:'completed'},items:[]});}},write:{create:async a=>{calls.push(['create',a]);if(options.timeout)throw Error('timeout after effect');return data({threadId:'new-thread',turnId:'new-turn'});},send_message:async a=>{calls.push(['followup',a]);if(options.timeout)throw Error('timeout');return data({turnId:'next-turn'});}}};
 const journal={reserve:async key=>{const old=records.get(key.operationId);if(old)return {acquired:false,record:old};const record={key};records.set(key.operationId,record);return {acquired:true,record};},save:async(key,patch)=>{records.set(key.operationId,{...records.get(key.operationId),...patch});}};
 const adapter=createCloudThreadsAdapter({ownerId:'synthetic-owner',provider,loadAuthorization:async()=>policy,preflight:options.preflight??(async()=>({allowed:true})),journal,decodeObservation:async(raw,x)=>({threadId:raw.threadId,turnId:raw.latestTurn.id,environment:x.environment,active:options.active??false,terminal:!(options.active??false)})});
 return {adapter,calls,records,setPolicy:p=>{policy={...policy,...p};}};
}
test('fixed separate capability allowlists contain no shell, HTTP or eval',()=>{assert.deepEqual(cloudThreadReadTools,['cloud_threads.read','cloud_threads.list_threads','cloud_threads.list_environments']);assert.deepEqual(cloudThreadWriteTools,['cloud_threads.create','cloud_threads.send_message']);});
test('create uses exact native schema and admission never claims started',async()=>{const f=fixture(),r=await f.adapter.create(input);assert.equal(r.started,false);assert.equal(r.threadId,'new-thread');assert.deepEqual(f.calls.find(x=>x[0]==='create')[1],{title:'Synthetic acceptance task',prompt:'Run the explicitly approved synthetic acceptance scope.',environmentId:env.id});});
test('same operation never repeats native side effect',async()=>{const f=fixture();await f.adapter.create(input);await assert.rejects(f.adapter.create(input));assert.equal(f.calls.filter(x=>x[0]==='create').length,1);});
test('ambiguous create rereads list but absence cannot authorize a retry',async()=>{const f=fixture({timeout:true});await assert.rejects(f.adapter.create(input),{code:'dispatch_uncertain'});await assert.rejects(f.adapter.create(input),{code:'dispatch_uncertain'});assert.equal(f.calls.filter(x=>x[0]==='create').length,1);assert(f.calls.some(x=>x[0]==='list'));assert.equal(f.records.get(input.operationId).state,'uncertain');});
test('followup reads original thread and preserves original environment',async()=>{const f=fixture({policy:{threadId:'original-thread'}}),r=await f.adapter.followup({...input,threadId:'original-thread'});assert.equal(r.threadId,'original-thread');assert.equal(f.calls.filter(x=>x[0]==='create').length,0);assert.deepEqual(f.calls.find(x=>x[0]==='followup')[1],{threadId:'original-thread',prompt:'Run the explicitly approved synthetic acceptance scope.'});});
test('ambiguous send rereads original thread without retry',async()=>{const f=fixture({timeout:true,policy:{threadId:'original-thread'}});await assert.rejects(f.adapter.followup({...input,threadId:'original-thread'}),{code:'dispatch_uncertain'});assert.equal(f.calls.filter(x=>x[0]==='followup').length,1);assert.equal(f.calls.filter(x=>x[0]==='read').length,2);});
test('active original turn blocks followup',async()=>{const f=fixture({active:true,policy:{threadId:'original-thread'}});await assert.rejects(f.adapter.followup({...input,threadId:'original-thread'}),{code:'writer_active'});assert(!f.calls.some(x=>x[0]==='followup'));});
for(const patch of [{paused:true},{canceled:true},{ownerId:'different-owner'},{requestId:'different-request'},{environment:{type:'computer',id:'different-env'}}])test('unauthorized policy fails closed '+JSON.stringify(patch),async()=>{const f=fixture({policy:patch});await assert.rejects(f.adapter.create(input),{code:'execution_denied'});assert.equal(f.calls.length,0);});
test('verified existing mapping can never create replacement',async()=>{const f=fixture({policy:{threadId:'existing'}});await assert.rejects(f.adapter.create(input),{code:'binding_conflict'});assert.equal(f.calls.length,0);});
test('offline waits and cannot switch environments',async()=>{const f=fixture({offline:true});await assert.rejects(f.adapter.create(input),{code:'environment_waiting'});assert(!f.calls.some(x=>x[0]==='create'));});
test('pause during reservation rechecked before native write',async()=>{let checks=0;const f=fixture({preflight:async()=>({allowed:++checks===1})});await assert.rejects(f.adapter.create(input),{code:'preflight_denied'});assert(!f.calls.some(x=>x[0]==='create'));});
test('native_cloud explicitly unsupported by cloud_threads create',async()=>{const f=fixture();assert.equal((await f.adapter.environmentStatus({type:'native_cloud',id:null})).available,false);assert.equal(f.calls.length,0);});
const raw={threadId:'existing',latestTurn:{id:'turn',status:'completed',error:null},items:[{id:'result-message',turnId:'turn',role:'assistant',text:'Work remains; product not delivered.'}]};
const context={ownerId:'synthetic-owner',requestId:input.requestId,threadId:'existing',environment:env};
function decoder(acceptResult){return createCloudThreadDecoder({lookupBinding:async()=>({verified:true,threadId:'existing',environment:env}),acceptResult,clock:()=> '2026-10-08T04:31:00Z'});}
test('real completed turn schema alone never means business completed',async()=>{const o=await decoder()(raw,context);assert.equal(o.terminal,true);assert.equal(o.businessCompleted,false);assert.equal(o.active,null);assert.equal(o.executionEvidence,null);});
test('pending acceptance checks prevent completion',async()=>{const o=await decoder(async()=>({verified:true,noActiveWriter:true,outcome:'completed',completedScope:['Code inspected'],pendingChecks:['Runtime validation']}))(raw,context);assert.equal(o.businessCompleted,false);});
test('source-backed accepted result emits terminal evidence with exact source IDs',async()=>{const o=await decoder(async()=>({verified:true,noActiveWriter:true,outcome:'completed',completedScope:['Approved acceptance verified'],pendingChecks:[]}))(raw,context);assert.equal(o.businessCompleted,true);assert.equal(o.executionEvidence.terminal,true);assert.match(o.executionEvidence.reference,/existing:turn:result-message$/);});
test('reconciler keeps inProgress slot and only releases after persisted accepted outcome',async()=>{let writes=0;const job={id:'job',ownerId:'owner',threadId:'thread',turnId:'turn',state:'assigned',holdsSlot:true,version:1,dispatchKey:'op',requestId:'req',environmentType:env.type,environmentId:env.id};const service={update:async(owner,x)=>{writes++;assert.equal(x.action,'complete');assert.equal(x.executionEvidence.terminal,true);return {job:{...job,state:'completed',holdsSlot:false}};}};let o={businessCompleted:false};const adapter={observe:async()=>o};assert.equal((await reconcileNativeDispatch({service,ownerId:'owner',job,adapter})).released,false);assert.equal(writes,0);o={businessCompleted:true,completedScope:['Acceptance verified'],executionEvidence:{kind:'tool_result',terminal:true,active:false,source:'cloud_threads.read',reference:'result-id',observedAt:'2026-10-08T04:31:00Z'}};assert.equal((await reconcileNativeDispatch({service,ownerId:'owner',job,adapter,newId:()=> 'event'})).released,true);assert.equal(writes,1);});

import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1NativeDispatchJournal} from '../src/adapters/d1-native-dispatch-journal.mjs';
test('durable journal arbitrates concurrent reservations and preserves admitted receipt on uncertainty',async t=>{const db=sqliteIntakeFixture();t.after(()=>db.close());const a=createD1NativeDispatchJournal(db.binding),b=createD1NativeDispatchJournal(db.binding),key={ownerId:'owner',operationId:'op',requestId:'req',environment:env};const results=await Promise.all([a.reserve(key),b.reserve(key)]);assert.equal(results.filter(x=>x.acquired).length,1);await a.save(key,{state:'admitted',receipt:{threadId:'thread',turnId:'turn',environment:env}});await b.save(key,{state:'uncertain'});const r=await a.get(key);assert.equal(r.state,'uncertain');assert.equal(r.receipt.threadId,'thread');assert.equal((await b.reserve(key)).acquired,false);await assert.rejects(a.save({...key,requestId:'other'},{state:'admitted'}));assert.equal(await a.get({...key,ownerId:'other'}),null);});

import {bindNativeCloudThreadTools} from '../src/adapters/cloud-threads-adapter.mjs';
test('native provider binding selects exact tool catalog names without exposing other capabilities',async()=>{const seen=[];const provider=bindNativeCloudThreadTools({mcp__codex_apps__cloud_threads_read:async args=>{seen.push(args);return data({threadId:args.threadId});},exec_command:()=>{throw Error('must never expose shell');}});assert.deepEqual(Object.keys(provider.read),['read']);assert.deepEqual(Object.keys(provider.write),[]);assert.equal((await provider.read.read({threadId:'synthetic-thread'})).structuredContent.threadId,'synthetic-thread');assert.deepEqual(seen,[{threadId:'synthetic-thread'}]);assert(Object.isFrozen(provider.read));});

test('paused task may be read with separate read permission but never continued',async()=>{const f=fixture({policy:{threadId:'original-thread',paused:true,executionAllowed:false}});const o=await f.adapter.observe({...input,threadId:'original-thread'});assert.equal(o.threadId,'original-thread');await assert.rejects(f.adapter.followup({...input,threadId:'original-thread'}),{code:'execution_denied'});assert(!f.calls.some(x=>x[0]==='followup'));f.setPolicy({readAllowed:false});await assert.rejects(f.adapter.observe({...input,threadId:'original-thread'}),{code:'execution_denied'});});
import {createNativeHostPreflight} from '../src/application/native-dispatch-host.mjs';
test('guard bridge calls latest versioned preflight for writes and independent authorization for reads',async()=>{let writes=0;const job={ownerId:'owner',requestId:'request',dispatchKey:'operation',threadId:null,environmentType:env.type,environmentId:env.id,version:9};const preflight=createNativeHostPreflight({service:{preflight:async(owner,j)=>{writes++;assert.equal(j.version,9);return j;}},loadCurrentJob:async()=>job,authorizeRead:async()=>true});const i={ownerId:'owner',requestId:'request',operationId:'operation',threadId:null,environment:env};assert.equal((await preflight({...i,phase:'before_write'})).allowed,true);assert.equal((await preflight({...i,phase:'observe'})).allowed,true);assert.equal(writes,1);assert.equal((await preflight({...i,operationId:'changed',phase:'before_write'})).allowed,false);assert.equal(writes,1);});
