import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {createD1DispatchQueue} from '../src/adapters/d1-dispatch-queue.mjs';
import {createDispatchService} from '../src/application/dispatch-service.mjs';
import {dispatchOne} from '../src/application/dispatch-host.mjs';
const env={type:'computer',id:'synthetic-computer'},now='2026-10-07T14:00:00Z';
function setup(t,{capacity=1,filename=':memory:',guard=false}={}){
 const db=sqliteIntakeFixture(filename);t.after(()=>db.close());let seq=0;const id=()=>`synthetic-${++seq}`,contexts=[];
 const requests=createIntakeService({store:createD1IntakeStore(db.binding,{guardDispatchOwnership:guard}),capabilities:{canSubmit:true,storageAvailable:true},clock:()=>now,newId:id,readBoard:async()=>({status:200,body:{snapshotRevision:'sha256:'+'0'.repeat(64),projectSummaries:[{id:'p',name:'Synthetic project'}],tasks:contexts}})});
 const store=createD1DispatchQueue(db.binding),service=createDispatchService({store,requests,enabled:true,capacity,clock:()=>now,newId:id});
 async function request({owner='owner',contextTaskId=null}={}){const r=await requests.submit('p',owner,{clientSubmissionId:'synthetic-client-'+id(),body:'Synthetic task',contextTaskId,viewedSnapshotRevision:'sha256:'+'0'.repeat(64),viewedSnapshotImportedAt:now,contextSummary:''});let x=r.request; x=(await requests.append(x.id,{eventId:id(),expectedVersion:x.version,status:'read',summary:'Read'},owner)).request;x=(await requests.append(x.id,{eventId:id(),expectedVersion:x.version,status:'accepted',summary:'Accepted'},owner)).request;return x;}
 async function enqueue(options={}){const r=await request(options),input={eventId:id(),requestId:r.id,expectedRequestVersion:r.version,environment:options.environment??env,priority:options.priority??0};const out=await service.enqueue(options.owner??'owner',input);contexts.push({id:'dispatch:'+out.job.id,projectId:'p'});return {...out,input};}
 const update=(job,action,extra={})=>service.update(job.ownerId,{jobId:job.id,eventId:id(),expectedVersion:job.version,action,dispatchKey:job.dispatchKey,threadId:job.threadId,environment:{type:job.environmentType,id:job.environmentId},summary:'Synthetic '+action,...extra});
 return {db,store,service,requests,enqueue,request,update,id,contexts};
}
function adapter({offline=false,lost=false}={}){const calls=[];return {calls,environmentStatus:async()=>({available:!offline}),create:async x=>{calls.push(['create',x]);if(lost)throw Error('lost reply after possible creation');return {threadId:'thread-'+calls.length,turnId:'turn-'+calls.length,environment:x.environment,started:true};},followup:async x=>{calls.push(['followup',x]);return {threadId:x.threadId,turnId:'turn-'+calls.length,environment:x.environment,started:true};}};}
test('capacity check, claim and intent are atomic under competing calls',async t=>{const c=setup(t,{capacity:2});for(let i=0;i<5;i++)await c.enqueue();const claims=await Promise.all(Array.from({length:8},()=>c.service.claim('owner',{eventId:c.id()})));assert.equal(claims.filter(x=>x.job).length,2);const jobs=(await c.service.list('owner')).jobs;assert.equal(jobs.filter(j=>j.holdsSlot).length,2);assert.equal(jobs.filter(j=>j.state==='queued').length,3);assert(jobs.filter(j=>j.holdsSlot).every(j=>j.dispatchKey&&j.dispatchAttempt===1));});
test('same task, event and claim dispatch only once; changed replay conflicts',async t=>{const c=setup(t),q=await c.enqueue(),replay=await c.service.enqueue('owner',q.input);assert.equal(replay.job.id,q.job.id);assert.equal(replay.replayed,true);const a=adapter(),eventId=c.id();await dispatchOne({service:c.service,ownerId:'owner',eventId,adapter:a,newId:c.id});const again=await dispatchOne({service:c.service,ownerId:'owner',eventId,adapter:a,newId:c.id});assert.equal(again.executed,false);assert.equal(a.calls.length,1);await assert.rejects(c.service.enqueue('owner',{...q.input,priority:90}),{code:'event_conflict'});});
test('priority reorders only queued work; claimed/running work is never killed',async t=>{const c=setup(t),low=await c.enqueue({priority:1}),high=await c.enqueue({priority:10});await c.service.priority('owner',{jobId:low.job.id,eventId:c.id(),expectedVersion:1,priority:99});const first=await c.service.claim('owner',{eventId:c.id()});assert.equal(first.job.id,low.job.id);await assert.rejects(c.service.priority('owner',{jobId:first.job.id,eventId:c.id(),expectedVersion:first.job.version,priority:0}),{code:'checkpoint_required'});assert.equal((await c.service.claim('owner',{eventId:c.id()})).job,null);assert.equal((await c.store.get('owner',high.job.id)).state,'queued');});
test('ambiguous external create holds capacity and is never retried after new notifications',async t=>{const c=setup(t);await c.enqueue();await c.enqueue();const a=adapter({lost:true}),r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id});assert.equal(r.job.state,'uncertain');assert.equal(r.job.holdsSlot,true);assert.equal((await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id})).job,null);assert.equal(a.calls.length,1);await assert.rejects(c.update(r.job,'checkpoint',{noActiveWriter:true,nextState:'queued'}),{code:'reconciliation_required'});});
test('offline preflight blocks without a create; recovery retains environment and failure record',async t=>{const c=setup(t);await c.enqueue();const a=adapter({offline:true});let r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id});assert.equal(a.calls.length,0);assert.equal(r.job.state,'blocked');assert.equal(r.job.holdsSlot,false);await assert.rejects(c.update(r.job,'resume',{environmentAvailable:true,environment:{type:'computer',id:'other'}}),{code:'environment_unavailable'});r=await c.update(r.job,'resume',{environmentAvailable:true});const live=adapter();r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:live,newId:c.id});assert.equal(r.job.state,'running');assert.equal(r.job.environmentId,env.id);assert.equal(live.calls.length,1);});
test('checkpoint requires no-writer acknowledgement; resume follows the original thread',async t=>{const c=setup(t);await c.enqueue();const a=adapter();let r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id}),old=r.job;await assert.rejects(c.update(old,'checkpoint',{nextState:'queued'}),{code:'checkpoint_required'});r=await c.update(old,'checkpoint',{noActiveWriter:true,nextState:'queued'});assert.equal(r.job.holdsSlot,false);r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id});assert.equal(r.job.threadId,old.threadId);assert.equal(a.calls[1][0],'followup');await assert.rejects(c.update(old,'complete',{noActiveWriter:true,turnId:old.turnId,evidenceLinks:[{label:'Result',url:'https://example.com/result'}]}),{code:'version_conflict'});});
test('follow-up request keeps original environment and thread and cannot overlap its writer',async t=>{const c=setup(t,{capacity:2});const initial=await c.enqueue(),a=adapter();let r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id});await assert.rejects(c.enqueue({contextTaskId:'dispatch:'+initial.job.id,environment:{type:'computer',id:'different'}}),{code:'dispatch_binding_conflict'});const follow=await c.enqueue({contextTaskId:'dispatch:'+initial.job.id});assert.equal(follow.job.threadId,r.job.threadId);assert.equal((await c.service.claim('owner',{eventId:c.id()})).job,null);r=await c.update(r.job,'complete',{turnId:r.job.turnId,noActiveWriter:true,executionEvidence:{kind:'tool_result',observedAt:now,source:'Synthetic executor result',step:'This attempt ended and all writers stopped',reference:'synthetic-current-attempt-terminal',active:false,terminal:true},evidenceLinks:[{label:'Result',url:'https://example.com/result'}]});const next=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id});assert.equal(next.job.threadId,r.job.threadId);assert.equal(a.calls.filter(x=>x[0]==='create').length,1);assert.equal(a.calls.filter(x=>x[0]==='followup').length,1);});
test('atomic result updates request receipt plus job; stale and unowned updates fail',async t=>{const c=setup(t);await c.enqueue();const r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:adapter(),newId:c.id});const receipt=await c.requests.get(r.job.requestId,'owner');assert.equal(receipt.request.status,'in_progress');assert.equal(receipt.request.version,r.job.requestVersion);await assert.rejects(c.service.update('other',{jobId:r.job.id,eventId:c.id(),expectedVersion:r.job.version,action:'cancel',summary:'Cancel'}),{code:'dispatch_not_found'});await assert.rejects(c.update(r.job,'complete',{turnId:r.job.turnId,noActiveWriter:true,evidenceLinks:[]}),{code:'result_evidence_required'});const done=await c.update(r.job,'fail',{turnId:r.job.turnId,noActiveWriter:true,executionEvidence:{kind:'tool_result',observedAt:now,source:'Synthetic executor result',step:'This attempt ended and all writers stopped',reference:'synthetic-current-attempt-terminal',active:false,terminal:true},summary:'Synthetic failure retained'});assert.equal(done.job.state,'failed');assert.equal(done.job.threadId,r.job.threadId);assert.equal((await c.requests.get(r.job.requestId,'owner')).request.latestSummary,'Synthetic failure retained');});
test('restart keeps unknown dispatch reservation and original binding',async t=>{const folder=mkdtempSync(join(tmpdir(),'dot-queue-'));t.after(()=>rmSync(folder,{recursive:true,force:true}));const path=join(folder,'q.db'),c=setup(t,{filename:path});await c.enqueue();await c.enqueue();const r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:adapter({lost:true}),newId:c.id});const second=sqliteIntakeFixture(path);t.after(()=>second.close());const store=createD1DispatchQueue(second.binding);assert.equal((await store.get('owner',r.job.id)).state,'uncertain');assert.deepEqual(await store.claim('owner','restart-claim','synthetic-digest','new-dispatch',1,now),{job:null,replayed:false});});
test('queue migrations upgrade existing intake database without deleting requests',async t=>{const c=setup(t);const request=await c.request();c.db.db.exec('DROP TABLE dispatch_operations; DROP TABLE dispatch_jobs; DROP TABLE mcp_event_outbox; DROP TABLE mcp_event_subscriptions; DROP TABLE mcp_events');assert.equal(await c.store.available(),false);for(const sql of readFileSync(new URL('../migrations/0001_events_dispatch.sql',import.meta.url),'utf8').split('--> statement-breakpoint'))c.db.db.exec(sql);assert.equal(await c.store.available(),false);for(const sql of readFileSync(new URL('../migrations/0002_execution_evidence.sql',import.meta.url),'utf8').split('--> statement-breakpoint'))c.db.db.exec(sql);assert.equal(await c.store.available(),false);c.db.db.exec('DROP TABLE dispatch_controls; DROP TABLE dispatch_resource_leases; DROP TABLE dispatch_task_bindings');for(const sql of readFileSync(new URL('../migrations/0003_dispatch_guards.sql',import.meta.url),'utf8').split('--> statement-breakpoint'))c.db.db.exec(sql);assert.equal(await c.store.available(),true);assert.equal((await c.requests.get(request.id,'owner')).request.id,request.id);});
test('conflicting concurrent event cannot write a rejected receipt or event',async t=>{
 const c=setup(t);await c.enqueue();const {job}=await c.service.claim('owner',{eventId:c.id()});const original=c.store.change.bind(c.store),pending=[];
 c.store.change=(...args)=>new Promise((resolve,reject)=>{pending.push({args,resolve,reject});if(pending.length===2)(async()=>{for(const p of pending.sort((a,b)=>a.args[6]==='begin'?-1:1)){try{p.resolve(await original(...p.args));}catch(e){p.reject(e);}}})();});
 const common={jobId:job.id,eventId:c.id(),expectedVersion:job.version,dispatchKey:job.dispatchKey,threadId:null,environment:env};const results=await Promise.allSettled([c.service.update('owner',{...common,action:'begin',summary:'begin won'}),c.service.update('owner',{...common,action:'checkpoint',noActiveWriter:true,nextState:'blocked',summary:'rejected checkpoint'})]);
 assert.equal(results[0].status,'fulfilled');assert.equal(results[1].reason.code,'event_conflict');const receipt=await c.requests.get(job.requestId,'owner');assert.equal(receipt.request.status,'accepted');assert.equal(receipt.request.version,job.requestVersion);assert(!receipt.events.some(e=>e.summary==='rejected checkpoint'));assert.equal((await c.store.get('owner',job.id)).state,'dispatching');
});
test('crash in dispatching cannot claim thread absence from no-active-writer alone',async t=>{const c=setup(t);await c.enqueue();let r=await c.service.claim('owner',{eventId:c.id()});r=await c.update(r.job,'begin');await assert.rejects(c.update(r.job,'checkpoint',{noActiveWriter:true,reconciliation:'confirmed_no_active_writer',nextState:'queued'}),{code:'reconciliation_required'});assert.equal((await c.store.get('owner',r.job.id)).holdsSlot,true);r=await c.update(r.job,'checkpoint',{noActiveWriter:true,reconciliation:'confirmed_no_thread_created',verifiedAbsent:true,reconciliationEvidence:'Synthetic executor operation registry confirms no thread was created',nextState:'queued'});assert.equal(r.job.holdsSlot,false);assert(r.job.reconciliationEvidence.includes('registry'));});
test('canceled receipt cannot be claimed or dispatched; queued ownership guards ordinary intake writes',async t=>{const c=setup(t);const q=await c.enqueue();const receipt=(await c.requests.get(q.job.requestId,'owner')).request;await c.requests.append(receipt.id,{eventId:c.id(),expectedVersion:receipt.version,status:'canceled',summary:'User canceled'},'owner');const a=adapter();const r=await dispatchOne({service:c.service,ownerId:'owner',eventId:c.id(),adapter:a,newId:c.id});assert.equal(r.job,null);assert.equal(a.calls.length,0);const guarded=setup(t,{guard:true});const g=await guarded.enqueue();await assert.rejects(guarded.requests.append(g.job.requestId,{eventId:guarded.id(),expectedVersion:g.job.requestVersion,status:'canceled',summary:'Cannot bypass queue'},'owner'),{code:'version_conflict'});});
test('failed receipt-event insert rolls back job, binding and operation atomically',async t=>{const c=setup(t);await c.enqueue();let r=await c.service.claim('owner',{eventId:c.id()});r=await c.update(r.job,'begin');const before=structuredClone(r.job),receipt=(await c.requests.get(before.requestId,'owner')).request;c.db.db.exec("CREATE TRIGGER reject_dispatch_receipt BEFORE INSERT ON intake_events WHEN NEW.status='assigned' BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");await assert.rejects(c.update(before,'bind',{threadId:'verified-thread',turnId:'verified-turn',verified:true}));assert.deepEqual(await c.store.get('owner',before.id),before);assert.deepEqual((await c.requests.get(before.requestId,'owner')).request,receipt);});
