import test from 'node:test';import assert from 'node:assert/strict';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {createD1DispatchQueue} from '../src/adapters/d1-dispatch-queue.mjs';
import {createDispatchService} from '../src/application/dispatch-service.mjs';
import {dispatchOne} from '../src/application/dispatch-host.mjs';
function setup(t){
 const db=sqliteIntakeFixture();t.after(()=>db.close());let n=0,now='2026-10-08T00:00:00Z';const id=()=>`synthetic-${++n}`,environment={type:'computer',id:'fixture-computer'},contexts=[],registry=[{id:'p',executionState:'active'},{id:'q',executionState:'active'}];
 const requests=createIntakeService({store:createD1IntakeStore(db.binding),capabilities:{canSubmit:true,storageAvailable:true},clock:()=>now,newId:id,readBoard:async()=>({status:200,body:{snapshotRevision:'sha256:'+'0'.repeat(64),projectSummaries:registry.map(p=>({...p,name:p.id})),tasks:contexts}})});
 const store=createD1DispatchQueue(db.binding),service=createDispatchService({store,requests,enabled:true,capacity:6,clock:()=>now,newId:id,readRegistry:async()=>registry});
 async function enqueue({project='p',resources=[],contextTaskId=null}={}){let {request:r}=await requests.submit(project,'owner',{clientSubmissionId:'synthetic-client-'+id(),body:'Synthetic guarded work',viewedSnapshotRevision:'sha256:'+'0'.repeat(64),viewedSnapshotImportedAt:now,contextTaskId});for(const status of ['read','accepted'])r=(await requests.append(r.id,{eventId:id(),expectedVersion:r.version,status,summary:status},'owner')).request;const input={eventId:id(),requestId:r.id,expectedRequestVersion:r.version,environment,resources};return {...await service.enqueue('owner',input),input};}
 const update=(job,action,extra={})=>service.update('owner',{jobId:job.id,eventId:id(),expectedVersion:job.version,dispatchKey:job.dispatchKey,threadId:job.threadId,environment,action,summary:'Synthetic '+action,...extra});
 const control=(scope,targetId,state,expectedVersion=0)=>service.control('owner',{scope,targetId,state,expectedVersion,reason:'Synthetic explicit user decision'});
 const calls=[],adapter={environmentStatus:async()=>({available:true}),create:async x=>{calls.push(['create',x]);return {threadId:'fixture-thread-'+calls.length,turnId:id(),environment,started:true};},followup:async x=>{calls.push(['followup',x]);return {threadId:x.threadId,turnId:id(),environment,started:true};}};
 return {db,service,store,enqueue,control,update,adapter,calls,registry,contexts,id,environment,setTime:x=>now=x,run:()=>dispatchOne({service,ownerId:'owner',eventId:id(),adapter,newId:id})};
}
test('durable paused project blocks old queue, fresh enqueue and resume; explicit versioned release permits it',async t=>{const c=setup(t),q=await c.enqueue();await c.control('project','p','paused');assert.equal((await c.service.claim('owner',{eventId:c.id()})).job,null);await assert.rejects(c.enqueue(),{code:'execution_paused'});await c.control('project','p','active',1);assert.equal((await c.service.claim('owner',{eventId:c.id()})).job.id,q.job.id);await assert.rejects(c.control('project','p','paused',1),{code:'version_conflict'});});
test('task deferred and canceled gates apply to old queued records',async t=>{for(const state of ['deferred','canceled']){const c=setup(t),q=await c.enqueue();await c.control('task',q.job.id,state);assert.equal((await c.run()).job,null);assert.equal(c.calls.length,0);}});
test('registry execution state blocks project while independent project remains claimable',async t=>{const c=setup(t);await c.enqueue();const next=await c.enqueue({project:'q'});c.registry[0].executionState='paused';assert.equal((await c.run()).job.id,next.job.id);await assert.rejects(c.enqueue(),{code:'execution_paused'});});
test('pause during host environment preflight prevents begin and external call',async t=>{const c=setup(t);await c.enqueue();c.adapter.environmentStatus=async()=>{await c.control('project','p','paused');return {available:true};};const r=await c.run();assert.equal(r.executed,false);assert.equal(r.job.state,'blocked');assert.equal(c.calls.length,0);await assert.rejects(c.update(r.job,'resume',{environmentAvailable:true}),{code:'execution_paused'});});
test('pause raced into atomic begin write cannot bypass persistent controls',async t=>{const c=setup(t);await c.enqueue();const {job}=await c.service.claim('owner',{eventId:c.id()});const change=c.store.change.bind(c.store);c.store.change=async(...args)=>{await c.control('project','p','paused');return change(...args);};await assert.rejects(c.update(job,'begin'),{code:'version_conflict'});assert.equal((await c.store.get('owner',job.id)).state,'claimed');});
test('browser and repository exclusive leases serialize cross-project conflicts but not other work',async t=>{for(const kind of ['browser','repository','foreground','gpu','service']){const c=setup(t),resource={kind,id:'shared-fixture'};const first=await c.enqueue({resources:[resource]});await c.enqueue({project:'q',resources:[resource]});const free=await c.enqueue({project:'q'});const other=await c.enqueue({resources:[{kind,id:'different-fixture'}]});const claims=await Promise.all(Array.from({length:5},()=>c.service.claim('owner',{eventId:c.id()})));assert.deepEqual(new Set(claims.filter(x=>x.job).map(x=>x.job.id)),new Set([first.job.id,free.job.id,other.job.id]));assert.equal((await c.store.leases('owner',first.job.id)).length,1);}});
test('lease timeout never steals unknown owner; original reconciliation releases reservation',async t=>{const c=setup(t),resources=[{kind:'browser',id:'shared-browser'}];await c.enqueue({resources});await c.enqueue({project:'q',resources});c.adapter.create=async()=>{c.calls.push(['ambiguous']);throw Error('lost response');};const r=await c.run();assert.equal(r.job.state,'uncertain');c.setTime('2026-10-09T00:00:00Z');assert.equal((await c.run()).job,null);await assert.rejects(c.update(r.job,'checkpoint',{noActiveWriter:true,nextState:'blocked'}),{code:'reconciliation_required'});assert.equal((await c.store.leases('owner',r.job.id)).length,1);await c.update(r.job,'checkpoint',{noActiveWriter:true,nextState:'blocked',reconciliation:'confirmed_no_thread_created',verifiedAbsent:true,reconciliationEvidence:'Synthetic operation registry verified absence'});assert.equal((await c.store.leases('owner',r.job.id)).length,0);assert((await c.service.claim('owner',{eventId:c.id()})).job);});
test('known binding survives service reconstruction and reconnect follows original task without duplicate number',async t=>{const c=setup(t);c.contexts.push({id:'existing-task',projectId:'p'});await c.service.registerBinding('owner',{taskId:'existing-task',projectId:'p',threadId:'original-thread',environment:c.environment,verified:true,evidence:'Synthetic original task receipt'});const queued=await c.enqueue({contextTaskId:'existing-task'});const restarted=createD1DispatchQueue(c.db.binding);assert.equal((await restarted.binding('owner','existing-task')).thread_id,'original-thread');c.adapter.environmentStatus=async()=>({available:false});const offline=await c.run();assert.equal(offline.job.threadId,'original-thread');const replay=await c.service.enqueue('owner',queued.input);assert.equal(replay.job.taskNumber,queued.job.taskNumber);assert.equal((await c.store.list('owner')).length,1);await c.update(offline.job,'resume',{environmentAvailable:true});c.adapter.environmentStatus=async()=>({available:true});const live=await c.run();assert.equal(live.job.threadId,'original-thread');assert.equal(c.calls.length,1);assert.equal(c.calls[0][0],'followup');assert.equal(live.job.environmentId,c.environment.id);});
test('checkpoint release and replay never resurrect old resource lease',async t=>{const c=setup(t);await c.enqueue({resources:[{kind:'gpu',id:'synthetic-gpu'}]});const eventId=c.id(),r=await dispatchOne({service:c.service,ownerId:'owner',eventId,adapter:c.adapter,newId:c.id});await c.update(r.job,'checkpoint',{noActiveWriter:true,nextState:'blocked'});await c.service.claim('owner',{eventId});assert.equal((await c.store.leases('owner',r.job.id)).length,0);});
test('task control accepts board dispatch identity and protects continuations',async t=>{const c=setup(t),q=await c.enqueue();await c.control('task','dispatch:'+q.job.id,'paused');assert.equal((await c.run()).job,null);});
test('expired lease is a hard preflight stop, never permission to create',async t=>{const c=setup(t);await c.enqueue({resources:[{kind:'browser',id:'fixture-browser'}]});const {job}=await c.service.claim('owner',{eventId:c.id()});c.setTime('2026-10-08T00:06:00Z');await assert.rejects(c.service.preflight('owner',job),{code:'resource_lease_expired'});assert.equal((await c.store.leases('owner',job.id)).length,1);assert.equal(c.calls.length,0);});
test('fail rejects nonterminal evidence and retains original lease',async t=>{const c=setup(t);await c.enqueue({resources:[{kind:'service',id:'fixture-service'}]});const {job}=await c.run();await assert.rejects(c.update(job,'fail',{turnId:job.turnId,noActiveWriter:true,executionEvidence:{kind:'progress_output',source:'Synthetic runner',step:'Still active',reference:'synthetic-ref',observedAt:'2026-10-08T00:00:00Z',active:true,terminal:false}}),{code:'result_evidence_required'});assert.equal((await c.store.leases('owner',job.id)).length,1);});
