import test from 'node:test';
import assert from 'node:assert/strict';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {handleIntakeRequest} from '../src/presentation/intake-http.mjs';
const now='2026-10-08T11:00:00.000Z';
const capabilities={storageAvailable:true,canSubmit:false};
function fixture(t,{readBoard=async()=>({status:200,body:{projectSummaries:[{id:'project-a',name:'Alias name',canonicalName:'Verified project A'},{id:'project-b',name:'Verified project B'}]}})}={}){
 const f=sqliteIntakeFixture();t.after(()=>f.close());const statements=[];const binding={...f.binding,prepare(sql){statements.push(sql);return f.binding.prepare(sql);}};const store=createD1IntakeStore(binding),service=createIntakeService({store,readBoard,capabilities});let sequence=0;
 const seed=({id='request-'+(++sequence),owner='owner-a',project='project-a',status='received',createdAt=now,updatedAt=createdAt,body='Original owner feedback',contextTaskId=null}={})=>{f.db.prepare('INSERT INTO intake_requests(id,owner_id,project_id,client_submission_id,payload_digest,body,context_task_id,viewed_snapshot_revision,viewed_snapshot_imported_at,context_summary,context_stale,status,created_at,updated_at,version,linked_task_ids,latest_summary) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,owner,project,id+'-submission','private-payload-digest',body,contextTaskId,'sha256:private-revision',now,'private-context-summary',0,status,createdAt,updatedAt,9,'["private-linked-task"]','private-internal-summary');return id;};
 const call=(path='/api/intake/inbox',{owner='owner-a',method='GET',headers={}}={})=>handleIntakeRequest(new Request('https://board.example'+path,{method,headers:{...(owner===null?{}:{'oai-authenticated-user-id':owner}),origin:'https://board.example',...headers}}),{service,capabilities});
 return {...f,store,service,seed,call,statements};
}
test('empty owner inbox has numeric zero counts and no truncation',async t=>{const f=fixture(t);assert.deepEqual(await f.service.inbox('owner-a'),{requests:[],unreadCount:0,pendingCount:0,truncated:false,limit:50,nextCursor:null});});
test('all-project inbox contains received/read/accepted/needs_confirmation and excludes execution or terminal states',async t=>{const f=fixture(t);for(const status of ['received','read','needs_confirmation','accepted','assigned','in_progress','blocked','completed','canceled','declined'])f.seed({id:status,project:status==='read'?'project-b':'project-a',status});const result=await f.service.inbox('owner-a');assert.deepEqual(result.requests.map(row=>row.status).sort(),['accepted','needs_confirmation','read','received']);assert.equal(result.unreadCount,1);assert.equal(result.pendingCount,4);assert.equal(result.requests.find(row=>row.id==='read').projectName,'Verified project B');});
test('real database owner isolation applies to both counts and rows, including supplied project/query hints',async t=>{const f=fixture(t);f.seed({id:'mine',owner:'owner-a'});for(let i=0;i<70;i++)f.seed({id:'other-'+i,owner:'owner-b'});const a=await f.service.inbox('owner-a'),b=await f.service.inbox('owner-b');assert.equal(a.pendingCount,1);assert.equal(a.unreadCount,1);assert.deepEqual(a.requests.map(row=>row.id),['mine']);assert.equal(b.pendingCount,70);assert.equal(b.requests.length,50);assert.equal(b.truncated,true);const response=await f.call('/api/intake/inbox?ownerId=owner-b&projectId=project-b&limit=500');assert.deepEqual((await response.json()).requests.map(row=>row.id),['mine']);});
test('50-row limit does not truncate unread/pending totals and does not acknowledge the hidden or visible rows',async t=>{const f=fixture(t);for(let i=0;i<65;i++)f.seed({id:'pending-'+String(i).padStart(3,'0'),status:i<60?'received':'read'});const before=f.db.prepare('SELECT * FROM intake_requests ORDER BY id').all();const first=await f.service.inbox('owner-a'),second=await f.service.inbox('owner-a');assert.equal(first.requests.length,50);assert.equal(first.unreadCount,60);assert.equal(first.pendingCount,65);assert.equal(first.truncated,true);assert.deepEqual(first,second);assert.deepEqual(f.db.prepare('SELECT * FROM intake_requests ORDER BY id').all(),before);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM intake_events').get().n,0);});
test('creation timestamps sort by actual instant across fractional formats; updatedAt never promotes an older request',async t=>{const f=fixture(t);f.seed({id:'whole-second',createdAt:'2026-10-08T10:00:00Z'});f.seed({id:'fractional-later',createdAt:'2026-10-08T10:00:00.500Z'});f.seed({id:'old-created',createdAt:'2026-10-08T09:00:00.000Z',updatedAt:'2026-10-08T12:00:00Z'});f.seed({id:'same-time-z',createdAt:'2026-10-08T10:00:00.500Z'});assert.deepEqual((await f.service.inbox('owner-a')).requests.map(row=>row.id),['same-time-z','fractional-later','whole-second','old-created']);});
test('returned request fields are allowlisted and retain the exact owner body and original context task',async t=>{const f=fixture(t);f.seed({id:'feedback',body:'这个任务结束了。\n<script>owner text</script>',contextTaskId:'original-context-task'});const result=await f.service.inbox('owner-a'),row=result.requests[0];assert.deepEqual(Object.keys(row).sort(),['id','projectId','projectName','body','status','createdAt','updatedAt','contextTaskId','version'].sort());assert.equal(row.body,'这个任务结束了。\n<script>owner text</script>');assert.equal(row.contextTaskId,'original-context-task');assert.equal(row.projectName,'Verified project A');for(const text of ['private-payload-digest','private-revision','private-context-summary','private-linked-task','private-internal-summary'])assert.equal(JSON.stringify(result).includes(text),false);});
test('unknown projects keep original IDs and never gain inferred names or source metadata',async t=>{const f=fixture(t);f.seed({project:'unregistered-project'});const row=(await f.service.inbox('owner-a')).requests[0];assert.equal(row.projectId,'unregistered-project');assert.equal(Object.hasOwn(row,'projectName'),false);assert.equal(Object.hasOwn(row,'source'),false);assert.equal(Object.hasOwn(row,'threadId'),false);});
test('board failure or malformed optional project names never hides pending feedback',async t=>{for(const readBoard of [async()=>({status:503}),async()=>{throw Error('board unavailable');},async()=>({status:200,body:{projectSummaries:[{id:'project-a',name:'/workspace/private/name'}]}})]){const f=fixture(t,{readBoard});f.seed();const result=await f.service.inbox('owner-a');assert.equal(result.requests.length,1);assert.equal(Object.hasOwn(result.requests[0],'projectName'),false);}});
test('store/service reject missing, whitespace, oversized, or control-character owner IDs',async t=>{const f=fixture(t);for(const ownerId of [null,undefined,'',' owner-a','owner-a\n','x'.repeat(201)]){await assert.rejects(f.store.inbox({ownerId}),{code:'authentication_required'});await assert.rejects(f.service.inbox(ownerId),{code:'authentication_required'});}});
test('store limit is bounded at 50 and HTTP GET always uses the fixed limit',async t=>{const f=fixture(t);f.seed();for(const limit of [0,-1,51,1.5,'50'])await assert.rejects(f.store.inbox({ownerId:'owner-a',limit}),{code:'invalid_inbox_limit'});assert.equal((await f.store.inbox({ownerId:'owner-a',limit:1})).limit,1);assert.equal((await(await f.call('/api/intake/inbox?limit=1')).json()).limit,50);});
test('HTTP inbox is authenticated GET-only, JSON, and private no-store',async t=>{const f=fixture(t);f.seed();const response=await f.call();assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/application\/json/);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal((await f.call(undefined,{owner:null})).status,401);for(const method of ['POST','PUT','DELETE','HEAD'])assert.equal((await f.call(undefined,{method})).status,405);assert.equal(f.db.prepare('SELECT status FROM intake_requests').get().status,'received');});
test('inbox path executes only the two owner-scoped SELECTs and changes no SQLite row',async t=>{const f=fixture(t);f.seed();f.statements.length=0;const before=f.db.prepare('SELECT total_changes() AS n').get().n;await f.call();assert.equal(f.db.prepare('SELECT total_changes() AS n').get().n,before);assert.equal(f.statements.length,2);assert.equal(f.statements.every(sql=>/^SELECT\b/.test(sql)&&sql.includes('owner_id=?')),true);});
test('keyset cursor paginates more than 50 items without repeats or omissions across equal mixed-format timestamps',async t=>{
 const f=fixture(t),states=['received','read','accepted','needs_confirmation'];
 for(let i=0;i<125;i++){let createdAt=new Date(Date.parse('2026-10-08T10:00:00.000Z')+Math.floor(i/5)*1000).toISOString();if(i%2===0)createdAt=createdAt.replace('.000Z','Z');f.seed({id:'page-'+String(i).padStart(3,'0'),status:states[i%4],createdAt});}
 const expected=f.db.prepare('SELECT id FROM intake_requests ORDER BY julianday(created_at) DESC,id DESC').all().map(row=>row.id),seen=[],sizes=[];let cursor=null;
 do{const page=await f.service.inbox('owner-a',cursor);assert.equal(page.pendingCount,125);assert.equal(page.unreadCount,32);assert.equal(page.truncated,Boolean(page.nextCursor));sizes.push(page.requests.length);seen.push(...page.requests.map(row=>row.id));cursor=page.nextCursor;}while(cursor);
 assert.deepEqual(sizes,[50,50,25]);assert.deepEqual(seen,expected);assert.equal(new Set(seen).size,125);
});
test('HTTP follows nextCursor while total counts remain complete rather than page-local',async t=>{
 const f=fixture(t);for(let i=0;i<61;i++)f.seed({id:'http-page-'+String(i).padStart(3,'0'),status:i<30?'received':'accepted'});
 const first=await(await f.call()).json();assert.equal(first.requests.length,50);assert.ok(first.nextCursor);const secondResponse=await f.call('/api/intake/inbox?cursor='+encodeURIComponent(first.nextCursor));assert.equal(secondResponse.status,200);const second=await secondResponse.json();assert.equal(second.requests.length,11);assert.equal(second.nextCursor,null);assert.equal(second.truncated,false);assert.equal(second.pendingCount,61);assert.equal(second.unreadCount,30);assert.equal(new Set([...first.requests,...second.requests].map(row=>row.id)).size,61);
});
test('newer arrivals between pages do not push previously returned requests into the next page',async t=>{
 const f=fixture(t);for(let i=0;i<60;i++)f.seed({id:'original-'+String(i).padStart(3,'0'),createdAt:'2026-10-08T10:00:00Z'});const first=await f.service.inbox('owner-a');f.seed({id:'new-arrival',createdAt:'2026-10-08T12:00:00Z'});const second=await f.service.inbox('owner-a',first.nextCursor);assert.equal(second.pendingCount,61);assert.equal(second.requests.length,10);assert.equal(second.nextCursor,null);assert.equal(new Set([...first.requests,...second.requests].map(row=>row.id)).size,60);assert.equal((await f.service.inbox('owner-a')).requests[0].id,'new-arrival');
});
test('malformed or unsupported cursors fail with invalid_inbox_cursor before any database read',async t=>{
 const f=fixture(t);f.seed();const encode=value=>Buffer.from(JSON.stringify(value)).toString('base64url');const valid={v:1,createdAt:now,id:'request-a'};
 const invalid=['','%', 'x'.repeat(401),encode(null),encode([]),encode({...valid,v:2}),encode({...valid,extra:true}),encode({v:1,id:'request-a'}),encode({...valid,createdAt:'2026-02-30T10:00:00Z'}),encode({...valid,createdAt:'2026-10-08T10:00:00+00:00'}),encode({...valid,id:"injection' OR 1=1"}),encode({...valid,id:'x'.repeat(101)})];
 for(const cursor of invalid){f.statements.length=0;await assert.rejects(f.service.inbox('owner-a',cursor),{code:'invalid_inbox_cursor'});assert.equal(f.statements.length,0);const response=await f.call('/api/intake/inbox?cursor='+encodeURIComponent(cursor));assert.equal(response.status,400);assert.equal((await response.json()).error,'invalid_inbox_cursor');}
});
test('inbox returns each actual version for accepted and unread requests without incrementing it',async t=>{
 const f=fixture(t);f.seed({id:'accepted-version',status:'accepted'});f.seed({id:'received-version'});f.db.prepare('UPDATE intake_requests SET version=37 WHERE id=?').run('accepted-version');const first=await f.service.inbox('owner-a');assert.equal(first.requests.find(row=>row.id==='accepted-version').version,37);assert.equal(first.requests.find(row=>row.id==='received-version').version,9);f.db.prepare('UPDATE intake_requests SET version=38 WHERE id=?').run('accepted-version');const second=await f.service.inbox('owner-a');assert.equal(second.requests.find(row=>row.id==='accepted-version').version,38);assert.equal(f.db.prepare('SELECT version FROM intake_requests WHERE id=?').get('accepted-version').version,38);
});
test('a cursor obtained for another owner never bypasses ownership for rows or aggregate counts',async t=>{
 const f=fixture(t);for(let i=0;i<60;i++)f.seed({id:'owner-b-'+String(i).padStart(3,'0'),owner:'owner-b'});f.seed({id:'owner-a-earlier',owner:'owner-a',createdAt:'2026-10-08T10:00:00Z'});const b=await f.service.inbox('owner-b'),a=await f.service.inbox('owner-a',b.nextCursor);assert.equal(a.pendingCount,1);assert.equal(a.unreadCount,1);assert.deepEqual(a.requests.map(row=>row.id),['owner-a-earlier']);assert.equal(a.nextCursor,null);
});
