import vm from 'node:vm';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {spawnSync} from 'node:child_process';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createWorker} from '../worker.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {intakeCapabilities,intakeDigest} from '../src/domain/intake.mjs';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
const source=JSON.parse(await readFile(new URL('../fixtures/synthetic.json',import.meta.url),'utf8'));
const owner='synthetic-owner';
function setup(t,{filename,env:overrides={}}={}){const fixture=sqliteIntakeFixture(filename);t.after(()=>fixture.close());const snapshot=structuredClone(source);snapshot.projectRegistry=[...new Set(snapshot.tasks.map(x=>x.project))].map((name,i)=>({id:'project-'+i,name}));const env={DB:fixture.binding,DOT_BOARD_SNAPSHOT:JSON.stringify(snapshot),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify(snapshot.projectRegistry),DOT_BOARD_INTAKE_ENABLED:'true',DOT_BOARD_INTAKE_READER_VERIFIED:'true',DOT_BOARD_INTAKE_WRITER_VERIFIED:'true',DOT_BOARD_INTAKE_MCP_ENABLED:'true',DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'true',...overrides};const worker=createWorker({});const call=(path,{method='GET',body,user=owner,origin='https://example.com',headers={}}={})=>worker.fetch(new Request('https://example.com'+path,{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),...(method==='POST'?{'content-type':'application/json',origin}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}),env);const mcp=(name,args,user=owner)=>call('/mcp',{method:'POST',body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}},user});return {fixture,env,worker,call,mcp,snapshot};}
async function input(ctx){const board=await(await ctx.call('/api/board')).json();const task=board.tasks[0];return {projectId:task.projectId,body:{clientSubmissionId:crypto.randomUUID(),body:'Synthetic project feedback',contextTaskId:task.id,viewedSnapshotRevision:board.snapshotRevision,viewedSnapshotImportedAt:board.importedAt,contextSummary:'Synthetic viewed state'}};}
async function submit(ctx,value){const response=await ctx.call(`/api/projects/${value.projectId}/requests`,{method:'POST',body:value.body});return {response,...await response.json()};}
async function result(response){const body=await response.json();return {response,...body.result?.structuredContent,protocolError:body.error,isError:body.result?.isError};}
test('capabilities fail closed and legacy projects receive no invented routing ID',async t=>{assert.equal(intakeCapabilities({},true).enabled,false);const ctx=setup(t,{env:{DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'false'}});assert.equal((await(await ctx.call('/api/intake/capabilities')).json()).enabled,false);const value=await input(ctx);assert.equal((await submit(ctx,value)).response.status,503);ctx.env.DOT_BOARD_SNAPSHOT=JSON.stringify(source);delete ctx.env.DOT_BOARD_PROJECT_REGISTRY;const board=await(await ctx.call('/api/board')).json();assert(board.projectSummaries.every(p=>p.id===null));});
test('snapshot revision stable on reread and changes with sanitized data',async t=>{const ctx=setup(t);const one=await(await ctx.call('/api/board')).json(),two=await(await ctx.call('/api/board')).json();assert.equal(one.snapshotRevision,two.snapshotRevision);ctx.snapshot.tasks[0].observation='A different synthetic observation';ctx.env.DOT_BOARD_SNAPSHOT=JSON.stringify(ctx.snapshot);assert.notEqual((await(await ctx.call('/api/board')).json()).snapshotRevision,one.snapshotRevision);});
test('persisted receipt, exact retry and changed-payload conflict',async t=>{const ctx=setup(t),value=await input(ctx),first=await submit(ctx,value);assert.equal(first.response.status,201);assert.equal(first.request.status,'received');assert.equal(first.request.clientSubmissionId,value.body.clientSubmissionId);const retry=await submit(ctx,value);assert.equal(retry.response.status,200);assert.equal(retry.request.id,first.request.id);assert.equal(retry.replayed,true);const changed=await submit(ctx,{...value,body:{...value.body,body:'Different'}});assert.equal(changed.response.status,409);const detail=await(await ctx.call('/api/requests/'+first.request.id)).json();assert.equal(detail.events.length,1);assert.equal(detail.request.version,1);});
test('submission at project level and stale context preserved without changing paused task',async t=>{const ctx=setup(t),value=await input(ctx);value.body.contextTaskId=null;value.body.viewedSnapshotRevision='sha256:'+'a'.repeat(64);const first=await submit(ctx,value);assert.equal(first.response.status,201);assert.equal(first.request.contextTaskId,null);assert.equal(first.request.contextStale,true);assert.equal(first.request.viewedSnapshotRevision,value.body.viewedSnapshotRevision);assert.equal((await(await ctx.call('/api/board')).json()).tasks.find(t=>t.id==='sample-paused').state,'paused');});
test('identity, origin, body size and malformed content fail safely',async t=>{const ctx=setup(t),value=await input(ctx),path=`/api/projects/${value.projectId}/requests`;assert.equal((await ctx.call(path,{method:'POST',body:value.body,user:null})).status,401);assert.equal((await ctx.call(path,{method:'POST',body:value.body,origin:'https://other.example'})).status,403);assert.equal((await ctx.call(path,{method:'POST',body:{...value.body,body:'x'.repeat(6001)}})).status,413);assert.equal((await ctx.call(path,{method:'POST',body:{...value.body,contextSummary:'x'.repeat(33000)}})).status,413);assert.equal((await ctx.call(path,{method:'POST',body:value.body,headers:{'content-type':'text/plain'}})).status,415);});
test('cross-project task is rejected; private identities never appear in receipts',async t=>{const ctx=setup(t),value=await input(ctx);const bad=await submit(ctx,{...value,body:{...value.body,contextTaskId:'not-the-project-task'}});assert.equal(bad.response.status,409);const good=await submit(ctx,value);const text=JSON.stringify(good.request);assert(!text.includes(owner));assert(!text.includes('payloadDigest'));assert.equal((await ctx.call('/api/requests/'+good.request.id,{user:'another-owner'})).status,404);});
test('MCP discovery has no private data; tool calls require identity and explicit bridge enablement',async t=>{const ctx=setup(t);const init=await ctx.call('/mcp',{method:'POST',user:null,body:{jsonrpc:'2.0',id:1,method:'initialize'}});assert.equal(init.status,200);const discover=await(await ctx.call('/mcp',{method:'POST',user:null,body:{jsonrpc:'2.0',id:2,method:'tools/list'}})).json();assert.deepEqual(discover.result.tools.map(tool=>tool.name),['get_request_inbox','get_board_snapshot','list_request_projects','list_project_requests','get_project_request','acknowledge_project_request','record_project_request_event']);assert(!JSON.stringify(discover).includes('Synthetic project'));assert.equal((await ctx.mcp('list_request_projects',{},null)).status,401);ctx.env.DOT_BOARD_INTAKE_MCP_ENABLED='false';assert.equal((await ctx.mcp('list_request_projects',{})).status,403);});
test('real MCP read does not acknowledge; ack is separate, idempotent and owner scoped',async t=>{const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value),requestId=created.request.id;const read=await result(await ctx.mcp('get_project_request',{requestId}));assert.equal(read.request.status,'received');assert.equal((await result(await ctx.mcp('get_project_request',{requestId},'another-owner'))).isError,true);const args={requestId,eventId:crypto.randomUUID(),expectedVersion:1};const ack=await result(await ctx.mcp('acknowledge_project_request',args));assert.equal(ack.request.status,'read');assert.equal(ack.request.version,2);assert.equal(ack.events.length,2);const replay=await result(await ctx.mcp('acknowledge_project_request',args));assert.equal(replay.replayed,true);assert.equal(replay.events.length,2);});
test('status machine requires reading, actual task linkage and completion evidence',async t=>{const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value),requestId=created.request.id;const event=(status,expectedVersion,extra={})=>ctx.mcp('record_project_request_event',{requestId,eventId:crypto.randomUUID(),expectedVersion,status,summary:'Synthetic verified status',...extra});assert.equal((await result(await event('accepted',1))).error,'invalid_transition');await ctx.mcp('acknowledge_project_request',{requestId,eventId:crypto.randomUUID(),expectedVersion:1});assert.equal((await result(await event('accepted',2))).request.status,'accepted');assert.equal((await result(await event('assigned',3))).error,'assignment_requires_task');assert.equal((await result(await event('assigned',3,{linkedTaskIds:['synthetic-task']}))).request.status,'assigned');assert.equal((await result(await event('in_progress',4))).request.status,'in_progress');assert.equal((await result(await event('completed',5))).error,'completion_requires_evidence');const done=await result(await event('completed',5,{evidenceLinks:[{label:'Synthetic result',url:'https://example.com/result'}]}));assert.equal(done.request.status,'completed');assert.equal(done.request.version,6);});
test('stale event versions cannot clobber another event',async t=>{const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value),requestId=created.request.id;await ctx.mcp('acknowledge_project_request',{requestId,eventId:crypto.randomUUID(),expectedVersion:1});const bad=await result(await ctx.mcp('record_project_request_event',{requestId,eventId:crypto.randomUUID(),expectedVersion:1,status:'accepted',summary:'Stale update'}));assert.equal(bad.error,'version_conflict');assert.equal((await(await ctx.call('/api/requests/'+requestId)).json()).request.status,'read');});
test('SQLite-backed D1 adapter persists after closing and reopening the connection',async t=>{const folder=await mkdtemp(join(tmpdir(),'intake-durable-'));t.after(()=>rm(folder,{recursive:true,force:true}));const filename=join(folder,'requests.sqlite');const one=sqliteIntakeFixture(filename),store=createD1IntakeStore(one.binding);const created=await store.create({id:'synthetic-durable',ownerId:owner,projectId:'project-0',clientSubmissionId:'synthetic-submission-1',payloadDigest:await intakeDigest({test:1}),body:'Synthetic durable request',contextTaskId:null,viewedSnapshotRevision:'sha256:'+'a'.repeat(64),viewedSnapshotImportedAt:'2026-01-01T00:00:00Z',contextSummary:'',contextStale:false,createdAt:'2026-01-01T00:00:00Z'});one.close();const two=sqliteIntakeFixture(filename);t.after(()=>two.close());assert.equal((await createD1IntakeStore(two.binding).get(created.request.id,owner)).request.body,'Synthetic durable request');});
test('storage failures produce no false receipt or private error details',async t=>{const ctx=setup(t),value=await input(ctx);ctx.env.DB={prepare(){throw Error('private connection detail');},batch(){throw Error('private connection detail');}};const failed=await submit(ctx,value);assert.equal(failed.response.status,503);assert.equal(failed.error,'storage_unavailable');assert.equal(failed.request,undefined);assert(!JSON.stringify(failed).includes('private connection detail'));});
test('renaming a registry label preserves immutable project routing',async t=>{const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value);const entry=ctx.snapshot.projectRegistry.find(p=>p.id===value.projectId);const oldName=entry.name;entry.name='Renamed synthetic project';entry.aliases=[oldName];ctx.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify(ctx.snapshot.projectRegistry);ctx.env.DOT_BOARD_SNAPSHOT=JSON.stringify(ctx.snapshot);const board=await(await ctx.call('/api/board')).json();assert.equal(board.tasks.find(t=>t.id===value.body.contextTaskId).projectId,value.projectId);assert.equal((await(await ctx.call(`/api/projects/${value.projectId}/requests`)).json()).requests[0].id,created.request.id);});
test('cursor pagination returns each owner-scoped receipt exactly once',async t=>{const ctx=setup(t),value=await input(ctx);for(let i=0;i<27;i++)await submit(ctx,{...value,body:{...value.body,clientSubmissionId:crypto.randomUUID(),body:'Synthetic request '+i}});const first=await(await ctx.call(`/api/projects/${value.projectId}/requests`)).json();assert.equal(first.requests.length,25);assert(first.nextCursor);const next=await(await ctx.call(`/api/projects/${value.projectId}/requests?cursor=${first.nextCursor}`)).json();assert.equal(next.requests.length,2);assert.equal(next.nextCursor,null);assert.equal(new Set([...first.requests,...next.requests].map(r=>r.id)).size,27);assert.equal((await(await ctx.call(`/api/projects/${value.projectId}/requests`,{user:'another-owner'})).json()).requests.length,0);});
test('MCP rejects invalid method arguments, protocols, and foreign origins',async t=>{const ctx=setup(t);assert.equal((await result(await ctx.mcp('list_project_requests',{projectId:5}))).protocolError.code,-32602);assert.equal((await ctx.call('/mcp',{method:'POST',body:{jsonrpc:'2.0',id:1,method:'ping'},headers:{'mcp-protocol-version':'9999-01-01'}})).status,400);assert.equal((await ctx.call('/mcp',{method:'POST',body:{jsonrpc:'2.0',id:1,method:'ping'},origin:'https://other.example'})).status,403);assert.equal((await ctx.call('/mcp')).status,405);const notify=await ctx.call('/mcp',{method:'POST',body:{jsonrpc:'2.0',method:'notifications/initialized'}});assert.equal(notify.status,202);assert.equal(await notify.text(),'');});
test('event failure rolls back the status update and keeps the receipt unchanged',async t=>{const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value),store=createD1IntakeStore(ctx.fixture.binding);ctx.fixture.db.exec("CREATE TRIGGER synthetic_event_failure BEFORE INSERT ON intake_events WHEN NEW.status='read' BEGIN SELECT RAISE(ABORT,'synthetic failure'); END");await assert.rejects(store.append(created.request.id,{eventId:crypto.randomUUID(),expectedVersion:1,status:'read',summary:'Synthetic',linkedTaskIds:[],evidenceLinks:[]},'synthetic-digest','2026-01-01T00:00:00Z'));const current=await store.get(created.request.id,owner);assert.equal(current.request.status,'received');assert.equal(current.request.version,1);assert.equal(current.events.length,1);});
test('built Worker shares the real request contract and keeps the bridge disabled by default',async t=>{const ctx=setup(t);const build=spawnSync(process.execPath,['scripts/build.mjs'],{cwd:new URL('../',import.meta.url),encoding:'utf8'});assert.equal(build.status,0,build.stderr);const module=await import('../dist/server/index.js?test='+Date.now());const response=await module.default.fetch(new Request('https://example.com/api/intake/capabilities'),{DB:ctx.fixture.binding});const capabilities=await response.json();assert.equal(capabilities.enabled,false);assert.equal(capabilities.bridgeEnabled,false);});
test('an idempotent retry returns the receipt after the viewed task leaves the snapshot',async t=>{const ctx=setup(t),value=await input(ctx),first=await submit(ctx,value);ctx.snapshot.tasks=ctx.snapshot.tasks.filter(t=>t.id!==value.body.contextTaskId);ctx.env.DOT_BOARD_SNAPSHOT=JSON.stringify(ctx.snapshot);const retry=await submit(ctx,value);assert.equal(retry.response.status,200);assert.equal(retry.request.id,first.request.id);assert.equal(retry.replayed,true);});
test('registry-only projects are not presented or accepted without an observed source label',async t=>{const ctx=setup(t);ctx.snapshot.projectRegistry.push({id:'project-empty',name:'Empty synthetic project'});ctx.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify(ctx.snapshot.projectRegistry);ctx.env.DOT_BOARD_SNAPSHOT=JSON.stringify(ctx.snapshot);const board=await(await ctx.call('/api/board')).json();assert(!board.projectSummaries.some(p=>p.id==='project-empty'));const value=await input(ctx);value.projectId='project-empty';value.body.contextTaskId=null;assert.equal((await submit(ctx,value)).response.status,404);});
test('a database binding without migrated schema is not advertised as available',async t=>{const ctx=setup(t);ctx.fixture.db.exec('DROP TABLE intake_events');const capabilities=await(await ctx.call('/api/intake/capabilities')).json();assert.equal(capabilities.storageAvailable,false);assert.equal(capabilities.enabled,false);});
test('submission readiness requires storage, activated bridge, verified plugin connection and explicit receipt permission',async t=>{
  const configured={DOT_BOARD_INTAKE_ENABLED:'true',DOT_BOARD_INTAKE_MCP_ENABLED:'true',DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'true'};
  assert.equal(intakeCapabilities({},true).canSubmit,false);
  assert.equal(intakeCapabilities(configured,false).canSubmit,false);
  for(const key of ['DOT_BOARD_INTAKE_ENABLED','DOT_BOARD_INTAKE_MCP_ENABLED','DOT_BOARD_INTAKE_CONNECTION_VERIFIED'])assert.equal(intakeCapabilities({...configured,[key]:'false'},true).canSubmit,false,key);
  const bootstrap=intakeCapabilities(configured,true);assert.equal(bootstrap.canSubmit,true);assert.equal(bootstrap.enabled,false);assert.equal(bootstrap.readerVerified,false);assert.equal(bootstrap.writerVerified,false);
});
test('connected bootstrap accepts a first real receipt while full readiness stays false through read and acknowledgement',async t=>{
  const ctx=setup(t,{env:{DOT_BOARD_INTAKE_READER_VERIFIED:'false',DOT_BOARD_INTAKE_WRITER_VERIFIED:'false'}}),value=await input(ctx);
  let caps=await(await ctx.call('/api/intake/capabilities')).json();assert.equal(caps.canSubmit,true);assert.equal(caps.enabled,false);
  const created=await submit(ctx,value);assert.equal(created.response.status,201);assert.equal(created.request.status,'received');
  const read=await result(await ctx.mcp('get_project_request',{requestId:created.request.id}));assert.equal(read.request.status,'received');
  const ack=await result(await ctx.mcp('acknowledge_project_request',{requestId:created.request.id,eventId:crypto.randomUUID(),expectedVersion:1}));assert.equal(ack.request.status,'read');
  const browserReadback=await(await ctx.call('/api/requests/'+created.request.id)).json();assert.equal(browserReadback.request.status,'read');
  caps=await(await ctx.call('/api/intake/capabilities')).json();assert.equal(caps.enabled,false);
  ctx.env.DOT_BOARD_INTAKE_READER_VERIFIED='true';assert.equal((await(await ctx.call('/api/intake/capabilities')).json()).enabled,false);
  ctx.env.DOT_BOARD_INTAKE_WRITER_VERIFIED='true';assert.equal((await(await ctx.call('/api/intake/capabilities')).json()).enabled,true);
});
test('unverified connection or withdrawn receipt permission blocks new submissions without losing prior receipts',async t=>{
  const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value);ctx.env.DOT_BOARD_INTAKE_CONNECTION_VERIFIED='false';
  assert.equal((await submit(ctx,{...value,body:{...value.body,clientSubmissionId:crypto.randomUUID()}})).response.status,503);
  assert.equal((await(await ctx.call('/api/requests/'+created.request.id)).json()).request.id,created.request.id);
  ctx.env.DOT_BOARD_INTAKE_CONNECTION_VERIFIED='true';ctx.env.DOT_BOARD_INTAKE_ENABLED='false';assert.equal((await submit(ctx,{...value,body:{...value.body,clientSubmissionId:crypto.randomUUID()}})).response.status,503);
});
test('withdrawn intake permission still allows exact retry to recover an existing durable receipt without a new write',async t=>{
  const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value);ctx.env.DOT_BOARD_INTAKE_ENABLED='false';ctx.env.DOT_BOARD_INTAKE_CONNECTION_VERIFIED='false';
  const replay=await submit(ctx,value);assert.equal(replay.response.status,200);assert.equal(replay.request.id,created.request.id);assert.equal(replay.replayed,true);assert.equal(ctx.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,1);
});
test('same acknowledgement committing between initial read and event lookup replays the latest owner-scoped receipt',async t=>{
  const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value),base=createD1IntakeStore(ctx.fixture.binding),id=created.request.id;
  const raw={eventId:'deterministic-replay-ack',expectedVersion:1,status:'read',summary:'Synthetic read acknowledgement'};
  const digest=await intakeDigest({requestId:id,...raw});const scopes=[];let committed=false;
  const store={...base,get:async(requestId,ownerId)=>{scopes.push(ownerId);return base.get(requestId,ownerId);},existingEvent:async eventId=>{if(!committed){committed=true;await base.append(id,{...raw,linkedTaskIds:[],evidenceLinks:[]},digest,'2026-01-01T13:00:00Z');}return base.existingEvent(eventId);}};
  const service=createIntakeService({store,readBoard:async()=>({status:200,body:await(await ctx.call('/api/board')).json()}),capabilities:intakeCapabilities(ctx.env,true)});
  const replay=await service.append(id,raw,owner),persisted=await base.get(id,owner);
  assert.equal(replay.replayed,true);assert.equal(replay.request.status,'read');assert.equal(replay.request.version,persisted.request.version);assert.equal(replay.request.version,2);assert.equal(replay.events.length,2);assert.deepEqual(scopes,[owner,owner]);
});
test('twelve concurrent identical acknowledgements all return the committed read receipt',async t=>{
  const ctx=setup(t),value=await input(ctx),created=await submit(ctx,value),args={requestId:created.request.id,eventId:'concurrent-ack-regression',expectedVersion:1};
  const results=await Promise.all(Array.from({length:12},async()=>result(await ctx.mcp('acknowledge_project_request',args))));
  assert(results.every(r=>r.request.status==='read'&&r.request.version===2));assert.equal(results.filter(r=>r.replayed===false).length,1);
  const detail=await(await ctx.call('/api/requests/'+created.request.id)).json();assert.equal(detail.events.length,2);assert.equal(detail.request.version,2);
});
test('definitively rejected task context retains editable draft and corrected intent uses a new submission key',async t=>{
  const ctx=setup(t),value=await input(ctx),board=await(await ctx.call('/api/board')).json();
  const uiSource=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),storage=new Map(),submissions=[];
  // This headless draft fixture has no inbox DOM node, but still runs its real background read.
  const sandbox=vm.createContext({$:()=>null,board,crypto,AbortController,setTimeout,clearTimeout,URL,list:v=>Array.isArray(v)?v:[],tasks:()=>board.tasks,taskById:id=>board.tasks.find(task=>task.id===id),projectNames:()=>board.projects,formatted:String,sessionStorage:{setItem:(key,v)=>storage.set(key,v),getItem:key=>storage.get(key)??null},fetch:async(path,options={})=>{if(options.method==='POST')submissions.push(JSON.parse(options.body));return ctx.call(path,{method:options.method??'GET',body:options.body?JSON.parse(options.body):undefined});}});
  const section=uiSource.slice(uiSource.indexOf('// Intake drafts are local-only.'),uiSource.indexOf("$('request-project').addEventListener"));
  vm.runInContext(section+"\nrenderIntake=()=>{};renderRequestHistory=()=>{};loadRequestDetail=async()=>{};const backgroundReads=[],readInbox=loadInbox;loadInbox=(...args)=>{const pending=readInbox(...args);backgroundReads.push(pending);return pending;};globalThis.api={intake,inbox,backgroundReads,currentDraft,submitProjectRequest};",sandbox);
  const {api}=sandbox;api.intake.projectKey=value.projectId;api.intake.capabilities=intakeCapabilities(ctx.env,true);
  api.currentDraft().body='Keep this synthetic draft';api.currentDraft().contextTaskId=value.body.contextTaskId;
  ctx.snapshot.tasks=ctx.snapshot.tasks.filter(task=>task.id!==value.body.contextTaskId);ctx.env.DOT_BOARD_SNAPSHOT=JSON.stringify(ctx.snapshot);
  await api.submitProjectRequest();await Promise.all(api.backgroundReads.splice(0));assert.equal(api.inbox.error,'');assert.equal(api.inbox.value.requests.length,0);assert.equal(ctx.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,0);assert.equal(api.currentDraft().body,'Keep this synthetic draft');assert.equal(api.currentDraft().pending,null);assert.equal(JSON.parse(storage.get('dot-board-project-drafts-v1')).drafts[value.projectId].pending,null);
  api.currentDraft().contextTaskId=null;api.currentDraft().context=null;await api.submitProjectRequest();
  assert.equal(submissions.length,2);assert.notEqual(submissions[0].clientSubmissionId,submissions[1].clientSubmissionId);assert.equal(ctx.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,1);assert.equal(api.currentDraft().body,'');
  await Promise.all(api.backgroundReads.splice(0));assert.equal(api.inbox.loading,false);assert.equal(api.inbox.error,'');assert.equal(api.inbox.value.requests.length,1);assert.equal(api.inbox.value.requests[0].body,'Keep this synthetic draft');
});
