import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Worker} from 'node:worker_threads';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1ManualTaskStatusStore} from '../src/adapters/d1-manual-task-status.mjs';
import {createManualTaskStatusService} from '../src/application/manual-task-status-service.mjs';
import {createSitesManualTaskStatus} from '../src/application/sites-manual-task-status.mjs';
const now='2026-10-08T11:30:00.000Z';
const base={schemaVersion:'dot-board.snapshot/2',importedAt:'2026-10-08T01:00:00Z',source:{label:'Real original source'},tasks:[{id:'task-a',title:'Task A',project:'Project A',state:'unknown',observedAt:'2026-10-08T01:00:00Z',verification:{businessAcceptance:{state:'pending'}},businessVerification:{state:'pending'},reportedAgentActivity:{state:'unknown'},source:{label:'Original task source'}},{id:'task-b',title:'Task B',project:'Project A',state:'partial',observedAt:'2026-10-08T02:00:00Z'}],agents:[{id:'agent-a',activity:{state:'unknown',observedAt:'2026-10-08T01:00:00Z'}}]};
const registryBase=[{id:'project-a',name:'Project A',aliases:[],executionState:'active'}];
const input=(state='running',patch={})=>({taskId:'task-a',expectedVersion:0,eventId:'manual-event-1',state,...patch});
function fixture(t){const f=sqliteIntakeFixture();t.after(()=>f.close());const snapshot=structuredClone(base),registry=structuredClone(registryBase),store=createD1ManualTaskStatusStore(f.binding),service=createManualTaskStatusService({store,ownerId:'owner-a',readSnapshot:()=>snapshot,readRegistry:()=>registry,clock:()=>now});const controls=(state,{owner='owner-a',scope='task',target='task-a'}={})=>f.db.prepare('INSERT INTO dispatch_controls(owner_id,scope,target_id,state,version,reason,updated_at) VALUES (?,?,?,?,3,?,?)').run(owner,scope,target,state,'Existing explicit control',now);return {...f,snapshot,registry,store,service,controls};}
const errorCode=code=>error=>error.code===code;
const getControl=(f,id='task-a')=>f.db.prepare("SELECT * FROM dispatch_controls WHERE owner_id='owner-a' AND scope='task' AND target_id=?").get(id);

test('initial status has version zero/null state and explicit control object',async t=>{const f=fixture(t);assert.deepEqual(await f.service.get('owner-a','task-a'),{taskId:'task-a',version:0,state:null,reason:'',updatedAt:null,source:'owner_manual',executionControl:{state:'active',version:0,reason:''}});});
test('owner-bound service and task existence reject unrelated identities and IDs',async t=>{const f=fixture(t);for(const action of [()=>f.service.get('owner-b','task-a'),()=>f.service.set('owner-b',input()),()=>f.service.overlay('owner-b',base)])await assert.rejects(action(),errorCode('board_access_denied'));await assert.rejects(f.service.get('owner-a','missing'),errorCode('task_not_found'));await assert.rejects(f.service.set('owner-a',input('running',{taskId:'missing'})),errorCode('task_not_found'));});
test('running is only manual metadata and never changes observed state, source, verification, Agent activity, or timestamps',async t=>{const f=fixture(t),before=structuredClone(f.snapshot);const receipt=await f.service.set('owner-a',input());assert.equal(receipt.duplicate,false);assert.equal(receipt.version,1);assert.equal(receipt.state,'running');assert.equal(receipt.source,'owner_manual');const out=await f.service.overlay('owner-a',f.snapshot);assert.equal(out.tasks[0].manualStatus.state,'running');assert.equal(out.tasks[0].state,'unknown');for(const field of ['verification','businessVerification','reportedAgentActivity','source','observedAt'])assert.deepEqual(out.tasks[0][field],before.tasks[0][field]);assert.strictEqual(out.tasks[1],f.snapshot.tasks[1]);assert.strictEqual(out.agents,f.snapshot.agents);assert.equal(out.importedAt,before.importedAt);assert.deepEqual(f.snapshot,before);assert.equal(getControl(f),undefined);});
test('each manual state is accepted independently when no execution lock exists',async t=>{for(const state of ['queued','running','blocked','paused','completed','canceled']){const f=fixture(t);assert.equal((await f.service.set('owner-a',input(state))).state,state);}});
test('paused/canceled write task admission controls in the same transaction, completed writes deferred',async t=>{for(const [state,gate] of [['paused','paused'],['canceled','canceled'],['completed','deferred']]){const f=fixture(t);const result=await f.service.set('owner-a',input(state,{reason:'Explicit owner choice'}));assert.equal(getControl(f).state,gate);assert.equal(result.executionControl.state,gate);assert.equal(result.executionControl.version,1);assert.equal(getControl(f).reason,'Explicit owner choice');assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM dispatch_jobs').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM dispatch_resource_leases').get().n,0);}});
test('control INSERT failure rolls back the corresponding manual event',async t=>{const f=fixture(t);f.db.exec("CREATE TRIGGER reject_status_control BEFORE INSERT ON dispatch_controls BEGIN SELECT RAISE(ABORT,'synthetic control failure'); END");await assert.rejects(f.service.set('owner-a',input('paused')),/synthetic control failure/);assert.equal((await f.service.get('owner-a','task-a')).version,0);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM task_manual_status_events').get().n,0);});
test('identical replay does not increment manual or control versions; changed payload conflicts',async t=>{const f=fixture(t);const first=await f.service.set('owner-a',input('paused'));const again=await f.service.set('owner-a',input('paused'));assert.equal(again.duplicate,true);assert.equal(again.version,first.version);assert.equal(getControl(f).version,1);await assert.rejects(f.service.set('owner-a',input('paused',{reason:'Changed payload'})),errorCode('manual_status_event_conflict'));await assert.rejects(f.service.set('owner-a',input('paused',{taskId:'task-b'})),errorCode('manual_status_event_conflict'));});
test('same event replay after a newer state returns latest current manual status without adding another event',async t=>{const f=fixture(t);await f.service.set('owner-a',input('running'));await f.service.set('owner-a',input('blocked',{expectedVersion:1,eventId:'manual-event-2'}));const repeated=await f.service.set('owner-a',input('running'));assert.equal(repeated.duplicate,true);assert.equal(repeated.version,2);assert.equal(repeated.state,'blocked');assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM task_manual_status_events').get().n,2);});
test('stale expected version fails with 409 and journal is append-only',async t=>{const f=fixture(t);await f.service.set('owner-a',input());await assert.rejects(f.service.set('owner-a',input('blocked',{eventId:'another-event'})),error=>error.code==='manual_status_version_conflict'&&error.status===409);assert.throws(()=>f.db.exec("UPDATE task_manual_status_events SET state='completed'"),/append_only/);assert.throws(()=>f.db.exec('DELETE FROM task_manual_status_events'),/append_only/);});
test('paused/canceled task or project gates reject all other states and cancellation cannot downgrade to pause',async t=>{for(const gate of ['paused','canceled'])for(const scope of ['task','project']){const f=fixture(t);f.controls(gate,{scope,target:scope==='project'?'project-a':'task-a'});for(const state of ['queued','running','blocked','completed'])await assert.rejects(f.service.set('owner-a',input(state)),error=>error.code==='execution_control_locked'&&error.status===409);if(gate==='canceled')await assert.rejects(f.service.set('owner-a',input('paused')),errorCode('execution_control_locked'));assert.equal((await f.service.set('owner-a',input('canceled'))).state,'canceled');}});
test('static task pause/cancel and registry policy participate in locking and cannot be downgraded by completed',async t=>{for(const state of ['paused','canceled']){const f=fixture(t);f.snapshot.tasks[0].state=state;await assert.rejects(f.service.set('owner-a',input('completed')),errorCode('execution_control_locked'));assert.equal((await f.service.get('owner-a','task-a')).executionControl.state,state);assert.equal(getControl(f),undefined);const r=fixture(t);r.registry[0].executionState=state;await assert.rejects(r.service.set('owner-a',input('running')),errorCode('execution_control_locked'));}});
test('manual queued/running/blocked never clear an existing deferred control or activate a project',async t=>{const f=fixture(t);f.controls('deferred');f.registry[0].executionState='deferred';for(const [index,state] of ['queued','running','blocked'].entries()){const result=await f.service.set('owner-a',input(state,{expectedVersion:index,eventId:'non-activating-'+index}));assert.equal(result.executionControl.state,'deferred');assert.equal(getControl(f).version,3);}assert.equal(f.registry[0].executionState,'deferred');});
test('missing migration leaves overlay identity unchanged and GET/POST fail with 503',async t=>{const f=fixture(t);f.db.exec('DROP TABLE task_manual_status_events');assert.equal(await f.service.available(),false);assert.strictEqual(await f.service.overlay('owner-a',f.snapshot),f.snapshot);await assert.rejects(f.service.get('owner-a','task-a'),error=>error.status===503&&error.code==='manual_status_storage_unavailable');await assert.rejects(f.service.set('owner-a',input()),error=>error.status===503&&error.code==='manual_status_storage_unavailable');});
test('unknown fields, invalid versions/states and unsafe reasons are rejected without writes',async t=>{const f=fixture(t);for(const value of [input('reviewing'),input('running',{expectedVersion:-1}),input('running',{expectedVersion:1.5}),input('running',{source:'agent'}),input('running',{reason:'/workspace/private/source'}),input('running',{reason:'x'.repeat(1201)})])await assert.rejects(f.service.set('owner-a',value));assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM task_manual_status_events').get().n,0);});
test('dispatch-prefixed task writes canonical gate and cannot bypass an existing canonical cancellation',async t=>{const f=fixture(t);f.snapshot.tasks[0].id='dispatch:existing-job';f.controls('canceled',{target:'existing-job'});await assert.rejects(f.service.set('owner-a',input('paused',{taskId:'dispatch:existing-job'})),errorCode('execution_control_locked'));const receipt=await f.service.set('owner-a',input('canceled',{taskId:'dispatch:existing-job'}));assert.equal(receipt.executionControl.state,'canceled');assert.equal(getControl(f,'existing-job').state,'canceled');});
test('owner-scoped store IDs and execution controls remain isolated',async t=>{const f=fixture(t);await f.service.set('owner-a',input('paused'));const serviceB=createManualTaskStatusService({store:f.store,ownerId:'owner-b',readSnapshot:()=>f.snapshot,readRegistry:()=>f.registry,clock:()=>now});assert.equal((await serviceB.get('owner-b','task-a')).version,0);assert.equal((await serviceB.set('owner-b',input('running'))).state,'running');assert.equal((await f.service.get('owner-a','task-a')).state,'paused');assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM task_manual_status_events').get().n,2);});
test('Sites facade uses current env owner and source snapshot without changing process state',async t=>{const f=fixture(t),env={DB:f.binding,DOT_BOARD_OWNER_ID:'owner-a',DOT_BOARD_SNAPSHOT:JSON.stringify(f.snapshot),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify(f.registry)};const service=createSitesManualTaskStatus(env,{clock:()=>now});assert.equal((await service.set('owner-a',input('completed'))).state,'completed');await assert.rejects(service.get('owner-b','task-a'),errorCode('board_access_denied'));});
async function race(t,identical){const dir=mkdtempSync(join(tmpdir(),'manual-task-status-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const filename=join(dir,'db.sqlite'),f=sqliteIntakeFixture(filename);t.after(()=>f.close());const workers=Array.from({length:8},(_,index)=>new Worker(new URL('./manual-task-status-worker.mjs',import.meta.url),{workerData:{filename,snapshot:base,registry:registryBase,now,input:input('paused',{eventId:identical?'same-event':'race-'+index})}}));t.after(async()=>Promise.all(workers.map(worker=>worker.terminate())));await Promise.all(workers.map(worker=>new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);})));const waiting=workers.map(worker=>new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);}));workers.forEach(worker=>worker.postMessage('go'));return {db:f.db,results:await Promise.all(waiting)};}
test('eight real SQLite CAS writers commit one manual version and one gate version',async t=>{const {db,results}=await race(t,false);assert.equal(results.filter(x=>x.ok).length,1,JSON.stringify(results));assert.equal(db.prepare('SELECT COUNT(*) AS n FROM task_manual_status_events').get().n,1);assert.equal(db.prepare('SELECT version FROM dispatch_controls').get().version,1);});
test('eight concurrent identical events all succeed with one manual event and one gate mutation',async t=>{const {db,results}=await race(t,true);assert.equal(results.every(x=>x.ok),true,JSON.stringify(results));assert.equal(results.filter(x=>!x.result.duplicate).length,1);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM task_manual_status_events').get().n,1);assert.equal(db.prepare('SELECT version FROM dispatch_controls').get().version,1);});
test('completed only closes admission and leaves a live job, held slot, thread binding and resource lease intact',async t=>{const f=fixture(t);f.db.prepare('INSERT INTO intake_requests(id,owner_id,project_id,client_submission_id,payload_digest,body,context_task_id,viewed_snapshot_revision,viewed_snapshot_imported_at,context_summary,context_stale,status,created_at,updated_at,version,linked_task_ids,latest_summary) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('active-request','owner-a','project-a','active-submit','a'.repeat(64),'Synthetic active work','task-a','sha256:'+('a'.repeat(64)),now,'',0,'in_progress',now,now,3,'[]','');f.db.prepare("INSERT INTO dispatch_jobs(id,owner_id,project_id,request_id,request_version,priority,state,environment_type,environment_id,root_job_id,thread_id,dispatch_key,holds_slot,context_task_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'running',?,?,?,?,?,1,?,?,?)").run('active-job','owner-a','project-a','active-request',3,0,'computer','synthetic-environment','active-job','private-live-thread','private-live-key','task-a',now,now);f.db.prepare('INSERT INTO dispatch_resource_leases(resource_key,owner_id,job_id,dispatch_key,acquired_at,expires_at) VALUES (?,?,?,?,?,?)').run('repository:synthetic','owner-a','active-job','private-live-key',now,'2026-10-08T11:35:00Z');const beforeJob=f.db.prepare('SELECT * FROM dispatch_jobs').get(),beforeLease=f.db.prepare('SELECT * FROM dispatch_resource_leases').get();await f.service.set('owner-a',input('completed'));assert.deepEqual(f.db.prepare('SELECT * FROM dispatch_jobs').get(),beforeJob);assert.deepEqual(f.db.prepare('SELECT * FROM dispatch_resource_leases').get(),beforeLease);assert.equal(getControl(f).state,'deferred');});
test('a pause raced in immediately before CAS rejects the status rather than reopening admission',async t=>{const f=fixture(t);let inserted=false;const binding={...f.binding,batch:async statements=>{if(!inserted){inserted=true;f.controls('paused');}return f.binding.batch(statements);}},service=createManualTaskStatusService({store:createD1ManualTaskStatusStore(binding),ownerId:'owner-a',readSnapshot:()=>f.snapshot,readRegistry:()=>f.registry,clock:()=>now});await assert.rejects(service.set('owner-a',input('running')),errorCode('execution_control_locked'));assert.equal((await service.get('owner-a','task-a')).version,0);assert.equal(getControl(f).state,'paused');});
