import test from 'node:test';import assert from 'node:assert/strict';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1DispatchQueue} from '../src/adapters/d1-dispatch-queue.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {createDispatchService} from '../src/application/dispatch-service.mjs';
import {dispatchOne} from '../src/application/dispatch-host.mjs';
async function setup(t){const f=sqliteIntakeFixture();t.after(()=>f.close());let now='2026-10-08T10:00:00.000Z',n=0;const clock=()=>now,id=()=>`manual-test-${++n}`,store=createD1DispatchQueue(f.binding),intake=createD1IntakeStore(f.binding),registry=[{id:'project-a',executionState:'deferred'}],environment={type:'computer',id:'original-environment'};await store.registerBinding('owner-a',{taskId:'task-a',projectId:'project-a',threadId:'original-thread',environment,evidence:'Verified original binding'},now);for(const requestId of ['request-one','request-two']){await intake.create({id:requestId,ownerId:'owner-a',projectId:'project-a',clientSubmissionId:id(),payloadDigest:'a'.repeat(64),body:'Synthetic owner prepared work',contextTaskId:'task-a',viewedSnapshotRevision:'sha256:'+'a'.repeat(64),viewedSnapshotImportedAt:now,contextSummary:'',contextStale:false,createdAt:now});f.db.prepare("UPDATE intake_requests SET status='accepted',version=3 WHERE id=?").run(requestId);}const requests={get:async(requestId,owner)=>{const r=await intake.get(requestId,owner);if(!r)throw Error('not owned');return r;}};const service=createDispatchService({store,requests,enabled:true,capacity:6,clock,newId:id,readRegistry:async()=>registry});const grant=()=>store.authorizeManualRequest('owner-a',{requestId:'request-one',projectId:'project-a',taskId:'task-a',expiresAt:'2026-10-08T10:01:00.000Z',reason:'Owner explicitly authorized this one request'},clock());const enqueue=(requestId='request-one')=>service.enqueue('owner-a',{eventId:id(),requestId,expectedRequestVersion:3,environment,resources:[]});return {...f,clock,id,store,service,registry,environment,grant,enqueue,setTime:x=>now=x};}
test('one accepted original-bound request crosses deferred; neighbors remain blocked and no new resource is invented',async t=>{const c=await setup(t);await assert.rejects(c.enqueue(),{code:'execution_paused'});await c.grant();const q=await c.enqueue();assert.equal(q.job.threadId,'original-thread');assert.deepEqual(q.job.resources,[]);await assert.rejects(c.enqueue('request-two'),{code:'execution_paused'});const eventId=c.id(),a=await c.service.claim('owner-a',{eventId}),b=await c.service.claim('owner-a',{eventId});assert.equal(a.job.id,q.job.id);assert.equal(b.replayed,true);assert.equal((await c.store.list('owner-a')).length,1);assert.equal((await c.service.claim('owner-a',{eventId:c.id()})).job,null);});
test('authorization cannot use another owner, missing binding, or change existing expiry',async t=>{const c=await setup(t);const value={requestId:'request-one',projectId:'project-a',taskId:'task-a',expiresAt:'2026-10-08T10:01:00Z',reason:'Explicit one request'};await assert.rejects(c.store.authorizeManualRequest('owner-b',value,c.clock()),{code:'manual_request_unprepared'});await assert.rejects(c.store.authorizeManualRequest('owner-a',{...value,taskId:'unregistered'},c.clock()),{code:'manual_request_unprepared'});await c.grant();await assert.rejects(c.store.authorizeManualRequest('owner-a',{...value,expiresAt:'2026-10-08T11:00:00Z'},c.clock()),{code:'manual_authorization_conflict'});});
test('paused and canceled registry or durable controls override the one-request exception',async t=>{for(const state of ['paused','canceled']){const c=await setup(t);await c.grant();await c.enqueue();c.registry[0].executionState=state;assert.equal((await c.service.claim('owner-a',{eventId:c.id()})).job,null);c.registry[0].executionState='deferred';await c.store.setControl('owner-a','task','task-a',state,0,'Owner control',c.clock());assert.equal((await c.service.claim('owner-a',{eventId:c.id()})).job,null);await assert.rejects(c.enqueue('request-two'),{code:'execution_paused'});}});
test('expiry is rechecked inside claim and expired claimed authorization retains its slot',async t=>{const c=await setup(t);await c.grant();await c.enqueue();const ids=await c.store.manualAuthorizationIds('owner-a',c.clock(),['project-a']);assert.deepEqual(ids,['request-one']);const expired=await c.store.claim('owner-a',c.id(),'digest',c.id(),6,'2026-10-08T10:01:00.000Z',[],ids);assert.equal(expired.job,null);const claimed=await c.service.claim('owner-a',{eventId:c.id()});assert.equal(claimed.job.holdsSlot,true);c.setTime('2026-10-08T10:01:00.000Z');await assert.rejects(c.service.preflight('owner-a',claimed.job),{code:'manual_authorization_expired'});assert.equal((await c.store.get('owner-a',claimed.job.id)).holdsSlot,true);});
test('durable deferred control is bypassed only for exact original bound request and active legacy remains normal',async t=>{const c=await setup(t);await c.store.setControl('owner-a','project','project-a','deferred',0,'Deferred project',c.clock());await c.grant();const q=await c.enqueue();assert.equal((await c.service.claim('owner-a',{eventId:c.id()})).job.id,q.job.id);const d=await setup(t);d.registry[0].executionState='active';const normal=await d.enqueue('request-two');assert.equal((await d.service.claim('owner-a',{eventId:d.id()})).job.id,normal.job.id);});
test('authorization replay after claimed and expired returns original immutable row without renewal',async t=>{const c=await setup(t),original=await c.grant();await c.enqueue();await c.service.claim('owner-a',{eventId:c.id()});c.setTime('2026-10-08T11:00:00Z');assert.deepEqual(await c.grant(),original);});
test('expiry raced into atomic begin retains claimed state and slot even without durable controls',async t=>{const c=await setup(t);await c.grant();await c.enqueue();const {job}=await c.service.claim('owner-a',{eventId:c.id()});const change=c.store.change.bind(c.store);c.store.change=async(...args)=>{args[7]='2026-10-08T10:01:00.000Z';return change(...args);};await assert.rejects(c.service.update('owner-a',{jobId:job.id,eventId:c.id(),expectedVersion:job.version,dispatchKey:job.dispatchKey,threadId:job.threadId,environment:c.environment,action:'begin',summary:'Synthetic begin'}),{code:'version_conflict'});assert.equal((await c.store.get('owner-a',job.id)).holdsSlot,true);});

test('real host does not checkpoint or release a claimed slot when manual authority expires during environment read',async t=>{const c=await setup(t);await c.grant();await c.enqueue();let called=0;const adapter={environmentStatus:async()=>{c.setTime('2026-10-08T10:01:00.000Z');return {available:true};},create:async()=>{called++;},followup:async()=>{called++;}};await assert.rejects(dispatchOne({service:c.service,ownerId:'owner-a',eventId:c.id(),newId:c.id,adapter}),{code:'manual_authorization_expired'});const jobs=await c.store.list('owner-a');assert.equal(jobs[0].state,'claimed');assert.equal(jobs[0].holdsSlot,true);assert.equal(called,0);});
