// All provider writes in this file are synthetic. No native tool or network call.
import test from 'node:test';import assert from 'node:assert/strict';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {createD1DispatchQueue} from '../src/adapters/d1-dispatch-queue.mjs';
import {createDispatchService} from '../src/application/dispatch-service.mjs';
import {dispatchOne} from '../src/application/dispatch-host.mjs';
import {createCloudThreadsAdapter} from '../src/adapters/cloud-threads-adapter.mjs';
import {createCloudThreadDecoder} from '../src/adapters/cloud-thread-observation.mjs';
import {createD1NativeDispatchJournal} from '../src/adapters/d1-native-dispatch-journal.mjs';
import {createNativeHostPreflight,reconcileNativeDispatch} from '../src/application/native-dispatch-host.mjs';
import {queueTarget} from '../src/domain/dispatch-queue.mjs';
const environment={type:'existing_thread',id:null},threadId='synthetic-original-thread';
async function fixture(t,options={}){
 const db=sqliteIntakeFixture();t.after(()=>db.close());let n=0;const id=()=>`opaque-${++n}`,clock=()=> '2026-10-08T05:00:00Z',contexts=[{id:'original-task',projectId:'p'}];
 const requests=createIntakeService({store:createD1IntakeStore(db.binding),capabilities:{canSubmit:true,storageAvailable:true},clock,newId:id,readBoard:async()=>({status:200,body:{snapshotRevision:'sha256:'+'0'.repeat(64),projectSummaries:[{id:'p',name:'Synthetic project'}],tasks:contexts}})});
 const store=createD1DispatchQueue(db.binding),service=createDispatchService({store,requests,enabled:true,capacity:6,clock,newId:id,readRegistry:async()=>[{id:'p',executionState:'active'}]});
 await service.registerBinding('owner',{taskId:'original-task',projectId:'p',threadId,environment,verified:true,evidence:'Synthetic authenticated original-thread read, no literal environment ID'});
 async function enqueue({contextTaskId='original-task',owner='owner'}={}){let {request:r}=await requests.submit('p',owner,{clientSubmissionId:'synthetic-client-'+id(),body:'Continue only the original authorized synthetic task.',viewedSnapshotRevision:'sha256:'+'0'.repeat(64),viewedSnapshotImportedAt:clock(),contextTaskId});for(const status of ['read','accepted'])r=(await requests.append(r.id,{eventId:id(),expectedVersion:r.version,status,summary:status},owner)).request;return service.enqueue(owner,{eventId:id(),requestId:r.id,expectedRequestVersion:r.version,environment,resources:[{kind:'browser',id:'synthetic-shared-browser'}]});}
 const calls=[],state={turnId:'previous-turn',status:'completed',accept:false,noActiveWriter:true,policy:{},...options};
 const find=async requestId=>(await store.list('owner')).find(x=>x.requestId===requestId);
 const data=structuredContent=>({structuredContent,isError:false});let reads=0;
 const provider={read:{list_environments:async()=>{calls.push('list_environments');throw Error('Opaque continuation must not select a computer');},list_threads:async()=>{calls.push('list_threads');return data({threads:[]});},read:async({threadId:target})=>{calls.push('read');reads++;if(state.beforeRead)state.beforeRead(reads,state);return data({threadId:target,latestTurn:{id:state.turnId,status:state.status,error:null},items:[{id:'result-item-'+state.turnId,turnId:state.turnId,role:'assistant',text:'Synthetic work has remaining acceptance checks.'}]});}},write:{create:async()=>{calls.push('create');throw Error('Opaque binding cannot create');},send_message:async args=>{calls.push(['send',args]);if(state.timeout)throw Error('Ambiguous transport timeout');if(state.response)return data(state.response);state.turnId='new-turn';state.status='inProgress';return data({turnId:state.turnId});}}};
 const decodeObservation=createCloudThreadDecoder({clock,lookupBinding:async()=>({verified:true,threadId,environment}),inspectExecution:async()=>({verified:true,noActiveWriter:state.noActiveWriter}),acceptResult:async()=>state.accept?{verified:true,noActiveWriter:true,outcome:'completed',completedScope:['Synthetic business acceptance checked'],pendingChecks:[]}:null});
 const config={ownerId:'owner',provider,journal:createD1NativeDispatchJournal(db.binding,{clock}),decodeObservation,loadAuthorization:async({requestId})=>({ownerId:'owner',requestId,threadId,environment,existingThreadVerified:true,environmentConstraintsSatisfied:true,connectionStatus:'unknown',executionAllowed:true,readAllowed:true,allowCreate:true,allowFollowup:true,title:'Synthetic original work',approvedPrompt:'Continue only the existing authorized synthetic scope.',...state.policy}),preflight:createNativeHostPreflight({service,loadCurrentJob:(_owner,requestId)=>find(requestId),authorizeRead:async()=>true})};
 const adapter=createCloudThreadsAdapter(config),run=()=>dispatchOne({service,ownerId:'owner',eventId:id(),adapter,newId:id});
 return {db,service,store,requests,enqueue,adapter,config,run,calls,state,id,find,contexts};
}
const sends=c=>c.calls.filter(x=>Array.isArray(x)&&x[0]==='send');
test('opaque schema carries no invented environment ID and creation is forbidden',async t=>{assert.deepEqual(queueTarget(environment),environment);assert.throws(()=>queueTarget({...environment,id:'invented'}),{code:'invalid_environment'});const c=await fixture(t);await assert.rejects(c.adapter.create({operationId:'op',requestId:'request',environment}),{code:'creation_denied'});assert.equal(c.calls.length,0);assert.deepEqual(await c.adapter.environmentStatus(environment),{available:null,connectionStatus:'unknown',reason:'Platform retains the original executor; use authorized continuation preflight'});});
test('opaque enqueue requires an existing verified original task binding',async t=>{const c=await fixture(t);await assert.rejects(c.enqueue({contextTaskId:null}),{code:'original_thread_unverified'});await assert.rejects(c.enqueue({owner:'other-owner'}),{code:'original_thread_unverified'});});
test('opaque original continuation uses only threadId, retains null environment, and admission keeps resource lease',async t=>{const c=await fixture(t),first=await c.enqueue();const r=await c.run();assert.equal(r.job.id,first.job.id);assert.equal(r.job.state,'assigned');assert.equal(r.job.threadId,threadId);assert.equal(r.job.environmentId,null);assert.equal(r.job.environmentType,'existing_thread');assert.equal(r.job.holdsSlot,true);assert.equal((await c.store.leases('owner',r.job.id)).length,1);assert.deepEqual(sends(c)[0][1],{threadId,prompt:'Continue only the existing authorized synthetic scope.'});assert(!c.calls.includes('list_environments'));assert(!c.calls.includes('create'));assert.equal(r.job.executionEvidence,null);});
test('pending business acceptance does not prevent authorized continuation but never completes it',async t=>{const c=await fixture(t);await c.enqueue();const r=await c.run();c.state.status='completed';let result=await reconcileNativeDispatch({service:c.service,ownerId:'owner',job:r.job,adapter:c.adapter,newId:c.id});assert.equal(result.released,false);assert.equal(result.observation.active,false);assert.equal(result.observation.businessCompleted,false);assert.equal((await c.store.leases('owner',r.job.id)).length,1);c.state.accept=true;result=await reconcileNativeDispatch({service:c.service,ownerId:'owner',job:r.job,adapter:c.adapter,newId:c.id});assert.equal(result.released,true);assert.equal(result.job.executionEvidence.terminal,true);assert.equal((await c.store.leases('owner',r.job.id)).length,0);});
for(const [name,patch]of Object.entries({unverified:{existingThreadVerified:false},constraints:{environmentConstraintsSatisfied:false},owner:{ownerId:'different-owner'},request:{requestId:'different-request'},thread:{threadId:'different-thread'},paused:{paused:true},canceled:{canceled:true},offline:{connectionStatus:'offline'}}))test('opaque '+name+' denies continuation without a native write',async t=>{const c=await fixture(t,{policy:patch});await c.enqueue();const r=await c.run();assert.equal(r.executed,false);assert.equal(sends(c).length,0);assert(!c.calls.includes('create'));});
test('active turn read retains reservation and resources without automatic continuation',async t=>{const c=await fixture(t,{status:'inProgress'});await c.enqueue();const r=await c.run();assert.equal(r.executed,false);assert.equal(sends(c).length,0);assert.equal(r.job.state,'uncertain');assert.equal(r.job.holdsSlot,true);assert.equal((await c.store.leases('owner',r.job.id)).length,1);assert.equal(r.requiresReconciliation,true);assert.equal((await c.run()).job,null);});
test('completed turn without verified writer absence cannot continue',async t=>{const c=await fixture(t,{noActiveWriter:false});await c.enqueue();const r=await c.run();assert.equal(r.executed,false);assert.equal(sends(c).length,0);});
test('turn changed during final read keeps claim uncertain and does not send',async t=>{const c=await fixture(t,{beforeRead:(n,s)=>{if(n===3){s.turnId='racing-turn';s.status='inProgress';}}});await c.enqueue();const r=await c.run();assert.equal(r.job.state,'uncertain');assert.equal(r.job.holdsSlot,true);assert.equal(sends(c).length,0);});
for(const [name,response]of Object.entries({sameTurn:{turnId:'previous-turn'},steered:{turnId:'different-turn',steered:true},statusUnknown:{turnId:'different-turn',status:'unknown'},missingTurn:{}}))test('opaque '+name+' response retains slot, rereads and never resends on another event',async t=>{const c=await fixture(t,{response});await c.enqueue();await c.enqueue();const r=await c.run();assert.equal(r.job.state,'uncertain');assert.equal(r.job.holdsSlot,true);assert.equal(sends(c).length,1);assert(c.calls.filter(x=>x==='read').length>=4);assert.equal((await c.run()).job,null);assert.equal(sends(c).length,1);});
test('opaque timeout stays uncertain through a fresh adapter with durable journal',async t=>{const c=await fixture(t,{timeout:true});await c.enqueue();const r=await c.run();assert.equal(r.job.state,'uncertain');const adapter=createCloudThreadsAdapter({...c.config,preflight:async()=>({allowed:true})});await assert.rejects(adapter.followup({operationId:r.job.dispatchKey,requestId:r.job.requestId,threadId,environment}),{code:'dispatch_uncertain'});assert.equal(sends(c).length,1);assert.equal((await c.store.leases('owner',r.job.id)).length,1);});
test('another resource holder and explicit project pause block opaque queue claims',async t=>{const c=await fixture(t);c.contexts.push({id:'another-original-task',projectId:'p'});await c.service.registerBinding('owner',{taskId:'another-original-task',projectId:'p',threadId:'another-synthetic-thread',environment,verified:true,evidence:'Synthetic distinct original thread binding'});const one=await c.enqueue(),two=await c.enqueue({contextTaskId:'another-original-task'});await c.run();assert.equal((await c.run()).job,null);assert.equal((await c.store.get('owner',two.job.id)).state,'queued');assert.equal((await c.store.get('owner',one.job.id)).holdsSlot,true);const d=await fixture(t);await d.enqueue();await d.service.control('owner',{scope:'project',targetId:'p',state:'paused',expectedVersion:0,reason:'Synthetic user pause'});assert.equal((await d.run()).job,null);assert.equal(sends(d).length,0);});
test('paused task remains observable through read grant, but cannot follow up',async t=>{const c=await fixture(t);const q=await c.enqueue();const r=await c.run();c.state.policy={paused:true,executionAllowed:false};const result=await c.adapter.observe({requestId:q.job.requestId,operationId:r.job.dispatchKey,threadId,turnId:r.job.turnId,environment});assert.equal(result.threadId,threadId);await assert.rejects(c.adapter.followup({requestId:q.job.requestId,operationId:r.job.dispatchKey,threadId,environment}),{code:'execution_denied'});assert.equal(sends(c).length,1);});

test('opaque followup does not require a new-task title',async t=>{const c=await fixture(t,{policy:{title:undefined}});await c.enqueue();const r=await c.run();assert.equal(r.job.state,'assigned');assert.equal(sends(c).length,1);assert(!Object.hasOwn(sends(c)[0][1],'title'));});

test('unknown original-writer read failure retains resources and never fabricates a safe checkpoint',async t=>{const c=await fixture(t,{beforeRead:()=>{throw Error('Synthetic unavailable readback');}});await c.enqueue();const r=await c.run();assert.equal(r.job.state,'uncertain');assert.equal(r.job.holdsSlot,true);assert.equal(r.requiresReconciliation,true);assert.equal((await c.store.leases('owner',r.job.id)).length,1);assert.equal(sends(c).length,0);assert.equal((await c.run()).job,null);const ops=c.db.db.prepare('SELECT action FROM dispatch_operations WHERE job_id=?').all(r.job.id);assert(!ops.some(x=>x.action==='checkpoint'));});

test('retained opaque reservation releases only after original-thread terminal read and verified safe checkpoint',async t=>{const c=await fixture(t,{status:'inProgress'});await c.enqueue();const waiting=await c.enqueue();const r=await c.run();assert.equal(r.job.state,'uncertain');assert.equal((await c.run()).job,null);const source={requestId:r.job.requestId,operationId:r.job.dispatchKey,threadId,environment};let observed=await c.adapter.observe(source);assert.equal(observed.active,true);const checkpoint={jobId:r.job.id,eventId:c.id(),expectedVersion:r.job.version,dispatchKey:r.job.dispatchKey,threadId,environment,action:'checkpoint',noActiveWriter:false,reconciliation:'confirmed_no_active_writer',nextState:'blocked',summary:'Synthetic safety reconciliation'};await assert.rejects(c.service.update('owner',checkpoint),{code:'checkpoint_required'});assert.equal((await c.store.leases('owner',r.job.id)).length,1);c.state.status='completed';c.state.noActiveWriter=true;observed=await c.adapter.observe(source);assert.equal(observed.terminal,true);assert.equal(observed.active,false);assert.equal(observed.businessCompleted,false);const safe=await c.service.update('owner',{...checkpoint,eventId:c.id(),turnId:observed.turnId,executionEvidence:{kind:'tool_result',observedAt:'2026-10-08T05:00:00Z',source:'Synthetic actual original-thread read',reference:'synthetic-read-terminal-item',step:'Pre-send original writer ended',active:false,terminal:true},reconciliationEvidence:'Synthetic read confirmed the original writer ended before any begin intent existed',noActiveWriter:observed.terminal===true&&observed.active===false,summary:'Original-thread read verified a terminal turn and no active writer; hold safely blocked'});assert.equal(safe.job.holdsSlot,false);assert.equal(safe.job.state,'blocked');assert.equal((await c.store.leases('owner',r.job.id)).length,0);assert.equal((await c.service.claim('owner',{eventId:c.id()})).job.id,waiting.job.id);assert.equal(sends(c).length,0);});
