import test from 'node:test';import assert from 'node:assert/strict';import {aggregateProjects,projectLayout,ageExecutionBoard,effectiveExecutionState,registeredProjectTotals,executionExpirySignature} from '../public/project-overview.js';
const now=Date.parse('2026-10-07T10:00:00Z');const agent={id:'a',name:'研究',kind:'researcher',projectNames:['A','B'],taskIds:['t1','t2'],activity:{state:'running',observedAt:'2026-10-07T09:59:00Z'}};const input=()=>({projects:['A','B','C'],agents:[structuredClone(agent)],tasks:[{id:'t1',title:'一',project:'A',state:'running',observedAt:'2026-10-07T09:59:00Z'},{id:'t2',title:'二',project:'B',state:'completed',observedAt:'2026-10-06T09:59:00Z',evidence:[{url:'https://example.com/result'}],verification:{businessAcceptance:{state:'pending'}}}]});
test('shared Agent appears per project but overall counted once',()=>{const m=aggregateProjects(input(),{now});assert.equal(m.metrics.uniqueAgents,1);assert.equal(m.projects[0].agents.length,1);assert.equal(m.projects[1].agents.length,1);assert.equal(m.metrics.confirmedRunning,1);});
test('unknown or stale activity never becomes zero running',()=>{for(const activity of [{state:'unknown'},{state:'running',observedAt:'2026-10-06T00:00:00Z'}]){const b=input();b.agents[0].activity=activity;const m=aggregateProjects(b,{now});assert.equal(m.metrics.confirmedRunning,null);assert.equal(m.metrics.unverifiedAgents,1);}});
test('fresh verified non-running can legitimately count zero alongside unknown',()=>{const b=input();b.agents[0].activity.state='paused';b.agents.push({...agent,id:'b',activity:{state:'unknown'}});const m=aggregateProjects(b,{now});assert.equal(m.metrics.confirmedRunning,0);assert.equal(m.metrics.unverifiedAgents,1);});
test('no task dependencies inferred from order or projects',()=>{const m=aggregateProjects(input(),{now});for(const p of m.projects){assert.deepEqual(p.dependencies,[]);assert.equal(p.dependencyStatus,'任务依赖未记录');assert(p.edges.every(e=>e.kind==='assignment'));}});
test('assignment edges exist only when explicit id links exist',()=>{const b=input();b.agents[0].taskIds=[];let m=aggregateProjects(b,{now});assert.equal(m.projects[0].edges.length,0);b.tasks[0].assignedAgentIds=['a'];m=aggregateProjects(b,{now});assert.deepEqual(m.projects[0].edges,[{from:'t1',to:'a',kind:'assignment'}]);});
test('task link establishes project membership even without declared project',()=>{const b=input();b.agents[0].projectNames=[];assert.equal(aggregateProjects(b,{now}).projects[1].agents.length,1);});
test('completion record does not imply business acceptance',()=>{const p=aggregateProjects(input(),{now}).projects[1];assert.equal(p.recordedCompleted,1);assert.equal(p.latestDeliveries[0].businessAcceptance,'pending');});
test('latest deliveries require evidence and valid observation time',()=>{const b=input();b.tasks[1].evidence=[];assert.equal(aggregateProjects(b,{now}).projects[1].latestDeliveries.length,0);b.tasks[1].evidence=[{url:'https://example.com'}];b.tasks[1].observedAt='invalid';assert.equal(aggregateProjects(b,{now}).projects[1].latestDeliveries.length,0);});
test('imported subset remains explicit under filtering and empty projects remain visible',()=>{const m=aggregateProjects(input(),{now,project:'A'});assert.deepEqual(m.scope,{projectCount:3,taskCount:2,agentCount:1});assert.equal(m.metrics.projects,1);assert.equal(aggregateProjects(input(),{now}).projects[2].tasks.length,0);});
test('private labels excluded and project lookup respects query/state',()=>{const b=input();b.projects.push('/user_notes/private');assert(!aggregateProjects(b,{now}).projects.some(p=>p.name.includes('user_notes')));assert.equal(aggregateProjects(b,{now,query:'二',taskState:'completed'}).projects[0].name,'B');});
test('single-project canvas shrinks to its real project width',()=>{assert.equal(projectLayout(aggregateProjects(input(),{now,project:'A'}).projects).width,780);});
test('status filter removes nonmatching tasks and their assignment edges',()=>{const b=input();b.tasks.push({id:'t3',title:'未完成',project:'B',state:'running',assignedAgentIds:['a']});const m=aggregateProjects(b,{now,taskState:'completed'});assert.equal(m.metrics.tasks,1);assert.deepEqual(m.projects[0].tasks.map(t=>t.id),['t2']);assert.deepEqual(m.projects[0].edges.map(e=>e.from),['t2']);});
test('query filters tasks inside a matching project rather than exposing siblings',()=>{const b=input();b.tasks.push({id:'t3',title:'第三件',project:'A',state:'running'});const m=aggregateProjects(b,{now,query:'第三'});assert.equal(m.metrics.tasks,1);assert.equal(m.projects[0].tasks[0].id,'t3');});
test('stale running description explicitly refers to last recorded execution',()=>{const b=input();b.agents[0].activity.observedAt='2026-10-01T00:00:00Z';assert.equal(aggregateProjects(b,{now}).projects[0].agents[0].status,'上次记录执行');});
test('older valid completion remains discoverable after a narrow search',()=>{const b=input();for(let i=0;i<5;i++)b.tasks.push({id:'d'+i,project:'B',title:'新结果'+i,state:'completed',observedAt:'2026-10-07T00:00:00Z',evidence:[{url:'https://example.com'}]});assert.equal(aggregateProjects(b,{now,query:'二'}).projects[0].latestDeliveries[0].id,'t2');});
test('project order uses actual valid task observations without refreshing their timestamps',()=>{const b=input();b.tasks[1].observedAt='2026-10-07T10:00:00Z';const m=aggregateProjects(b,{now});assert.equal(m.projects[0].name,'B');assert.equal(m.projects[0].tasks[0].observedAt,b.tasks[1].observedAt);b.tasks[1].observedAt='2030-01-01T00:00:00Z';assert.equal(aggregateProjects(b,{now}).projects[0].name,'A');});
test('narrow project layout keeps project zones within the available canvas width',()=>{const m=aggregateProjects(input(),{now}),layout=projectLayout(m.projects,{compact:true,availableWidth:357});assert.equal(layout.width,333);assert(layout.zones.every(z=>z.compact&&z.x>=0&&z.x+z.width<=layout.width));assert(layout.zones[1].y>=layout.zones[0].y+layout.zones[0].height);assert.equal(layout.zones.length,m.projects.length);});
test('unassigned coordinator stays reachable without inventing a project or edge',()=>{const b=input();b.agents.push({id:'root',name:'总协调',kind:'coordinator',activity:{state:'running',observedAt:'2026-10-01T00:00:00Z'}});const m=aggregateProjects(b,{now});assert.equal(m.unassignedAgents.length,1);assert.equal(m.unassignedAgents[0].id,'root');assert.equal(m.unassignedAgents[0].status,'上次记录执行');assert.equal(m.unassignedAgents[0].observedAt,'2026-10-01T00:00:00Z');assert.equal(m.scope.projectCount,3);assert.equal(m.metrics.uniqueAgents,1);assert(m.projects.every(p=>!p.edges.some(e=>e.to==='root')));});
test('unassigned search never reclassifies filtered-out project Agents as unassigned',()=>{const b=input();b.agents.push({id:'root',name:'总协调',kind:'coordinator'});const m=aggregateProjects(b,{now,project:'C',query:'总协调'});assert.equal(m.projects.length,0);assert.deepEqual(m.unassignedAgents.map(a=>a.id),['root']);assert.equal(m.metrics.projects,0);});

function evidenceBoard(){
 const observed='2026-10-07T09:59:00Z',expires='2026-10-07T10:04:00Z';
 const proof={effectiveState:'running',phase:'running',evidenceType:'tool_result',lastExecutionObservedAt:observed,evidenceExpiresAt:expires,currentStep:'Tests produced a result',lastEffectiveAction:'Tests produced a result'};
 return {projects:['A'],importedAt:'2026-10-01T00:00:00Z',generatedAt:'2026-10-07T10:00:00Z',tasks:[{id:'dispatch:a',project:'A',title:'Observed task',state:'running',taskNumber:7,observedAt:observed}],agents:[{id:'worker',name:'Worker',taskIds:['dispatch:a'],projectNames:['A'],activity:{state:'running',observedAt:observed}}],queueUpdates:{records:[{id:'dispatch:a',taskNumber:7,observedAt:observed,...proof}]},projectTotals:[{projectId:'p',projectName:'A',registered:9,completed:4,removed:1,activeRegistered:8,current:[{taskNumber:7,jobId:'a',...proof},{taskNumber:9,jobId:'b',...proof,evidenceExpiresAt:'2026-10-07T10:05:00Z'}],unverifiedRunning:[8],scopeChanges:[{type:'registered',taskNumber:9,recordedAt:observed},{type:'removed',taskNumber:3,recordedAt:observed}],coverage:{scope:'managed_queue',totalsComplete:true,includesCanceled:true,scopeChangesTotal:10,scopeChangesShown:2,scopeChangesOmitted:8}}]};
}
test('managed activity requires effective state and concrete unexpired evidence, never raw lifecycle or page time',()=>{
 const record=evidenceBoard().queueUpdates.records[0];
 assert.equal(effectiveExecutionState(record,now),'running');
 for(const changed of [{effectiveState:'unknown'},{evidenceExpiresAt:null},{evidenceType:'started'},{lastExecutionObservedAt:'2026-10-08T00:00:00Z'}])assert.equal(effectiveExecutionState({...record,...changed},now),'unknown');
 assert.equal(effectiveExecutionState({state:'running',phase:'running',observedAt:new Date(now).toISOString()},now),'unknown');
 assert.equal(effectiveExecutionState(record,Date.parse(record.evidenceExpiresAt)),'unknown');
});
test('cached board expiry ages tasks, agents and parallel current numbers without mutating source clocks or task numbers',()=>{
 const board=evidenceBoard(),before=structuredClone(board),fresh=aggregateProjects(board,{now}),later=Date.parse('2026-10-07T10:04:00Z'),aged=ageExecutionBoard(board,later),model=aggregateProjects(board,{now:later});
 assert.equal(fresh.projects[0].tasks[0].state,'running');assert.equal(fresh.metrics.confirmedRunning,1);
 assert.equal(aged.tasks[0].state,'unknown');assert.equal(aged.agents[0].activity.state,'unknown');assert.equal(model.metrics.confirmedRunning,null);
 assert.equal(model.projects[0].tasks[0].taskNumber,7);assert.equal(model.projects[0].tasks[0].currentStep,'');assert.equal(model.projects[0].tasks[0].lastEffectiveAction,'Tests produced a result');
 assert.deepEqual(aged.projectTotals[0].current.map(t=>t.taskNumber),[9]);assert.deepEqual(aged.projectTotals[0].unverifiedRunning,[8,7]);
 assert.equal(aged.tasks[0].observedAt,before.tasks[0].observedAt);assert.equal(aged.agents[0].activity.observedAt,before.agents[0].activity.observedAt);
 assert.equal(aged.importedAt,before.importedAt);assert.equal(aged.generatedAt,before.generatedAt);assert.deepEqual(board,before);
 assert.notEqual(executionExpirySignature(board,now),executionExpirySignature(board,later));
});
test('registered accounting retains global project scope under task filters and discloses omitted change history',()=>{
 const board=evidenceBoard(),model=aggregateProjects(board,{now,query:'Observed'}),totals=model.projects[0].registeredTotals;
 assert.equal(model.metrics.tasks,1);assert.equal(totals.registered,9);assert.equal(totals.completed,4);assert.equal(totals.removed,1);assert.equal(totals.activeRegistered,8);
 assert.deepEqual(totals.current.map(t=>t.taskNumber),[7,9]);assert.equal(totals.coverage.scopeChangesOmitted,8);assert.equal(totals.scopeChanges.filter(c=>c.type==='registered').length,1);
 board.tasks=[];board.agents=[];board.projects=[];assert.equal(aggregateProjects(board,{now}).projects[0].registeredTotals.registered,9);
});
test('no project accounting or activity is invented when coverage or typed evidence is missing',()=>{
 assert.deepEqual(registeredProjectTotals([{projectName:'A',registered:99}],now),[]);
 const board=evidenceBoard();delete board.queueUpdates.records[0].effectiveState;board.queueUpdates.records[0].state='running';board.queueUpdates.records[0].observedAt=new Date(now).toISOString();
 const model=aggregateProjects(board,{now});assert.equal(model.projects[0].tasks[0].state,'unknown');assert.equal(model.projects[0].agents[0].state,'unknown');
});
