import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorker} from '../worker.mjs';
import {readEnvironmentSnapshot} from '../src/adapters/snapshot.mjs';
import {readEnvironmentProjectRegistry,withIndependentProjectRegistry,gateIntakeByProjectRegistry} from '../src/adapters/project-registry.mjs';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
const sample=JSON.parse(await readFile(new URL('../fixtures/synthetic.json',import.meta.url),'utf8'));
const projectName=sample.tasks[0].project;
const registry=[{id:'stable-project',name:projectName}];
function scenario(t){const fixture=sqliteIntakeFixture();t.after(()=>fixture.close());const snapshot=structuredClone(sample);const env={DB:fixture.binding,DOT_BOARD_SNAPSHOT:JSON.stringify(snapshot),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify(registry),DOT_BOARD_INTAKE_MCP_ENABLED:'true',DOT_BOARD_INTAKE_CONNECTION_VERIFIED:'true',DOT_BOARD_INTAKE_ENABLED:'true',DOT_BOARD_INTAKE_READER_VERIFIED:'true',DOT_BOARD_INTAKE_WRITER_VERIFIED:'true'};const worker=createWorker({});async function call(path,{method='GET',body}={}){const response=await worker.fetch(new Request('https://example.com'+path,{method,headers:{'oai-authenticated-user-id':'synthetic-owner',...(method==='POST'?{origin:'https://example.com','content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:response.status,body:await response.json()};}async function submit(){const board=(await call('/api/board')).body;return call('/api/projects/stable-project/requests',{method:'POST',body:{clientSubmissionId:crypto.randomUUID(),body:'Synthetic lifecycle request',contextTaskId:null,viewedSnapshotRevision:board.snapshotRevision,viewedSnapshotImportedAt:board.importedAt,contextSummary:''}});}return {env,snapshot,call,submit,fixture};}
test('registered empty project can receive its first request without fabricated tasks or activity',async t=>{
 const c=scenario(t);c.snapshot.tasks=[];c.snapshot.agents=[];c.env.DOT_BOARD_SNAPSHOT=JSON.stringify(c.snapshot);
 c.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify([{...registry[0],acceptNewRequests:true}]);
 const board=(await c.call('/api/board')).body;
 assert.equal(board.projectSummaries.length,1);assert.equal(board.projectSummaries[0].id,'stable-project');
 assert.deepEqual(board.projectSummaries[0].taskIds,[]);assert.deepEqual(board.projectSummaries[0].agentIds,[]);assert.equal(board.projectSummaries[0].lastObservedAt,null);
 assert.equal(board.tasks.length,0);assert.equal(board.agents.length,0);assert.equal(board.importedAt,c.snapshot.importedAt);
 const projects=await c.call('/mcp',{method:'POST',body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'list_request_projects',arguments:{}}}});
 assert.match(JSON.stringify(projects.body),/stable-project/);const saved=await c.submit();assert.equal(saved.status,201);
 assert.equal((await c.call('/api/board')).body.tasks.length,0);
});
test('independent registry decorates twelve synthetic snapshot chunks without mutating any source value',()=>{const text=JSON.stringify(sample);const env={DOT_BOARD_SNAPSHOT_PARTS:'12',DOT_BOARD_PROJECT_REGISTRY:JSON.stringify(registry)};for(let i=0;i<12;i++)env['DOT_BOARD_SNAPSHOT_'+i]=text.slice(Math.floor(i*text.length/12),Math.floor((i+1)*text.length/12));const before=JSON.stringify(env),parsed=readEnvironmentSnapshot(env),decorated=withIndependentProjectRegistry(parsed,readEnvironmentProjectRegistry(env));assert.equal(JSON.stringify(env),before);assert.equal(parsed.projectRegistry,undefined);assert.deepEqual(decorated.tasks,parsed.tasks);assert.equal(decorated.importedAt,parsed.importedAt);assert.equal(decorated.projectRegistry[0].id,'stable-project');});
test('task export replacement cannot overwrite independent stable project identities',async t=>{const c=scenario(t);const first=(await c.call('/api/board')).body;c.snapshot.importedAt='2026-01-02T12:00:00Z';c.snapshot.projectRegistry=[{id:'untrusted-export-id',name:projectName}];c.snapshot.tasks[0].title='Updated synthetic title';c.env.DOT_BOARD_SNAPSHOT=JSON.stringify(c.snapshot);const second=(await c.call('/api/board')).body;assert(second.tasks.every(x=>x.projectId==='stable-project'));assert.equal(second.tasks.length,first.tasks.length);assert(second.tasks.some(x=>x.title==='Updated synthetic title'));assert.notEqual(first.snapshotRevision,second.snapshotRevision);assert.equal(second.importedAt,c.snapshot.importedAt);assert(!JSON.stringify(second).includes('untrusted-export-id'));});
test('invalid or absent registry disables intake without hiding the original Agent/task board',async t=>{const c=scenario(t);for(const value of [undefined,'{','{}',JSON.stringify([{id:'duplicate',name:projectName},{id:'duplicate',name:'Other'}]),'x'.repeat(65537)]){if(value===undefined)delete c.env.DOT_BOARD_PROJECT_REGISTRY;else c.env.DOT_BOARD_PROJECT_REGISTRY=value;const board=await c.call('/api/board'),caps=await c.call('/api/intake/capabilities');assert.equal(board.status,200);assert.equal(board.body.tasks.length,sample.tasks.length);assert.equal(board.body.importedAt,sample.importedAt);assert(board.body.tasks.every(x=>x.projectId===null));assert.equal(caps.body.canSubmit,false);assert.equal(caps.body.enabled,false);assert.equal(caps.body.registryStatus,value===undefined?'absent':'invalid');}});
test('renaming a project keeps the ID, existing receipt and old-label task associations',async t=>{const c=scenario(t),created=await c.submit();assert.equal(created.status,201);c.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify([{id:'stable-project',name:'Renamed synthetic project',aliases:[projectName]}]);c.snapshot.tasks[0].project='Renamed synthetic project';c.env.DOT_BOARD_SNAPSHOT=JSON.stringify(c.snapshot);const board=(await c.call('/api/board')).body;assert(board.tasks.every(x=>x.projectId==='stable-project'));const list=(await c.call('/api/projects/stable-project/requests')).body;assert.equal(list.requests[0].id,created.body.request.id);assert.equal(board.tasks.find(x=>x.id==='sample-paused').state,'paused');});
test('registry removal blocks new reception but preserves receipts; restoring the same ID restores history',async t=>{const c=scenario(t),saved=await c.submit();delete c.env.DOT_BOARD_PROJECT_REGISTRY;assert.equal((await c.submit()).status,503);assert.equal((await c.call('/api/requests/'+saved.body.request.id)).body.request.id,saved.body.request.id);assert.equal(c.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,1);c.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify(registry);assert.equal((await c.call('/api/projects/stable-project/requests')).body.requests[0].id,saved.body.request.id);});
test('new unregistered project remains visible and cannot borrow another project intake ID',async t=>{const c=scenario(t);c.snapshot.tasks.push({...c.snapshot.tasks[0],id:'new-project-task',project:'New synthetic project'});c.env.DOT_BOARD_SNAPSHOT=JSON.stringify(c.snapshot);const board=(await c.call('/api/board')).body;assert.equal(board.tasks.length,sample.tasks.length+1);assert.equal(board.tasks.find(x=>x.id==='new-project-task').projectId,null);assert.equal(board.tasks.find(x=>x.id==='sample-paused').projectId,'stable-project');});
test('registry validation and gating never create a request, event, credential or fallback identity',async t=>{const c=scenario(t);for(const value of ['[]',JSON.stringify([{id:'stable-project',name:projectName}])]){const state=readEnvironmentProjectRegistry({DOT_BOARD_PROJECT_REGISTRY:value});const caps=gateIntakeByProjectRegistry({canSubmit:true,enabled:true},state);assert.equal(caps.canSubmit,state.records.length>0);assert.equal(c.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,0);assert.equal(c.fixture.db.prepare('SELECT COUNT(*) AS n FROM intake_events').get().n,0);}assert.equal(withIndependentProjectRegistry(null,readEnvironmentProjectRegistry({})),null);});
test('private baseline label and stricter privacy filters remain in the integrated source',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),ui=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),domain=await readFile(new URL('../src/domain/snapshot.mjs',import.meta.url),'utf8');assert(html.includes('私密空间'));assert(ui.includes('__external_'));assert(ui.includes('dream_notes'));assert(domain.includes('dream_notes'));assert.match(html,/<p id="relationship-note">只显示已记录的任务与负责人\s*关系<\/p>/);assert(ui.includes("detailSection('协作关系'"));assert(ui.includes('项目归属用于分类，不代表 Agent 的上下级关系'));assert(ui.includes('本轮完成'));});
test('private registry labels and aliases are rejected before board JSON or MCP projection',async t=>{
  const c=scenario(t);const markers=['/user_notes/synthetic-project','/agent_notes/synthetic-project','dream_notes synthetic','/workspace/synthetic-project','system prompt synthetic','__external_synthetic','safe\u0001label'];
  for(const marker of markers)for(const field of ['name','alias']){
    c.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify([{id:'stable-project',name:field==='name'?marker:projectName,aliases:field==='alias'?[marker]:[]}]);
    const state=readEnvironmentProjectRegistry(c.env);assert.equal(state.status,'invalid');assert.deepEqual(state.records,[]);
    const board=await c.call('/api/board'),caps=await c.call('/api/intake/capabilities'),mcp=await c.call('/mcp',{method:'POST',body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'list_request_projects',arguments:{}}}});
    assert.equal(board.status,200);assert.equal(board.body.tasks.length,sample.tasks.length);assert(!JSON.stringify(board.body).includes(marker));assert(!JSON.stringify(mcp.body).includes(marker));assert.equal(caps.body.canSubmit,false);assert.equal(caps.body.enabled,false);
  }
});
test('rejected aliases cannot be silently sanitized into another project label',()=>{
  for(const aliases of [[' safe '],['safe\u0001'],['/user_notes/synthetic']])assert.equal(readEnvironmentProjectRegistry({DOT_BOARD_PROJECT_REGISTRY:JSON.stringify([{id:'one',name:'safe',aliases}])}).status,'invalid');
  const valid=readEnvironmentProjectRegistry({DOT_BOARD_PROJECT_REGISTRY:JSON.stringify([{id:'one',name:'Current name',aliases:['Old name']}])});assert.equal(valid.status,'configured');assert.equal(valid.records[0].id,'one');
});
