import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {taskClarity,renderProjectClarity,renderRequestInbox,utcTime,createManualStatusController,clarityBoard,renderManualStatusForm} from '../public/project-clarity.js';
class Node {
 constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.dataset={};this.attributes={};this.events=new Map();this.className='';this.ownText='';this.classList={add:v=>{this.className+=' '+v;},contains:v=>this.className.split(/\s+/).includes(v)};}
 set textContent(value){this.ownText=String(value);this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}
 set innerHTML(_){throw Error('Unsafe HTML insertion');}
 append(...nodes){for(const node of nodes){node.parentElement=this;this.children.push(node);}}
 replaceChildren(...nodes){this.children=[];this.ownText='';this.append(...nodes);}
 setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}
 addEventListener(k,fn){const list=this.events.get(k)||[];list.push(fn);this.events.set(k,list);}
 fire(k){for(const fn of this.events.get(k)||[])fn({target:this});}click(){this.fire('click');}
}
function setup(){const doc={createElement:tag=>new Node(tag,doc)};return doc.createElement('section');}
const walk=n=>[n,...n.children.flatMap(walk)],nodes=(root,cls)=>walk(root).filter(n=>n.classList.contains(cls));
const now=Date.parse('2026-10-08T11:00:00Z');
const input=()=>({projects:['Alpha','Beta'],tasks:[{id:'a',title:'Verify application',project:'Alpha',state:'partial',observedAt:'2026-10-08T10:59:00Z',observation:'The service starts and returns a successful response.',blocker:'The graphical interface still needs verification.',nextAction:'Verify the existing interface.',assignedAgentIds:['owner','reviewer']}],agents:[{id:'owner',name:'Original owner',taskIds:['a'],projectNames:['Alpha'],activity:{state:'running',observedAt:'2026-10-08T10:59:00Z'}},{id:'reviewer',name:'Reviewer',taskIds:['a'],projectNames:['Alpha'],activity:{state:'unknown'}}]});
const queue=(changes={})=>({enabled:true,jobs:[{id:'check',projectId:'p-alpha',projectName:'Alpha',originalTaskContext:{taskId:'a'},threadBound:true,state:'completed',observedAt:'2026-10-08T10:59:00Z',summary:'Read-only query completed; application unchanged.',title:'Read-only verification',...changes}]});

test('assignment records neither establish a thread nor imply running',()=>{const b=input(),c=taskClarity(b.tasks[0],b,null,now);assert.equal(c.status,'部分完成');assert.equal(c.owners.length,2);assert.equal(c.threadVerified,false);const root=setup();renderProjectClarity(root,b,null,{now});assert.match(root.textContent,/Original owner/);assert.match(root.textContent,/Reviewer/);assert.doesNotMatch(root.textContent,/当前执行未核实|尚未确认/);assert.doesNotMatch(root.textContent,/原线程已绑定|正在执行/);});
test('queue context requires exact task and project and excludes historical validation',()=>{const b=input();for(const q of [queue({projectName:'Beta'}),queue({originalTaskContext:{taskId:'wrong'}}),queue({projectId:'validation'}),{...queue(),enabled:false}])assert.equal(taskClarity(b.tasks[0],b,q,now).execution,null);assert.equal(taskClarity(b.tasks[0],b,queue(),now).threadVerified,true);});
test('only typed unexpired execution evidence is running',()=>{const b=input(),proof={state:'running',effectiveState:'running',evidenceType:'tool_result',lastExecutionObservedAt:'2026-10-08T10:59:00Z',evidenceExpiresAt:'2026-10-08T11:04:00Z'};assert.equal(taskClarity(b.tasks[0],b,queue(proof),now).status,'正在执行');for(const edit of [{evidenceType:'started'},{evidenceExpiresAt:null},{lastExecutionObservedAt:'2026-10-08T11:01:00Z'}])assert.notEqual(taskClarity(b.tasks[0],b,queue({...proof,...edit}),now).status,'正在执行');assert.notEqual(taskClarity(b.tasks[0],b,queue(proof),Date.parse(proof.evidenceExpiresAt)).status,'正在执行');});
test('a finished request does not complete its project task',()=>{const b=input(),root=setup();renderProjectClarity(root,b,queue(),{now});assert.equal(nodes(root,'pc-status')[0].textContent,'部分完成');assert.match(root.textContent,/最近一次执行已返回结果/);assert.match(root.textContent,/不代表整个项目已完成/);assert.match(root.textContent,/Read-only query completed/);});
test('paused and canceled tasks never repeat an old instruction to resume',()=>{for(const state of ['paused','canceled']){const b=input();b.tasks[0].state=state;b.tasks[0].nextAction='Resume and publish now';const root=setup();renderProjectClarity(root,b,queue(),{now});assert.doesNotMatch(root.textContent,/Resume and publish now/);assert.match(root.textContent,/已暂停|已取消/);assert.match(root.textContent,/保持暂停|不再继续/);}});
test('raw recorded running without a concrete receipt stays unverified',()=>{const b=input();b.tasks[0].state='running';assert.equal(taskClarity(b.tasks[0],b,null,now).status,'近况待核实');});
test('project and task counts remain distinct under a project selection',()=>{const root=setup();renderProjectClarity(root,input(),null,{now,project:'Alpha'});assert.equal(nodes(root,'pc-project').length,1);assert.match(nodes(root,'pc-scope')[0].textContent,/当前项目 · 1 项任务/);renderProjectClarity(root,input(),null,{now});assert.match(nodes(root,'pc-scope')[0].textContent,/2 个项目 · 1 项任务/);});
test('content-type selector controls the visible objects',()=>{const root=setup();renderProjectClarity(root,input(),null,{now,contentType:'tasks'});assert.equal(nodes(root,'pc-task').length,1);assert.equal(nodes(root,'pc-owner').length,0);renderProjectClarity(root,input(),null,{now,contentType:'agents'});assert.equal(nodes(root,'pc-task').length,0);assert.equal(nodes(root,'pc-roster-person').length,2);});
test('project, task, owner and evidence controls keep actual identities',()=>{const root=setup(),actions=[];renderProjectClarity(root,input(),null,{now,onProject:id=>actions.push(['project',id]),onTask:id=>actions.push(['task',id]),onAgent:id=>actions.push(['owner',id])});nodes(root,'pc-project-head')[0].children[0].children[0].click();nodes(root,'pc-task-title')[0].click();nodes(root,'pc-owner')[0].children[1].click();nodes(root,'pc-footer')[0].children[0].click();assert.deepEqual(actions,[['project','Alpha'],['task','a'],['owner','owner'],['task','a']]);});
test('disclosures remain open after background rendering and have stable focus keys',()=>{const root=setup();renderProjectClarity(root,input(),queue(),{now});for(const cls of ['pc-receipt','pc-blocker']){const detail=nodes(root,cls)[0];assert(detail.children[0].dataset.focusKey);detail.open=true;detail.fire('toggle');}renderProjectClarity(root,input(),queue(),{now});assert.equal(nodes(root,'pc-receipt')[0].open,true);assert.equal(nodes(root,'pc-blocker')[0].open,true);});
test('empty filtered results can clear filters without inventing records',()=>{const root=setup();let cleared=false;renderProjectClarity(root,input(),null,{now,query:'does not exist',onClear:()=>{cleared=true;}});assert.equal(nodes(root,'pc-task').length,0);assert.match(root.textContent,/没有匹配/);nodes(root,'pc-link')[0].click();assert.equal(cleared,true);});
test('source observation clocks are stable, timezone explicit, and bad timestamps disclosed',()=>{assert.equal(utcTime('2026-10-08T10:59:00Z'),'10-08 10:59 UTC');assert.equal(utcTime(null),'时间未记录');const b=input(),before=structuredClone(b);b.tasks[0].observedAt='2026-10-08T13:00:00Z';assert.equal(taskClarity(b.tasks[0],b,null,now).freshness,'future');const root=setup();renderProjectClarity(root,b,null,{now});assert.match(root.textContent,/时间待核实/);assert.equal(b.tasks[0].observedAt,'2026-10-08T13:00:00Z');assert.equal(before.tasks[0].observedAt,'2026-10-08T10:59:00Z');});
test('frontend drops internal source labels instead of echoing them',()=>{const b=input();b.tasks[0].observation='/workspace/private/secret';b.tasks[0].blocker='/user_notes/private';b.agents[0].name='/root/private';const root=setup();renderProjectClarity(root,b,null,{now});assert.doesNotMatch(root.textContent,/\/workspace\/|\/user_notes\/|\/root\//);});
test('inbox displays saved/read state without claiming the work is done or acknowledging it',()=>{const root=setup(),value={unreadCount:1,pendingCount:2,requests:[{id:'r1',projectId:'alpha',projectName:'Alpha',body:'Please revise the deliverable',status:'received',createdAt:'2026-10-08T10:59:00Z'},{id:'r2',projectId:'beta',projectName:'Beta',body:'Please inspect the result',status:'read',createdAt:'2026-10-08T10:58:00Z'}]},before=structuredClone(value),opened=[];renderRequestInbox(root,value,{onOpen:receipt=>opened.push(receipt.id)});assert.match(root.textContent,/1 条待读取 · 2 条待处理/);assert.match(root.textContent,/已收到 · 待读取/);assert.match(root.textContent,/已读取 · 待处理/);assert.doesNotMatch(root.textContent,/任务已完成/);nodes(root,'inbox-open')[0].click();assert.deepEqual(opened,['r1']);assert.deepEqual(value,before);});
test('failed inbox reads preserve the last records and provide retry',()=>{const root=setup();let retried=false;renderRequestInbox(root,{requests:[],unreadCount:0,pendingCount:0},{error:'network',onRetry:()=>{retried=true;}});assert.match(root.textContent,/保留上次读取/);nodes(root,'pc-link')[0].click();assert.equal(retried,true);});
test('inbox client is read-only and refreshes after user submission',async()=>{const source=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(source,/requestJson\('\/api\/intake\/inbox'\+/);const fn=source.slice(source.indexOf('async function loadInbox'),source.indexOf('function openInboxRequest'));assert.doesNotMatch(fn,/POST|PATCH|PUT|acknowledge/);assert.match(source,/finally\{intake.submitting.delete\(key\);renderIntake\(\);void loadInbox\(\);\}/);});

test('inbox pagination and accepted state remain actionable without changing status',()=>{const root=setup();let more=0;renderRequestInbox(root,{requests:[{id:'accepted',body:'An accepted request',projectName:'Alpha',status:'accepted'}],pendingCount:70,unreadCount:2,truncated:true,nextCursor:'opaque'}, {onMore:()=>more++});assert.match(root.textContent,/已受理/);assert.match(root.textContent,/70 条待处理/);walk(root).find(n=>n.dataset.focusKey==='inbox:more-page').click();assert.equal(more,1);});

const statusResult=(taskId,version,state,extra={})=>({taskId,version,state,source:'owner_manual',updatedAt:'2026-10-08T11:00:00Z',executionControl:{state:'active',version:0},...extra});
test('manual progress is a task label, never fresh execution evidence',()=>{const b=input();b.tasks[0].manualStatus={state:'running',version:1,source:'owner_manual'};const c=taskClarity(b.tasks[0],b,null,now);assert.equal(c.status,'进行中');assert.equal(c.executionState,null);const root=setup();renderProjectClarity(root,b,null,{now});assert.match(nodes(root,'pc-status')[0].textContent,/进行中手动/);assert.doesNotMatch(root.textContent,/正在执行|有新执行回执/);});
test('external pause overrides an older manual running label and filters',()=>{const b=input();b.tasks[0].state='paused';b.tasks[0].manualStatus={state:'running',version:2,source:'owner_manual'};assert.equal(taskClarity(b.tasks[0],b,null,now).status,'已暂停');assert.equal(clarityBoard(b).tasks[0].state,'paused');});
test('manual completion participates in filters without replacing observations or acceptance',()=>{const b=input(),observed=b.tasks[0].observedAt;b.tasks[0].manualStatus={state:'completed',version:1,source:'owner_manual'};const root=setup();renderProjectClarity(root,b,null,{now,taskState:'completed'});assert.equal(nodes(root,'pc-task').length,1);assert.match(nodes(root,'pc-status')[0].textContent,/已完成手动/);assert.equal(b.tasks[0].state,'partial');assert.equal(b.tasks[0].observedAt,observed);});
test('broken legacy relation placeholders are omitted without mutating source records',()=>{const b=input();b.tasks[0].assignedAgentIds=[];b.agents=[];b.tasks[0].observation='本轮未找到可验证的原任务映射或最新执行证据。';b.tasks[0].blocker=b.tasks[0].observation;b.tasks[0].nextAction='核验原任务后再行动，不启动替代任务';const before=structuredClone(b),root=setup();renderProjectClarity(root,b,null,{now});assert.equal(nodes(root,'pc-owner').length,0);assert.equal(nodes(root,'pc-blocker').length,0);assert.doesNotMatch(root.textContent,/未找到可验证|无法关联|尚未确认|当前执行未核实/);assert.deepEqual(b,before);});
test('status reads do not turn a missing manual record into queued',async()=>{const task=input().tasks[0],calls=[];const controller=createManualStatusController({requestJson:async(url,options)=>{calls.push([url,options]);return statusResult(task.id,0,null);}});await controller.open(task);assert.equal(controller.get(task.id).draft,'');assert.equal(controller.get(task.id).data.state,null);assert.equal(calls.length,1);assert.equal(calls[0][1],undefined);});
test('manual save uses the exact current version, status, identity and optional reason',async()=>{const task=input().tasks[0],posts=[],saved=[];const controller=createManualStatusController({uuid:()=> 'event-one',onSaved:(id,result)=>saved.push([id,result]),requestJson:async(url,options)=>{if(!options)return statusResult(task.id,0,null);posts.push(JSON.parse(options.body));return statusResult(task.id,1,'completed');}});await controller.open(task);controller.choose(task.id,'completed');controller.reason(task.id,'Owner update');await controller.save(task);assert.deepEqual(posts,[{expectedVersion:0,eventId:'event-one',state:'completed',reason:'Owner update'}]);assert.equal(controller.get(task.id).message,'已保存');assert.equal(saved[0][0],task.id);assert.equal(task.state,'partial');});
test('uncertain status saves retry byte-identical payload and block editing until resolved',async()=>{const task=input().tasks[0],payloads=[];let attempts=0;const controller=createManualStatusController({uuid:()=> 'same-event',requestJson:async(url,options)=>{if(!options)return statusResult(task.id,0,null);payloads.push(options.body);if(++attempts===1)throw Error('network');return {...statusResult(task.id,1,'completed'),duplicate:true};}});await controller.open(task);controller.choose(task.id,'completed');await controller.save(task);controller.choose(task.id,'running');assert.equal(controller.get(task.id).draft,'completed');await controller.save(task);assert.equal(payloads[0],payloads[1]);assert.equal(controller.get(task.id).submission,null);});
test('rapid repeated status clicks never create parallel writes',async()=>{const task=input().tasks[0];let resolve,posts=0;const controller=createManualStatusController({uuid:()=> 'event',requestJson:async(url,options)=>{if(!options)return statusResult(task.id,0,null);posts++;return new Promise(r=>resolve=r);}});await controller.open(task);controller.choose(task.id,'completed');const saving=controller.save(task);await controller.save(task);assert.equal(posts,1);resolve(statusResult(task.id,1,'completed'));await saving;});
test('version conflict requires deliberate reread and never automatically overwrites',async()=>{const task=input().tasks[0];let reads=0,posts=0;const controller=createManualStatusController({uuid:()=> 'event',requestJson:async(url,options)=>{if(!options)return statusResult(task.id,reads++,reads===1?null:'completed');posts++;const e=Error('version_conflict');e.status=409;throw e;}});await controller.open(task);controller.choose(task.id,'running');await controller.save(task);assert.equal(posts,1);assert.equal(controller.get(task.id).loaded,false);await controller.save(task);assert.equal(posts,1);await controller.open(task,true);assert.equal(controller.get(task.id).draft,'completed');assert.equal(posts,1);});
test('locked execution control only allows an equivalent stopped status in the editor',async()=>{const task=input().tasks[0];task.state='paused';const controller=createManualStatusController({requestJson:async()=>statusResult(task.id,2,'running',{executionControl:{state:'paused',version:3}})});await controller.open(task);assert.equal(controller.get(task.id).draft,'paused');controller.choose(task.id,'running');assert.equal(controller.get(task.id).draft,'paused');const root=setup();renderManualStatusForm(root,task,controller);const options=walk(root).filter(n=>n.tagName==='OPTION'&&n.value);assert(options.filter(n=>!['paused','canceled'].includes(n.value)).every(n=>n.disabled));assert.equal(options.find(n=>n.value==='canceled').disabled,false);assert.match(root.textContent,/恢复请在对话中确认/);});
test('a presentation callback error cannot relabel a verified saved status as an uncertain write',async()=>{const task=input().tasks[0];const controller=createManualStatusController({uuid:()=> 'event',onSaved:()=>{throw Error('render failed');},requestJson:async(url,options)=>options?statusResult(task.id,1,'completed'):statusResult(task.id,0,null)});await controller.open(task);controller.choose(task.id,'completed');await controller.save(task);assert.equal(controller.get(task.id).submission,null);assert.match(controller.get(task.id).message,/已保存/);});

test('idempotent replay adopts a later server status instead of endlessly replaying an older choice',async()=>{const task=input().tasks[0];const controller=createManualStatusController({uuid:()=> 'event',requestJson:async(url,options)=>options?{...statusResult(task.id,3,'blocked'),duplicate:true}:statusResult(task.id,1,'running')});await controller.open(task);controller.choose(task.id,'completed');await controller.save(task);assert.equal(controller.get(task.id).submission,null);assert.equal(controller.get(task.id).data.state,'blocked');assert.match(controller.get(task.id).message,/当前状态已更新为受阻/);});

test('manual pause uses pause wording even before the source control projection refreshes',()=>{const b=input();b.tasks[0].manualStatus={state:'paused',version:1,source:'owner_manual'};assert.equal(taskClarity(b.tasks[0],b,null,now).next,'保持暂停，等待你的新指令');assert.equal(b.tasks[0].state,'partial');});
test('manual save hover retains a dark background and next-step labels stay unbroken',async()=>{const css=await readFile(new URL('../public/project-clarity.css',import.meta.url),'utf8');assert.match(css,/\.pc-save-status:hover\{background:#3d5745;color:#fff\}/);assert.match(css,/\.pc-next h3\{white-space:nowrap\}/);});

test('quick status reads current version then saves once without a second save click',async()=>{
 const task=input().tasks[0],calls=[],saved=[];
 const controller=createManualStatusController({uuid:()=> 'quick-event',onSaved:(id,result)=>saved.push([id,result.state]),requestJson:async(url,options)=>{calls.push([url,options]);return options?statusResult(task.id,5,'running'):statusResult(task.id,4,'blocked',{reason:'Keep the owner note'});}});
 await controller.quickSave(task,'running');assert.equal(calls.length,2);assert.equal(calls[0][1],undefined);
 assert.deepEqual(JSON.parse(calls[1][1].body),{expectedVersion:4,eventId:'quick-event',state:'running',reason:'Keep the owner note'});
 assert.deepEqual(saved,[[task.id,'running']]);assert.equal(task.state,'partial');
 assert(calls.every(([url])=>url==='/api/tasks/a/status'));
});
test('quick status loading rejects a second in-flight choice and never writes before a successful read',async()=>{
 const task=input().tasks[0];let resolveRead,posts=0;
 const controller=createManualStatusController({uuid:()=> 'quick-event',requestJson:async(url,options)=>{if(options){posts++;return statusResult(task.id,1,'completed');}return new Promise(resolve=>resolveRead=resolve);}});
 const first=controller.quickSave(task,'completed');await controller.quickSave(task,'running');assert.equal(posts,0);resolveRead(statusResult(task.id,0,null));await first;assert.equal(posts,1);assert.equal(controller.get(task.id).data.state,'completed');
 const failed=createManualStatusController({requestJson:async()=>{throw Error('offline');}});await failed.quickSave(task,'completed');assert.equal(failed.get(task.id).loaded,false);assert.match(failed.get(task.id).error,/读取/);
});
test('quick status preserves locked controls and never sends a prohibited change',async()=>{
 const task=input().tasks[0];for(const locked of ['paused','canceled']){let writes=0;const controller=createManualStatusController({requestJson:async(url,options)=>{if(options)writes++;return statusResult(task.id,2,locked,{executionControl:{state:locked,version:3}});}});await controller.quickSave(task,'running');assert.equal(writes,0);assert.match(controller.get(task.id).error,/恢复执行需要在对话中确认/);}
});
test('quick status conflict and uncertain writes do not announce success or replace the confirmed badge',async()=>{
 const task=input().tasks[0],saved=[];let postBodies=[];
 const controller=createManualStatusController({uuid:()=> 'quick-same',onSaved:()=>saved.push(true),requestJson:async(url,options)=>{if(!options)return statusResult(task.id,3,'blocked');postBodies.push(options.body);throw Error('network');}});
 await controller.quickSave(task,'completed');assert.equal(saved.length,0);assert.equal(controller.get(task.id).data.state,'blocked');await controller.save(task);assert.equal(postBodies[0],postBodies[1]);
 const conflict=createManualStatusController({uuid:()=> 'quick-conflict',onSaved:()=>saved.push(true),requestJson:async(url,options)=>{if(!options)return statusResult(task.id,3,'blocked');const error=Error('manual_status_version_conflict');error.status=409;throw error;}});await conflict.quickSave(task,'completed');assert.equal(conflict.get(task.id).loaded,false);assert.match(conflict.get(task.id).error,/重新读取/);assert.equal(saved.length,0);
});
test('state badge is the direct native dropdown while note editing is absent from the card',()=>{
 const root=setup(),task=input().tasks[0],picked=[];
 const controller={get:()=>({loading:false,saving:false,data:null,error:'',message:'',submission:null}),quickSave:(task,value)=>picked.push([task.id,value])};
 renderProjectClarity(root,input(),null,{now,statusController:controller});const select=nodes(root,'pc-status-select')[0];
 assert.equal(select.tagName,'SELECT');assert.match(select.getAttribute('aria-label'),/Verify application.*选择后自动保存/);assert.equal(select.children[0].textContent,'部分完成');assert.equal(select.children.length,7);assert.equal(nodes(root,'pc-status-editor').length,0);
 select.value='completed';select.fire('change');assert.deepEqual(picked,[['a','completed']]);assert.equal(task.state,'partial');
});
test('manual source remains visible on quick badges, and other tasks stay editable while one saves',()=>{
 const b=input();b.tasks[0].manualStatus={state:'completed',version:2,source:'owner_manual'};b.tasks.push({...b.tasks[0],id:'b',title:'Other task',manualStatus:null});
 const root=setup(),controller={get:id=>({loading:false,saving:id==='a',data:null,error:'',message:'',submission:null}),quickSave(){}};
 renderProjectClarity(root,b,null,{now,statusController:controller});const selects=nodes(root,'pc-status-select');assert.match(selects[0].children[0].textContent,/手动标记/);assert.equal(selects[0].disabled,true);assert.equal(selects[1].disabled,false);
});
test('header, search and request composer shortcuts stay within the existing UI and services',async()=>{
 const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),app=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),css=await readFile(new URL('../public/board-brand.css',import.meta.url),'utf8');
 const header=html.slice(html.indexOf('<section class="page-heading"'),html.indexOf('<div id="request-anchor"'));
 assert(html.slice(html.indexOf('<header class="topbar"'),html.indexOf('<div class="app-layout"')).includes('board-team.png'));assert(header.includes('heading-actions'));assert(!html.includes('<details class="search-panel">'));assert(html.includes('id="clear-search"'));
 assert(app.includes("$('request-anchor').append(panel)"));assert(app.includes("$('request-home').append(panel)"));assert(app.includes("requestProject()?.id&&!$('request-body').disabled?$('request-body'):$('request-project')"));
 assert.match(css,/\.page-heading h1\{font-size:34px/);assert.match(css,/\.search-inline input\{[^}]*height:44px/);
});
test('quick-save rerender restores the status focus without stealing focus from another control',async()=>{
 for(const userMoved of [false,true]){
  const root=setup(),doc=root.ownerDocument;doc.body={};let resolveSave;
  const controller={get:()=>({loading:false,saving:false,data:null,error:'',message:'',submission:null}),quickSave:()=>new Promise(resolve=>resolveSave=resolve)};
  root.querySelectorAll=()=>walk(root);renderProjectClarity(root,input(),null,{now,statusController:controller});const old=nodes(root,'pc-status-select')[0];doc.activeElement=old;old.value='completed';old.fire('change');
  renderProjectClarity(root,input(),null,{now,statusController:controller});const replacement=nodes(root,'pc-status-select')[0];replacement.focus=()=>doc.activeElement=replacement;const other={dataset:{focusKey:'other'}};doc.activeElement=userMoved?other:doc.body;resolveSave();await new Promise(resolve=>setImmediate(resolve));assert.equal(doc.activeElement,userMoved?other:replacement);
 }
});

test('manual completed renders old blocker and next step only under collapsed history',()=>{
 const b=input(),task=b.tasks[0];task.state='blocked';task.manualStatus={source:'owner_manual',state:'completed',version:1,reason:'Collection is finished; do not collect again.'};const before=structuredClone(b),root=setup();renderProjectClarity(root,b,null,{now});
 assert.equal(nodes(root,'pc-blocker').length,0);assert.equal(nodes(root,'pc-history').length,1);const history=nodes(root,'pc-history')[0];assert.notEqual(history.open,true);assert.match(history.textContent,/原卡点/);assert(history.textContent.includes(task.nextAction));assert.equal(nodes(root,'pc-next')[0].textContent,'状态备注'+task.manualStatus.reason);assert.deepEqual(b,before);
});
test('inspector consumes the same current arrangement and history projection',async()=>{const source=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),inspector=source.slice(source.indexOf('function taskInspector'),source.indexOf('function taskInspector')+7000);assert.match(inspector,/clarity\.stopped\|\|clarity\.manualCompleted/);assert.match(inspector,/renderTaskHistory\(fragment,clarity\.history\)/);assert.doesNotMatch(inspector,/text\(task\.blocker\)|text\(task\.nextAction\)/);});
