import test from 'node:test';
import assert from 'node:assert/strict';
import {mappedQueueTaskContext,withoutManagedQueueTasks} from '../public/project-overview.js';
const job={id:'a',projectName:'Project A',threadBound:true};
const board=()=>({tasks:[{id:'dispatch:a',title:'Queued task',project:'Project A',assignedAgentIds:['reviewer']},{id:'legacy',title:'Other observation',project:'Project A'},{id:'dispatch:outside',title:'Not in this queue response',project:'Project A'}],agents:[{id:'worker',name:'Worker',taskIds:['dispatch:a']},{id:'reviewer',name:'Reviewer',taskIds:[]}],queueUpdates:{records:[{id:'dispatch:a'},{id:'dispatch:outside'}]}});
test('only an actual queue member plus a validated matching projection can remove a duplicate',()=>{const b=board(),copy=structuredClone(b);assert.deepEqual(withoutManagedQueueTasks(b,{enabled:true,jobs:[job]}).tasks.map(task=>task.id),['legacy','dispatch:outside']);assert.deepEqual(b,copy);});
test('unmatched observed dispatch names remain reachable',()=>{const b=board();b.queueUpdates.records=[];assert.equal(withoutManagedQueueTasks(b,{enabled:true,jobs:[job]}).tasks.length,3);assert.equal(mappedQueueTaskContext(b,job),null);});
test('thread binding or same project text alone does not supply an Agent identity',()=>{assert.equal(mappedQueueTaskContext({tasks:[],agents:[{id:'a',name:'Other',projectNames:['Project A']}]},job),null);assert.equal(mappedQueueTaskContext(board(),{...job,projectName:'Different project'}),null);});
test('mapping uses both actual task association routes without inventing roles',()=>{assert.deepEqual(mappedQueueTaskContext(board(),job),{id:'dispatch:a',agents:board().agents});});
test('disabled or unreadable queues never hide observation tasks',()=>{assert.equal(withoutManagedQueueTasks(board(),null).tasks.length,3);assert.equal(withoutManagedQueueTasks(board(),{enabled:false,jobs:[job]}).tasks.length,3);});

test('fresh queue project totals supersede an older board count without changing observations',()=>{const b=board();b.projectTotals=[{registered:7}];const totals=[{registered:8,current:[]}],out=withoutManagedQueueTasks(b,{enabled:true,jobs:[job],projectTotals:totals});assert.deepEqual(out.projectTotals,totals);assert.equal(b.projectTotals[0].registered,7);assert.equal(out.tasks[0].title,'Other observation');});

test('server-verified original context links the existing Agent without hiding its observed task',async()=>{const {originalQueueTaskContext}=await import('../public/project-overview.js');const board={tasks:[{id:'original',project:'Project',assignedAgentIds:['agent']}],agents:[{id:'agent',name:'Original owner',taskIds:['original']}],projects:['Project']};const job={id:'job',projectName:'Project',originalTaskContext:{taskId:'original'}};assert.equal(originalQueueTaskContext(board,job).agents[0].id,'agent');assert.equal(originalQueueTaskContext(board,{...job,projectName:'Other'}),null);assert.equal(originalQueueTaskContext(board,{id:'job',projectName:'Project',threadBound:true}),null);assert.equal(withoutManagedQueueTasks(board,{enabled:true,jobs:[job]}).tasks.length,1);});
