import test from 'node:test';
import assert from 'node:assert/strict';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1IntakeStore} from '../src/adapters/d1-intake.mjs';
import {createIntakeService} from '../src/application/intake-service.mjs';
import {createD1DispatchQueue} from '../src/adapters/d1-dispatch-queue.mjs';
import {createDispatchService} from '../src/application/dispatch-service.mjs';

// All IDs, sources, receipts, leases and databases here are synthetic. These
// tests never call an execution adapter, network tool, or production database.
const owner='fixture-owner',thread='fixture-original-thread';
const defaultEnvironment={type:'existing_thread',id:null};
const attemptedAt='2026-10-08T13:00:00.000Z';
const typedTerminal=observedAt=>({kind:'tool_result',observedAt,source:'Synthetic terminal tool result',step:'Synthetic result explicitly reports terminal execution and no active writer',reference:'https://example.com/synthetic-terminal',active:false,terminal:true});
const admission=(job,overrides={})=>({requestId:job.requestId,dispatchKey:job.dispatchKey,threadId:job.threadId,turnId:'current-attempt-new-turn',observedAt:'2026-10-08T13:00:30.000Z',source:'cloud_threads.read',reference:'https://example.com/synthetic-admission',...overrides});
async function setup(t,{isolationHistory=false,environment=defaultEnvironment}={}){
 const f=sqliteIntakeFixture();t.after(()=>f.close());let now='2026-10-08T12:00:00.000Z',serial=0;
 const id=()=>`reconcile-fixture-${++serial}`;
 const contexts=[{id:'original-task',projectId:'project-a'},{id:'other-task',projectId:'project-a'}];
 const requests=createIntakeService({store:createD1IntakeStore(f.binding),capabilities:{canSubmit:true,storageAvailable:true},clock:()=>now,newId:id,readBoard:async()=>({status:200,body:{snapshotRevision:'sha256:'+'a'.repeat(64),projectSummaries:[{id:'project-a',name:'Synthetic project'}],tasks:contexts}})});
 const store=createD1DispatchQueue(f.binding),service=createDispatchService({store,requests,enabled:true,capacity:6,readRegistry:async()=>[{id:'project-a',executionState:'active'}],clock:()=>now,newId:id});
 const register=(who,taskId,threadId)=>service.registerBinding(who,{taskId,projectId:'project-a',threadId,environment,verified:true,evidence:'Synthetic original binding verified for the fixture'});
 await register(owner,'original-task',thread);
 const enqueue=async(who=owner,taskId='original-task')=>{let {request}=await requests.submit('project-a',who,{clientSubmissionId:'fixture-submit-'+id(),body:'Synthetic narrowly scoped original-thread work',contextTaskId:taskId,viewedSnapshotRevision:'sha256:'+'a'.repeat(64),viewedSnapshotImportedAt:now});for(const status of ['read','accepted'])({request}=await requests.append(request.id,{eventId:id(),expectedVersion:request.version,status,summary:'Synthetic '+status},who));return (await service.enqueue(who,{eventId:id(),requestId:request.id,expectedRequestVersion:request.version,environment,resources:[{kind:'repository',id:'fixture-exclusive-repository'}]})).job;};
 const update=(job,action,extra={},who=owner)=>service.update(who,{jobId:job.id,eventId:id(),expectedVersion:job.version,dispatchKey:job.dispatchKey,threadId:job.threadId,environment,action,summary:'Synthetic '+action,...extra});
 const history=[];
 const historical=async(who,taskId,turnId)=>{await enqueue(who,taskId);let {job}=await service.claim(who,{eventId:id()});({job}=await update(job,'begin',{},who));({job}=await update(job,'bind',{turnId,verified:true},who));now='2026-10-08T12:00:01.000Z';({job}=await update(job,'complete',{turnId,noActiveWriter:true,executionEvidence:typedTerminal(now)},who));history.push({who,jobId:job.id,requestId:job.requestId});now='2026-10-08T12:00:00.000Z';return job;};
 await historical(owner,'original-task','historical-turn-1');
 if(isolationHistory){await register(owner,'other-task','fixture-other-thread');await historical(owner,'other-task','other-thread-turn');await register('fixture-other-owner','original-task',thread);await historical('fixture-other-owner','original-task','other-owner-turn');}
 const historyImage=()=>history.map(row=>({job:f.db.prepare('SELECT * FROM dispatch_jobs WHERE owner_id=? AND id=?').get(row.who,row.jobId),request:f.db.prepare('SELECT * FROM intake_requests WHERE owner_id=? AND id=?').get(row.who,row.requestId),events:f.db.prepare('SELECT * FROM intake_events WHERE request_id=? ORDER BY version').all(row.requestId),operations:f.db.prepare('SELECT * FROM dispatch_operations WHERE owner_id=? AND job_id=? ORDER BY created_at,event_id').all(row.who,row.jobId)}));
 const originalHistory=historyImage();now=attemptedAt;await enqueue();let {job}=await service.claim(owner,{eventId:id()});const currentJobId=job.id;
 const heldImage=()=>({job:f.db.prepare('SELECT * FROM dispatch_jobs WHERE owner_id=? AND id=?').get(owner,currentJobId),leases:f.db.prepare('SELECT * FROM dispatch_resource_leases WHERE owner_id=? AND job_id=? ORDER BY resource_key').all(owner,currentJobId),request:f.db.prepare('SELECT * FROM intake_requests WHERE owner_id=? AND id=?').get(owner,job.requestId),requestEvents:f.db.prepare('SELECT * FROM intake_events WHERE request_id=? ORDER BY version').all(job.requestId),operations:f.db.prepare('SELECT * FROM dispatch_operations WHERE owner_id=? AND job_id=? ORDER BY event_id').all(owner,currentJobId)});
 const state=async()=>store.get(owner,currentJobId);
 const move=async(action,extra={})=>{({job}=await update(await state(),action,extra));return job;};
 const makeDispatching=async()=>{now='2026-10-08T13:00:01.000Z';return move('begin');};
 const makeUncertain=async()=>{await makeDispatching();now='2026-10-08T13:00:10.000Z';return move('uncertain');};
 const rejectUnchanged=async(action,extra,{code}={})=>{const before=heldImage();await assert.rejects(update(await state(),action,extra),error=>{if(code)return error.code===code;return [400,409,503].includes(error?.status)&&typeof error?.code==='string';});assert.deepEqual(heldImage(),before,'Rejected reconciliation must not write job, slot, lease, request, receipt or operation');assert.deepEqual(historyImage(),originalHistory,'Original historical job and receipts must remain intact');};
 return {...f,store,service,requests,id,history,originalHistory,historyImage,heldImage,state,move,update,makeDispatching,makeUncertain,rejectUnchanged,setTime:value=>{now=value;},clock:()=>now};
}

test('known-thread dispatching checkpoint is rejected even with no-writer/absence assertions',async t=>{const c=await setup(t);await c.makeDispatching();for(const fields of [{noActiveWriter:true,nextState:'blocked'},{noActiveWriter:true,nextState:'queued',reconciliation:'confirmed_no_active_writer',reconciliationEvidence:'Synthetic idle text is not an admission fence'},{noActiveWriter:true,nextState:'blocked',reconciliation:'confirmed_no_thread_created',verifiedAbsent:true}])await c.rejectUnchanged('checkpoint',fields,{code:'uncertain_requires_admission'});});
test('known-thread uncertain checkpoint cannot release a lease using a later idle read or boolean',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:10:00.000Z');await c.rejectUnchanged('checkpoint',{noActiveWriter:true,nextState:'blocked',reconciliation:'confirmed_no_active_writer',reconciliationEvidence:'Synthetic thread looked idle after the uncertain send'},{code:'uncertain_requires_admission'});});
test('uncertain bind without typed positive admission is rejected without touching reservation/history',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');for(const admissionEvidence of [undefined,null,{},'A free-text success claim'])await c.rejectUnchanged('bind',{turnId:'current-attempt-new-turn',verified:true,...(admissionEvidence===undefined?{}:{admissionEvidence})});});
test('admission evidence must exactly bind request, dispatch key, original thread and proposed new turn',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');const job=await c.state();for(const changed of [{requestId:c.history[0].requestId},{dispatchKey:'another-dispatch-key'},{threadId:'another-original-thread'},{turnId:'different-proposed-turn'}])await c.rejectUnchanged('bind',{turnId:'current-attempt-new-turn',verified:true,admissionEvidence:admission(job,changed)});});
test('admission needs current-attempt, nonfuture, at-most-five-minute source evidence',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:10:00.000Z');const job=await c.state();for(const observedAt of ['2026-10-08T12:59:59.999Z','2026-10-08T13:04:59.999Z','2026-10-08T13:10:00.001Z','invalid-time'])await c.rejectUnchanged('bind',{turnId:'current-attempt-new-turn',verified:true,admissionEvidence:admission(job,{observedAt})});});
test('missing admission source or reference is never replaced by fabricated provenance',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');const job=await c.state();for(const changed of [{source:''},{reference:''},{source:undefined},{reference:undefined}])await c.rejectUnchanged('bind',{turnId:'current-attempt-new-turn',verified:true,admissionEvidence:admission(job,changed)});});
test('old turn binding is rejected in dispatching even when the receipt is newly read',async t=>{const c=await setup(t);await c.makeDispatching();c.setTime('2026-10-08T13:00:31.000Z');await c.rejectUnchanged('bind',{turnId:'historical-turn-1',verified:true});});
test('old turn cannot be admitted to an uncertain current attempt using fresh matching-looking evidence',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');const job=await c.state();await c.rejectUnchanged('bind',{turnId:'historical-turn-1',verified:true,admissionEvidence:admission(job,{turnId:'historical-turn-1'})});});
test('attemptContext uses only owner/current-job claims and owner/original-thread historical turns',async t=>{const c=await setup(t,{isolationHistory:true}),job=await c.state();assert.equal(typeof c.store.attemptContext,'function');const ctx=await c.store.attemptContext(owner,job);assert.equal(Date.parse(ctx.attemptStartedAt),Date.parse(attemptedAt));assert.ok(ctx.knownPriorTurnIds.includes('historical-turn-1'));assert.equal(ctx.knownPriorTurnIds.includes('other-thread-turn'),false);assert.equal(ctx.knownPriorTurnIds.includes('other-owner-turn'),false);assert.deepEqual(c.historyImage(),c.originalHistory);});
test('attemptContext takes the latest relevant persisted claim and ignores non-claim or foreign-owner operations',async t=>{const c=await setup(t),job=await c.state();const insert=(eventId,who,action,createdAt)=>c.db.prepare('INSERT INTO dispatch_operations(owner_id,event_id,job_id,payload_digest,action,created_at) VALUES (?,?,?,?,?,?)').run(who,eventId,job.id,'f'.repeat(64),action,createdAt);insert('claim-whole-second',owner,'claim','2026-10-08T13:00:00Z');insert('claim-fraction-later',owner,'claim','2026-10-08T13:00:00.500Z');insert('later-priority',owner,'priority','2026-10-08T13:20:00Z');insert('foreign-claim','fixture-other-owner','claim','2026-10-08T13:30:00Z');assert.equal(typeof c.store.attemptContext,'function');assert.equal(Date.parse((await c.store.attemptContext(owner,job)).attemptStartedAt),Date.parse('2026-10-08T13:00:00.500Z'));});
test('a missing persisted claim timestamp cannot be replaced by job updatedAt or a fresh admission timestamp',async t=>{const c=await setup(t);await c.makeUncertain();c.db.prepare("DELETE FROM dispatch_operations WHERE owner_id=? AND job_id=? AND action='claim'").run(owner,(await c.state()).id);c.setTime('2026-10-08T13:00:31.000Z');const job=await c.state();await c.rejectUnchanged('bind',{turnId:'current-attempt-new-turn',verified:true,admissionEvidence:admission(job)});});
test('fresh positive admission is durably recorded, then fresh typed terminal completion releases only the current lease',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');const proof=admission(await c.state());const bound=await c.move('bind',{turnId:proof.turnId,verified:true,admissionEvidence:proof});assert.equal(bound.state,'assigned');assert.equal(bound.holdsSlot,true);const saved=JSON.parse(bound.reconciliationEvidence);for(const [key,value] of Object.entries(proof))assert.equal(saved[key],value,key);assert.equal((await c.store.leases(owner,bound.id)).length,1);c.setTime('2026-10-08T13:00:50.000Z');const finished=await c.move('complete',{turnId:proof.turnId,noActiveWriter:true,executionEvidence:typedTerminal(c.clock())});assert.equal(finished.state,'completed');assert.equal(finished.holdsSlot,false);assert.equal((await c.store.leases(owner,bound.id)).length,0);assert.equal((await c.requests.get(finished.requestId,owner)).request.status,'completed');assert.deepEqual(c.historyImage(),c.originalHistory);});
async function assignedCurrent(c){await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');const proof=admission(await c.state());return c.move('bind',{turnId:proof.turnId,verified:true,admissionEvidence:proof});}
test('known-thread complete/fail cannot rely on result links and a noActiveWriter boolean alone',async t=>{for(const action of ['complete','fail']){const c=await setup(t);const job=await assignedCurrent(c);c.setTime('2026-10-08T13:00:50.000Z');await c.rejectUnchanged(action,{turnId:job.turnId,noActiveWriter:true,evidenceLinks:[{label:'Synthetic result link',url:'https://example.com/result'}]});}});
test('known-thread terminal evidence must be typed tool_result, inactive and terminal',async t=>{const c=await setup(t);const job=await assignedCurrent(c);c.setTime('2026-10-08T13:00:50.000Z');for(const changed of [{kind:'progress_output'},{kind:'active_process',active:true},{active:true},{active:undefined},{terminal:false},{terminal:undefined}])await c.rejectUnchanged('complete',{turnId:job.turnId,noActiveWriter:true,executionEvidence:{...typedTerminal(c.clock()),...changed}});});
test('both complete/fail reject terminal evidence older than the current attempt or older than five minutes',async t=>{for(const action of ['complete','fail']){const c=await setup(t);const job=await assignedCurrent(c);c.setTime('2026-10-08T13:10:00.000Z');for(const observedAt of ['2026-10-08T12:59:59.999Z','2026-10-08T13:04:59.999Z','2026-10-08T13:10:00.001Z'])await c.rejectUnchanged(action,{turnId:job.turnId,noActiveWriter:true,executionEvidence:typedTerminal(observedAt)});}});
test('fresh typed tool_result failure can safely close current execution without changing history',async t=>{const c=await setup(t);const job=await assignedCurrent(c);c.setTime('2026-10-08T13:00:50.000Z');const result=await c.move('fail',{turnId:job.turnId,noActiveWriter:true,executionEvidence:typedTerminal(c.clock())});assert.equal(result.state,'failed');assert.equal(result.holdsSlot,false);assert.equal((await c.store.leases(owner,job.id)).length,0);assert.deepEqual(c.historyImage(),c.originalHistory);});
test('exact five-minute terminal evidence remains within the stated inclusive freshness window',async t=>{const c=await setup(t);const job=await assignedCurrent(c);c.setTime('2026-10-08T13:06:00.000Z');const result=await c.move('complete',{turnId:job.turnId,noActiveWriter:true,executionEvidence:typedTerminal('2026-10-08T13:01:00.000Z')});assert.equal(result.state,'completed');assert.equal(result.holdsSlot,false);assert.deepEqual(c.historyImage(),c.originalHistory);});
test('wrong terminal turn or dispatch identity cannot release the admitted attempt',async t=>{const c=await setup(t);const job=await assignedCurrent(c);c.setTime('2026-10-08T13:00:50.000Z');for(const changed of [{turnId:'historical-turn-1'},{dispatchKey:'unrelated-dispatch-key'},{threadId:'unrelated-thread'}])await c.rejectUnchanged('complete',{turnId:job.turnId,noActiveWriter:true,executionEvidence:typedTerminal(c.clock()),...changed});});
test('typed terminal receipt requirement applies to every known-thread environment, not only existing_thread',async t=>{for(const environment of [{type:'computer',id:'fixture-computer'},{type:'coding_environment',id:'fixture-coding-environment'},{type:'native_cloud',id:null}]){const c=await setup(t,{environment}),job=await assignedCurrent(c);c.setTime('2026-10-08T13:00:50.000Z');await c.rejectUnchanged('complete',{turnId:job.turnId,noActiveWriter:true,evidenceLinks:[{label:'Link alone is insufficient',url:'https://example.com/result'}]});const result=await c.move('complete',{turnId:job.turnId,noActiveWriter:true,executionEvidence:typedTerminal(c.clock())});assert.equal(result.state,'completed');assert.deepEqual(c.historyImage(),c.originalHistory);}});
test('caller-provided attempt time and empty prior-turn list cannot override D1-derived context',async t=>{const c=await setup(t);await c.makeUncertain();c.setTime('2026-10-08T13:00:31.000Z');const job=await c.state();await c.rejectUnchanged('bind',{turnId:'historical-turn-1',verified:true,attemptStartedAt:'2026-10-08T01:00:00Z',knownPriorTurnIds:[],admissionEvidence:admission(job,{turnId:'historical-turn-1'})});});
