import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createSitesPrivateEntry} from '../src/application/sites-entry.mjs';import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
const source=JSON.parse(readFileSync(new URL('../fixtures/synthetic.json',import.meta.url),'utf8'));
function setup(t){const db=sqliteIntakeFixture();t.after(()=>db.close());const snapshot=structuredClone(source);snapshot.tasks[0]={...snapshot.tasks[0],state:'unknown',observedAt:null};const task=snapshot.tasks[0];const env={DB:db.binding,DOT_BOARD_INGRESS:'sites-owner-private-v1',DOT_BOARD_OWNER_ID:'synthetic-owner',DOT_BOARD_AUDIENCE:'https://example.com',DOT_BOARD_OBSERVATIONS_ENABLED:'true',DOT_BOARD_INTAKE_MCP_ENABLED:'true',DOT_BOARD_PROJECT_REGISTRY:JSON.stringify([{id:'p',name:task.project,aliases:[],executionState:'deferred'}]),DOT_BOARD_SNAPSHOT:JSON.stringify(snapshot),DOT_BOARD_OBSERVATION_BINDINGS:JSON.stringify([{taskId:task.id,threadId:'synthetic-original-thread',environment:null,readAllowed:true}])};const entry=createSitesPrivateEntry();const event={taskId:task.id,eventId:'synthetic-observation-1',expectedVersion:0,source:{threadId:'synthetic-original-thread',environment:null,turnId:'synthetic-turn',itemId:'synthetic-item',observedAt:'2026-10-07T23:00:00Z'},changes:{state:'partial',observation:'Synthetic source verified a partial deliverable.',blocker:'Synthetic remaining work',nextAction:'Read the next genuine result'}};const call=(path,{owner='synthetic-owner',body,origin='https://example.com'}={})=>entry.fetch(new Request('https://example.com'+path,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':owner,...(body?{'content-type':'application/json',...(origin?{origin}:{})}:{})},body:body?JSON.stringify(body):undefined}),env);return {db,env,entry,event,task,call};}
test('Sites D1 observation roundtrip updates the existing task without deployment, dispatch or other source-clock changes',async t=>{
 const c=setup(t),before=await(await c.call('/api/board')).json();const save=await c.call('/api/observations/events',{body:c.event});assert.equal(save.status,201);assert.equal((await save.json()).version,1);
 const after=await(await c.call('/api/board')).json(),updated=after.tasks.find(x=>x.id===c.task.id);assert.equal(updated.state,'partial');assert.equal(updated.observedAt,c.event.source.observedAt);assert.equal(after.importedAt,before.importedAt);assert.deepEqual(after.agents,before.agents);assert.deepEqual(after.tasks.filter(x=>x.id!==c.task.id),before.tasks.filter(x=>x.id!==c.task.id));assert(!JSON.stringify(after).includes('synthetic-original-thread'));
 assert.equal((await c.call('/api/observations/events',{body:c.event})).status,201);const state=await(await c.call('/api/observations/tasks/'+encodeURIComponent(c.task.id))).json();assert.equal(state.version,1);assert.equal(state.sourceBinding.environment,null);assert.equal(state.automaticMonitoring,false);
 assert.equal(c.db.db.prepare('SELECT COUNT(*) AS n FROM dispatch_jobs').get().n,0);assert.equal(c.db.db.prepare('SELECT COUNT(*) AS n FROM intake_requests').get().n,0);
 const restarted=createSitesPrivateEntry();const reload=await restarted.fetch(new Request('https://example.com/api/board',{headers:{'oai-authenticated-user-id':'synthetic-owner'}}),c.env);assert.equal((await reload.json()).tasks.find(x=>x.id===c.task.id).state,'partial');
});
test('Sites observation writes enforce original mapping, owner, origin and pause priority',async t=>{const c=setup(t);assert.equal((await c.call('/api/observations/events',{body:c.event,owner:'wrong'})).status,403);assert.equal((await c.call('/api/observations/events',{body:c.event,origin:null})).status,403);assert.equal((await c.call('/api/observations/events',{body:{...c.event,source:{...c.event.source,threadId:'wrong-thread'}}})).status,409);assert.equal((await c.call('/api/observations/events',{body:c.event})).status,201);const registry=JSON.parse(c.env.DOT_BOARD_PROJECT_REGISTRY);registry[0].executionState='paused';c.env.DOT_BOARD_PROJECT_REGISTRY=JSON.stringify(registry);assert.equal((await(await c.call('/api/board')).json()).tasks.find(x=>x.id===c.task.id).state,'paused');});
test('published observation MCP contract lists concrete tools and performs the same persistent versioned write',async t=>{const c=setup(t);const rpc=async(method,params)=>{const r=await c.call('/mcp',{body:{jsonrpc:'2.0',id:1,method,params}});return {status:r.status,body:await r.json()};};const listed=await rpc('tools/list',{});assert(listed.body.result.tools.some(x=>x.name==='record_task_observation'));assert(listed.body.result.tools.some(x=>x.name==='get_task_observation_state'));const record=await rpc('tools/call',{name:'record_task_observation',arguments:c.event});assert.equal(record.status,200);assert.equal(record.body.result.structuredContent.version,1);const state=await rpc('tools/call',{name:'get_task_observation_state',arguments:{taskId:c.task.id}});assert.equal(state.body.result.structuredContent.version,1);assert.equal(state.body.result.structuredContent.canRecord,true);});
