import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1TaskRequirementsStore} from '../src/adapters/d1-task-requirements.mjs';
import {createTaskRequirementsService} from '../src/application/task-requirements-service.mjs';
import {createSitesPrivateEntry} from '../src/application/sites-entry.mjs';
import {renderNativeTaskEvidence} from '../public/project-clarity.js';
const now='2026-10-10T01:00:00.000Z',source=JSON.parse(readFileSync(new URL('../fixtures/synthetic.json',import.meta.url),'utf8'));
const code=value=>error=>error.code===value;
function fixture(t){const db=sqliteIntakeFixture();t.after(()=>db.close());const snapshot=structuredClone(source),task=snapshot.tasks[0];task.sourceBinding={threadId:null,readAllowed:false};task.state='paused';const store=createD1TaskRequirementsStore(db.binding),service=createTaskRequirementsService({store,ownerId:'owner-a',readSnapshot:()=>snapshot,clock:()=>now});return {...db,store,service,snapshot,task};}
const req=f=>({taskId:f.task.id,eventId:'requirement-source-event',expectedVersion:0,changes:{goal:'Existing genuine goal'},sourceReferences:['synthetic-user-message']});
const evidence=(f,extra={})=>({taskId:f.task.id,eventId:'native-evidence-event',expectedVersion:1,requirementVersion:1,nativeTaskName:'maintain_original_board',summary:'Ordinary display change checked; queue dispatch remains unverified.',observedAt:now,resultReferences:[{kind:'commit',label:'Synthetic source commit',reference:'https://example.com/source/commit/sample'}],...extra});
const seed=async f=>f.service.set('owner-a',req(f));
const count=f=>f.db.prepare('SELECT COUNT(*) n FROM task_requirement_events').get().n;
test('native evidence links an immutable original requirement revision without inventing cloud identity',async t=>{const f=fixture(t),original=await seed(f),before=structuredClone(f.snapshot),result=await f.service.appendNativeEvidence('owner-a',evidence(f));assert.equal(result.version,2);assert.equal(result.grantsExecution,false);assert.equal(result.evidenceScope,'descriptive_only');assert.equal(result.goal,original.goal);assert.deepEqual(result.sourceReferences,original.sourceReferences);assert.equal(result.nativeEvidence[0].sourceType,'native_task');assert.equal(result.nativeEvidence[0].requirementVersion,1);assert.equal(result.nativeEvidence[0].requirementEventId,'requirement-source-event');assert.deepEqual(result.nativeEvidence[0].requirementSourceReferences,['synthetic-user-message']);assert.deepEqual(f.snapshot,before);for(const key of ['threadId','turnId','requestId','state','executionAllowed'])assert(!Object.hasOwn(result.nativeEvidence[0],key));assert.deepEqual((await f.service.get('owner-a',f.task.id)).nativeEvidence,result.nativeEvidence);});
test('later text edits preserve all evidence and old requirement provenance',async t=>{const f=fixture(t);await seed(f);const first=await f.service.appendNativeEvidence('owner-a',evidence(f));await f.service.set('owner-a',{...req(f),eventId:'second-requirement',expectedVersion:2,changes:{goal:'Later owner text'},sourceReferences:['later-synthetic-message']});const second=await f.service.appendNativeEvidence('owner-a',evidence(f,{eventId:'second-evidence',expectedVersion:3}));assert.equal(second.version,4);assert.equal(second.goal,'Later owner text');assert.deepEqual(second.nativeEvidence[0],first.nativeEvidence[0]);assert(second.nativeEvidence.every(note=>note.requirementEventId==='requirement-source-event'));assert(second.nativeEvidence.every(note=>note.requirementSourceReferences[0]==='synthetic-user-message'));});
test('evidence never overlays task observations, state, manual controls, binding or timestamps',async t=>{const f=fixture(t);await seed(f);const before=await f.service.overlay('owner-a',f.snapshot);await f.service.appendNativeEvidence('owner-a',evidence(f));assert.deepEqual(await f.service.overlay('owner-a',f.snapshot),before);for(const table of ['intake_requests','dispatch_jobs','dispatch_controls','dispatch_task_bindings','dispatch_resource_leases','board_observation_events','task_manual_status_events']){if(f.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table))assert.equal(f.db.prepare('SELECT COUNT(*) n FROM '+table).get().n,0);}});
test('owner, missing task, version zero and unsupported fields are rejected before writes',async t=>{const f=fixture(t);await seed(f);await assert.rejects(f.service.appendNativeEvidence('',evidence(f)),code('authentication_required'));await assert.rejects(f.service.appendNativeEvidence('other',evidence(f)),code('board_access_denied'));await assert.rejects(f.service.appendNativeEvidence('owner-a',evidence(f,{taskId:'missing-task'})),code('task_not_found'));for(const extra of [{requirementVersion:0},{requirementVersion:2},{requestId:'invented'},{threadId:'invented'},{turnId:'invented'},{state:'completed'},{grantsExecution:true},{changes:{goal:'replacement'}},{requirementEventId:'forged-source'}])await assert.rejects(f.service.appendNativeEvidence('owner-a',evidence(f,extra)));assert.equal(count(f),1);});
test('another task or owner revision cannot be used as a requirement anchor',async t=>{const f=fixture(t);await seed(f);const missing=source.tasks[1];assert(missing);await assert.rejects(f.service.appendNativeEvidence('owner-a',evidence(f,{taskId:missing.id})),code('requirements_version_conflict'));const other=createTaskRequirementsService({store:f.store,ownerId:'owner-b',readSnapshot:()=>f.snapshot,clock:()=>now});await assert.rejects(other.appendNativeEvidence('owner-b',evidence(f)),code('requirements_version_conflict'));assert.equal(count(f),1);});
test('identical replay does not append and changed replay conflicts even after later text edits',async t=>{const f=fixture(t);await seed(f);const input=evidence(f);await f.service.appendNativeEvidence('owner-a',input);await f.service.set('owner-a',{...req(f),eventId:'later',expectedVersion:2,changes:{goal:'Changed goal'}});const replay=await f.service.appendNativeEvidence('owner-a',input);assert.equal(replay.duplicate,true);assert.equal(replay.version,3);assert.equal(replay.nativeEvidence.length,1);await assert.rejects(f.service.appendNativeEvidence('owner-a',{...input,summary:'Different result'}),code('requirements_event_conflict'));assert.equal(count(f),3);});
test('competing evidence and text CAS writes commit exactly one version',async t=>{const f=fixture(t);await seed(f);const results=await Promise.allSettled([f.service.appendNativeEvidence('owner-a',evidence(f)),f.service.set('owner-a',{...req(f),eventId:'parallel-text',expectedVersion:1,changes:{goal:'Concurrent edit'}})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.find(x=>x.status==='rejected').reason.code,'requirements_version_conflict');assert.equal(count(f),2);});
test('concurrent identical evidence events have one durable winner',async t=>{const f=fixture(t);await seed(f);const results=await Promise.all(Array.from({length:6},()=>f.service.appendNativeEvidence('owner-a',evidence(f))));assert.equal(results.filter(x=>!x.duplicate).length,1);assert(results.every(x=>x.nativeEvidence.length===1));assert.equal(count(f),2);});
test('evidence rejects malformed references, secret-like text, future times and wrong source types',async t=>{const f=fixture(t);await seed(f);for(const extra of [{resultReferences:[]},{resultReferences:[{kind:'cloud_thread_receipt',label:'receipt',reference:'x'}]},{resultReferences:[{kind:'commit',label:'unsafe',reference:'/workspace/private'}]},{resultReferences:[{kind:'test',label:'test',reference:'x',verified:true}]},{resultReferences:[evidence(f).resultReferences[0],evidence(f).resultReferences[0]]},{summary:'/root/private'},{observedAt:'invalid'},{observedAt:'2026-10-11T01:00:00Z'},{sourceType:'cloud_thread'}])await assert.rejects(f.service.appendNativeEvidence('owner-a',evidence(f,extra)));assert.equal(count(f),1);});
test('full append-only ledger rejects further entries without dropping history',async t=>{const f=fixture(t);await seed(f);for(let i=1;i<=20;i++)await f.service.appendNativeEvidence('owner-a',evidence(f,{eventId:'evidence-'+i,expectedVersion:i}));await assert.rejects(f.service.appendNativeEvidence('owner-a',evidence(f,{eventId:'overflow',expectedVersion:21})),code('native_evidence_limit'));assert.equal((await f.service.get('owner-a',f.task.id)).nativeEvidence.length,20);assert.equal(count(f),21);});
function httpFixture(t,entry=createSitesPrivateEntry()){const f=fixture(t),env={DB:f.binding,DOT_BOARD_INGRESS:'sites-owner-private-v1',DOT_BOARD_OWNER_ID:'owner-a',DOT_BOARD_AUDIENCE:'https://example.com',DOT_BOARD_SNAPSHOT:JSON.stringify(f.snapshot),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify([{id:'sample',name:f.task.project,aliases:[],executionState:'paused'}]),DOT_BOARD_INTAKE_MCP_ENABLED:'true'};const call=(path,{body,owner='owner-a',origin='https://example.com'}={})=>entry.fetch(new Request('https://example.com'+path,{method:body?'POST':'GET',headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),origin,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);return {...f,call};}
test('normal HTTP append uses existing owner/origin checks and rereads in original requirements',async t=>{const f=httpFixture(t);await seed(f);const {taskId,...body}=evidence(f),path='/api/tasks/'+taskId+'/requirements/native-evidence';assert.equal((await f.call(path,{body,owner:null})).status,401);assert.equal((await f.call(path,{body,owner:'other'})).status,403);assert.equal((await f.call(path,{body,origin:'https://other.example.com'})).status,403);assert.equal((await f.call(path,{body:{...body,taskId}})).status,400);assert.equal((await f.call(path,{body})).status,200);assert.equal((await f.call(path)).status,405);const result=await(await f.call('/api/tasks/'+taskId+'/requirements')).json();assert.equal(result.nativeEvidence.length,1);assert.equal(result.grantsExecution,false);});
test('MCP exposes descriptive append separately from ordinary text changes',async t=>{const f=httpFixture(t);await seed(f);const rpc=(name,args)=>f.call('/mcp',{body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}}});const catalog=await(await f.call('/mcp',{body:{jsonrpc:'2.0',id:1,method:'tools/list'}})).json();assert(catalog.result.tools.some(tool=>tool.name==='record_task_native_evidence'));const result=await(await rpc('record_task_native_evidence',evidence(f))).json();assert.equal(result.result.structuredContent.version,2);assert.equal(result.result.structuredContent.nativeEvidence[0].sourceType,'native_task');assert.equal(count(f),2);});
test('compiled Sites entry appends and reads the same descriptive metadata',async t=>{const compiled=(await import('../dist/sites/index.js')).default,f=httpFixture(t,compiled);await seed(f);const {taskId,...body}=evidence(f);assert.equal((await f.call('/api/tasks/'+taskId+'/requirements/native-evidence',{body})).status,200);const result=await(await f.call('/api/tasks/'+taskId+'/requirements')).json();assert.equal(result.nativeEvidence.length,1);assert.equal(result.evidenceScope,'descriptive_only');const board=await(await f.call('/api/board')).json();assert(!Object.hasOwn(board.tasks.find(task=>task.id===taskId),'nativeEvidence'));});
class Node{constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.ownText='';}set textContent(value){this.ownText=String(value);this.children=[];}get textContent(){return this.ownText+this.children.map(node=>node.textContent).join('');}append(...nodes){this.children.push(...nodes);}setAttribute(){}addEventListener(){}}
test('native evidence UI renders as descriptive text and has no execution or mutation controls',()=>{const doc={createElement:tag=>new Node(tag,doc)},root=doc.createElement('div');renderNativeTaskEvidence(root,[{requirementVersion:1,nativeTaskName:'<img src=x onerror=alert(1)>',summary:'<script>synthetic</script>',observedAt:now,recordedAt:now,requirementSourceReferences:['source-message'],resultReferences:[{kind:'native_result',label:'Result',reference:'javascript:synthetic'}]}]);assert.match(root.textContent,/需求版本 1/);assert.match(root.textContent,/不赋予执行权/);assert.match(root.textContent,/不是 cloud_threads 队列回执/);assert.match(root.textContent,/不代表项目整体验收完成/);const all=node=>[node,...node.children.flatMap(all)];assert(!all(root).some(node=>['BUTTON','INPUT','SELECT','A','IMG','SCRIPT'].includes(node.tagName)));assert.match(root.textContent,/<script>synthetic/);});
test('ordinary text endpoint cannot smuggle or replace native evidence',async t=>{const f=fixture(t);await seed(f);await assert.rejects(f.service.set('owner-a',{...req(f),eventId:'smuggle',expectedVersion:1,nativeEvidence:[]}));await assert.rejects(f.service.set('owner-a',{...req(f),eventId:'smuggle2',expectedVersion:1,changes:{nativeEvidence:[]}}));assert.equal(count(f),1);});

test('unread native evidence is not presented as a verified empty ledger',()=>{const doc={createElement:tag=>new Node(tag,doc)},root=doc.createElement('div');renderNativeTaskEvidence(root,undefined);assert.match(root.textContent,/尚未读取/);assert.doesNotMatch(root.textContent,/尚未记录 native/);const empty=doc.createElement('div');renderNativeTaskEvidence(empty,[]);assert.match(empty.textContent,/尚未记录 native/);});

test('requirement anchor must identify a text revision rather than an evidence-only append',async t=>{const f=fixture(t);await seed(f);await f.service.appendNativeEvidence('owner-a',evidence(f));await assert.rejects(f.service.appendNativeEvidence('owner-a',evidence(f,{eventId:'invalid-anchor',expectedVersion:2,requirementVersion:2})),code('requirement_revision_not_text'));assert.equal(count(f),2);});
