import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Worker} from 'node:worker_threads';
import {sqliteIntakeFixture} from './sqlite-intake-fixture.mjs';
import {createD1TaskRequirementsStore} from '../src/adapters/d1-task-requirements.mjs';
import {createTaskRequirementsService} from '../src/application/task-requirements-service.mjs';
import {createWorker} from '../worker.mjs';
import {createSitesPrivateEntry} from '../src/application/sites-entry.mjs';
const now='2026-10-09T18:00:00.000Z',source=JSON.parse(readFileSync(new URL('../fixtures/synthetic.json',import.meta.url),'utf8'));
const input=(taskId,extra={})=>({taskId,eventId:'requirements-event-1',expectedVersion:0,changes:{goal:'Keep existing requests visible'},sourceReferences:['synthetic-owner-message-1'],...extra});
function fixture(t){const db=sqliteIntakeFixture();t.after(()=>db.close());const snapshot=structuredClone(source),task=snapshot.tasks[0];task.goal='Original goal';task.acceptanceCriteria='Original acceptance';const store=createD1TaskRequirementsStore(db.binding),service=createTaskRequirementsService({store,ownerId:'owner-a',readSnapshot:()=>snapshot,clock:()=>now});return {...db,store,service,snapshot,task};}
const code=value=>error=>error.code===value;
const count=f=>f.db.prepare('SELECT COUNT(*) n FROM task_requirement_events').get().n;
test('initial requirements read uses existing fields and reports no execution grant',async t=>{const f=fixture(t),r=await f.service.get('owner-a',f.task.id);assert.equal(r.version,0);assert.equal(r.goal,'Original goal');assert.equal(r.acceptanceCriteria,'Original acceptance');assert.deepEqual(r.sourceReferences,{goal:[],acceptanceCriteria:[]});assert.equal(r.grantsExecution,false);});
test('owner and known-task checks reject without creating any records',async t=>{const f=fixture(t);await assert.rejects(f.service.get('',f.task.id),code('authentication_required'));await assert.rejects(f.service.get('owner-b',f.task.id),code('board_access_denied'));await assert.rejects(f.service.set('owner-b',input(f.task.id)),code('board_access_denied'));await assert.rejects(f.service.set('owner-a',input('missing-task')),code('task_not_found'));assert.equal(count(f),0);});
test('partial fields preserve unmodified content and retain separate source references',async t=>{const f=fixture(t),before=structuredClone(f.snapshot);const a=await f.service.set('owner-a',input(f.task.id));assert.equal(a.version,1);assert.equal(a.acceptanceCriteria,'Original acceptance');const b=await f.service.set('owner-a',input(f.task.id,{eventId:'requirements-event-2',expectedVersion:1,changes:{acceptanceCriteria:'Read the existing original task'},sourceReferences:['synthetic-owner-message-2']}));assert.equal(b.goal,a.goal);assert.deepEqual(b.sourceReferences,{goal:['synthetic-owner-message-1'],acceptanceCriteria:['synthetic-owner-message-2']});assert.deepEqual(f.snapshot,before);assert.equal(b.grantsExecution,false);});
test('overlay changes only requested text while original task, source, status, control and timestamps stay unchanged',async t=>{const f=fixture(t);f.task.state='paused';f.task.observedAt=now;f.task.nextAction='Original next action';f.task.manualStatus={version:2,state:'completed'};f.task.sourceBinding={threadId:null,readAllowed:false};const before=structuredClone(f.snapshot);await f.service.set('owner-a',input(f.task.id,{changes:{goal:'New bounded goal',acceptanceCriteria:'New bounded criteria'}}));const overlay=await f.service.overlay('owner-a',f.snapshot);const changed=overlay.tasks.find(x=>x.id===f.task.id);assert.deepEqual({...changed,goal:before.tasks[0].goal,acceptanceCriteria:before.tasks[0].acceptanceCriteria},before.tasks[0]);assert.deepEqual(f.snapshot,before);assert.deepEqual(overlay.agents,before.agents);assert.equal(overlay.importedAt,before.importedAt);for(const table of ['dispatch_controls','dispatch_jobs','dispatch_task_bindings','dispatch_resource_leases','board_observation_events','intake_requests'])assert.equal(f.db.prepare('SELECT COUNT(*) n FROM '+table).get().n,0);});
test('metadata records do not require or create a source execution binding, even for stopped tasks',async t=>{for(const state of ['paused','canceled','completed']){const f=fixture(t);f.task.state=state;await f.service.set('owner-a',input(f.task.id));assert.equal((await f.service.overlay('owner-a',f.snapshot)).tasks[0].state,state);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM dispatch_task_bindings').get().n,0);}});
test('identical event replay returns current version without duplicate history and changed replay is rejected',async t=>{const f=fixture(t),value=input(f.task.id);await f.service.set('owner-a',value);assert.equal((await f.service.set('owner-a',value)).duplicate,true);await f.service.set('owner-a',input(f.task.id,{eventId:'requirements-event-2',expectedVersion:1,changes:{goal:'Later verified goal'}}));const replay=await f.service.set('owner-a',value);assert.equal(replay.version,2);assert.equal(replay.goal,'Later verified goal');assert.equal(replay.duplicate,true);assert.equal(count(f),2);await assert.rejects(f.service.set('owner-a',{...value,changes:{goal:'Changed replay'}}),code('requirements_event_conflict'));});
test('stale CAS and forbidden fields cannot change requirements or execution fields',async t=>{const f=fixture(t);await f.service.set('owner-a',input(f.task.id));await assert.rejects(f.service.set('owner-a',input(f.task.id,{eventId:'stale-event'})),code('requirements_version_conflict'));for(const changes of [{state:'running'},{threadId:'replacement'},{goal:'valid',nextAction:'execute now'},{goal:'x'.repeat(401)},{goal:'/workspace/private/path'},{}])await assert.rejects(f.service.set('owner-a',input(f.task.id,{eventId:'bad',expectedVersion:1,changes})));await assert.rejects(f.service.set('owner-a',{...input(f.task.id),executionAllowed:true}));assert.equal(count(f),1);});
test('source references are bounded recorded provenance and cannot become policy fields',async t=>{const f=fixture(t);for(const sourceReferences of [[],[''],['a','a'],['x'.repeat(201)],[{executionAllowed:true}],['/workspace/private']])await assert.rejects(f.service.set('owner-a',input(f.task.id,{sourceReferences})));assert.equal(count(f),0);const r=await f.service.set('owner-a',input(f.task.id,{changes:{goal:'A description mentioning execution is still only text'}}));assert.equal(r.grantsExecution,false);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM dispatch_controls').get().n,0);});
test('eight competing text CAS writes commit exactly one version',async t=>{const f=fixture(t);const results=await Promise.allSettled(Array.from({length:8},(_,i)=>f.service.set('owner-a',input(f.task.id,{eventId:'race-'+i,changes:{goal:'Goal '+i}}))));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert(results.filter(x=>x.status==='rejected').every(x=>x.reason.code==='requirements_version_conflict'));assert.equal(count(f),1);});
test('concurrent identical metadata events replay one persisted record',async t=>{const f=fixture(t);const results=await Promise.all(Array.from({length:8},()=>f.service.set('owner-a',input(f.task.id))));assert.equal(count(f),1);assert.equal(results.filter(x=>!x.duplicate).length,1);assert(results.every(x=>x.version===1));});
test('missing requirements migration preserves ordinary board reads but new writes fail explicitly',async t=>{const f=fixture(t);f.db.exec('DROP TABLE task_requirement_events');assert.equal(await f.service.available(),false);assert.strictEqual(await f.service.overlay('owner-a',f.snapshot),f.snapshot);await assert.rejects(f.service.get('owner-a',f.task.id),code('requirements_storage_unavailable'));});
test('requirements history is append-only and both migration tracks create equivalent new schema',async t=>{const f=fixture(t);await f.service.set('owner-a',input(f.task.id));assert.throws(()=>f.db.exec("UPDATE task_requirement_events SET fields_json='{}'"),/requirements_append_only/);assert.throws(()=>f.db.exec('DELETE FROM task_requirement_events'),/requirements_append_only/);const db=new DatabaseSync(':memory:');t.after(()=>db.close());for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));assert.deepEqual(db.prepare('PRAGMA table_info(task_requirement_events)').all(),f.db.prepare('PRAGMA table_info(task_requirement_events)').all());assert.deepEqual(db.prepare('PRAGMA index_list(task_requirement_events)').all(),f.db.prepare('PRAGMA index_list(task_requirement_events)').all());});
function siteFixture(t,entry=createSitesPrivateEntry()){
 const f=fixture(t),env={DB:f.binding,DOT_BOARD_INGRESS:'sites-owner-private-v1',DOT_BOARD_OWNER_ID:'owner-a',DOT_BOARD_AUDIENCE:'https://example.com',DOT_BOARD_SNAPSHOT:JSON.stringify(f.snapshot),DOT_BOARD_PROJECT_REGISTRY:JSON.stringify([{id:'sample',name:f.task.project,aliases:[],executionState:'paused'}]),DOT_BOARD_INTAKE_MCP_ENABLED:'true'};
 const call=(path,{owner='owner-a',body,origin='https://example.com',method=body?'POST':'GET'}={})=>entry.fetch(new Request('https://example.com'+path,{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),...(origin?{origin}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);
 return {...f,env,call};
}
test('owner-private HTTP saves then rereads only requirement text and rejects missing identity, wrong owner, origin and target',async t=>{const f=siteFixture(t),path='/api/tasks/'+f.task.id+'/requirements',{taskId,...body}=input(f.task.id);assert.equal((await f.call(path,{owner:null})).status,401);assert.equal((await f.call(path,{owner:'other',body})).status,403);assert.equal((await f.call(path,{body,origin:'https://other.example.com'})).status,403);assert.equal((await f.call('/api/tasks/missing/requirements',{body})).status,404);assert.equal((await f.call(path,{body})).status,200);const got=await(await f.call(path)).json();assert.equal(got.version,1);assert.equal(got.grantsExecution,false);const b=await(await f.call('/api/board')).json();assert.equal(b.tasks.find(x=>x.id===f.task.id).goal,body.changes.goal);assert.equal(b.tasks.find(x=>x.id===f.task.id).state,f.task.state);assert.equal(count(f),1);});
test('MCP exposes bounded metadata tools with CAS and sources without dispatching any request',async t=>{const f=siteFixture(t),rpc=(name,args)=>f.call('/mcp',{body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}}});const list=await(await f.call('/mcp',{body:{jsonrpc:'2.0',id:1,method:'tools/list'}})).json();assert(list.result.tools.some(x=>x.name==='get_task_requirements'));assert(list.result.tools.some(x=>x.name==='record_task_requirements'));const saved=await(await rpc('record_task_requirements',input(f.task.id))).json();assert.equal(saved.result.structuredContent.version,1);const read=await(await rpc('get_task_requirements',{taskId:f.task.id})).json();assert.deepEqual(read.result.structuredContent.sourceReferences.goal,['synthetic-owner-message-1']);assert.equal(read.result.structuredContent.grantsExecution,false);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM intake_requests').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM dispatch_jobs').get().n,0);});
test('compiled Sites entry preserves the same incremental requirement save/read contract',async t=>{const compiled=(await import('../dist/sites/index.js')).default,f=siteFixture(t,compiled),{taskId,...body}=input(f.task.id),path='/api/tasks/'+f.task.id+'/requirements';assert.equal((await f.call(path,{body})).status,200);assert.equal((await(await f.call(path)).json()).version,1);assert.equal((await(await f.call('/api/board')).json()).tasks.find(x=>x.id===f.task.id).goal,body.changes.goal);});
async function raceRequirementWriters(t,identical){const dir=mkdtempSync(join(tmpdir(),'task-requirements-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const filename=join(dir,'db.sqlite'),f=sqliteIntakeFixture(filename);t.after(()=>f.close());const workers=Array.from({length:6},(_,i)=>new Worker(new URL('./task-requirements-worker.mjs',import.meta.url),{workerData:{filename,snapshot:source,now,input:input(source.tasks[0].id,{eventId:identical?'same-event':'event-'+i})}}));t.after(async()=>Promise.all(workers.map(worker=>worker.terminate())));await Promise.all(workers.map(worker=>new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);})));const waiting=workers.map(worker=>new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);}));workers.forEach(worker=>worker.postMessage('go'));return {db:f.db,results:await Promise.all(waiting)};}
test('six independent SQLite connections preserve one requirement CAS winner',async t=>{const {db,results}=await raceRequirementWriters(t,false);assert.equal(results.filter(r=>r.ok).length,1,JSON.stringify(results));assert(results.filter(r=>!r.ok).every(r=>r.code==='requirements_version_conflict'));assert.equal(db.prepare('SELECT COUNT(*) n FROM task_requirement_events').get().n,1);});
test('six independent identical-event writers all read one idempotent persisted version',async t=>{const {db,results}=await raceRequirementWriters(t,true);assert(results.every(r=>r.ok),JSON.stringify(results));assert.equal(results.filter(r=>!r.result.duplicate).length,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM task_requirement_events').get().n,1);});
test('metadata updates preserve existing uncertain writer, resource lease, task binding and cancellation rows byte-for-byte',async t=>{const f=fixture(t),taskId=f.task.id;f.db.prepare('INSERT INTO intake_requests(id,owner_id,project_id,client_submission_id,payload_digest,body,context_task_id,viewed_snapshot_revision,viewed_snapshot_imported_at,context_summary,context_stale,status,created_at,updated_at,version,linked_task_ids,latest_summary) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('existing-request','owner-a','sample','existing-submission','a'.repeat(64),'Synthetic existing request',taskId,'sha256:'+('a'.repeat(64)),now,'',0,'blocked',now,now,4,'[]','');f.db.prepare("INSERT INTO dispatch_jobs(id,owner_id,project_id,request_id,request_version,state,environment_type,root_job_id,thread_id,dispatch_key,holds_slot,context_task_id,created_at,updated_at) VALUES (?,?,?,?,?,'uncertain','existing_thread',?,?,?,1,?,?,?)").run('existing-job','owner-a','sample','existing-request',4,'existing-job','synthetic-original-thread','synthetic-dispatch-key',taskId,now,now);f.db.prepare('INSERT INTO dispatch_resource_leases(resource_key,owner_id,job_id,dispatch_key,acquired_at,expires_at) VALUES (?,?,?,?,?,?)').run('service:synthetic','owner-a','existing-job','synthetic-dispatch-key',now,now);f.db.prepare("INSERT INTO dispatch_controls(owner_id,scope,target_id,state,version,reason,updated_at) VALUES (?,'task',?,'canceled',3,?,?)").run('owner-a',taskId,'Existing owner decision',now);f.db.prepare('INSERT INTO dispatch_task_bindings(owner_id,task_id,project_id,thread_id,environment_type,environment_id,verified_at,evidence) VALUES (?,?,?,?,?,NULL,?,?)').run('owner-a',taskId,'sample','synthetic-original-thread','existing_thread',now,'Synthetic existing mapping');const tables=['intake_requests','dispatch_jobs','dispatch_resource_leases','dispatch_controls','dispatch_task_bindings'],before=Object.fromEntries(tables.map(table=>[table,f.db.prepare('SELECT * FROM '+table).all()]));await f.service.set('owner-a',input(taskId));for(const table of tables)assert.deepEqual(f.db.prepare('SELECT * FROM '+table).all(),before[table]);});

test('requirements capability reports actual service storage and generic Worker remains view-only',async t=>{const f=siteFixture(t);assert.equal((await(await f.call('/api/config')).json()).requirementsEnabled,true);f.db.exec('DROP TABLE task_requirement_events');assert.equal((await(await f.call('/api/config')).json()).requirementsEnabled,false);const response=await createWorker().fetch(new Request('https://example.com/api/config'),{});assert.equal((await response.json()).requirementsEnabled,false);});
test('public schema snapshot appends only requirements and preserves all previous tables',()=>{const previous=JSON.parse(readFileSync(new URL('../drizzle/meta/0007_snapshot.json',import.meta.url),'utf8')),current=JSON.parse(readFileSync(new URL('../drizzle/meta/0008_snapshot.json',import.meta.url),'utf8'));assert.equal(current.prevId,previous.id);assert.notEqual(current.id,previous.id);const tables={...current.tables};assert(tables.task_requirement_events);delete tables.task_requirement_events;assert.deepEqual(tables,previous.tables);for(const key of Object.keys(previous).filter(k=>!['id','prevId','tables'].includes(k)))assert.deepEqual(current[key],previous[key]);});
