import test from 'node:test';import assert from 'node:assert/strict';
import {createTaskRequirementsController,renderTaskRequirementsForm} from '../public/project-clarity.js';
const task={id:'sample-task',goal:'Original goal',acceptanceCriteria:'Original standard',state:'paused'},now='2026-10-10T01:00:00.000Z';
const value=(version=1,extra={})=>({taskId:task.id,version,goal:task.goal,acceptanceCriteria:task.acceptanceCriteria,sourceReferences:{goal:['synthetic-message'],acceptanceCriteria:['synthetic-message']},nativeEvidence:[],grantsExecution:false,...extra});
const saved=p=>value(2,{nativeEvidence:[{...p,sourceType:'native_task'}]});
const draft=c=>{for(const [k,v] of Object.entries({requirementVersion:'1',nativeTaskName:'maintain_original_board',summary:'Recorded display change only',observedAt:now,references:'commit | Source | https://example.com/commit/sample'}))c.editNative(task.id,k,v);};
test('normal native evidence form writes one original task CAS without changing text or state',async()=>{const calls=[],c=createTaskRequirementsController({uuid:()=> 'native-event',clock:()=>now,requestJson:async(url,options)=>{calls.push([url,options]);return options?saved(JSON.parse(options.body)):value();}});await c.open(task);draft(c);await c.appendNative(task);assert.equal(calls.length,2);assert.equal(calls[1][0],'/api/tasks/sample-task/requirements/native-evidence');const body=JSON.parse(calls[1][1].body);assert.equal(body.expectedVersion,1);assert.equal(body.requirementVersion,1);assert.equal(body.nativeTaskName,'maintain_original_board');assert.equal(body.observedAt,now);assert.deepEqual(body.resultReferences,[{kind:'commit',label:'Source',reference:'https://example.com/commit/sample'}]);assert(!Object.hasOwn(body,'requestId'));assert(!Object.hasOwn(body,'threadId'));assert.equal(c.get(task.id).nativeSubmission,null);assert.equal(task.state,'paused');assert.equal(c.get(task.id).goal,task.goal);});
test('lost native save receipt is reconciled by read with no duplicate write',async()=>{let posts=0,persisted=null;const c=createTaskRequirementsController({uuid:()=> 'native-event',requestJson:async(url,options)=>{if(options){posts++;persisted=saved(JSON.parse(options.body));throw Error('response lost');}return persisted||value();}});await c.open(task);draft(c);await c.appendNative(task);await c.appendNative(task);assert.equal(posts,1);c.edit(task.id,'goal','must not edit while unknown');assert.equal(c.get(task.id).goal,task.goal);await c.save(task);assert.equal(posts,1);await c.open(task,true);assert.equal(posts,1);assert.equal(c.get(task.id).nativeSubmission,null);assert.match(c.get(task.id).message,/回读确认成果/);});
test('retry requires a fresh read and uses byte-identical event after an uncommitted failure',async()=>{const posts=[];const c=createTaskRequirementsController({uuid:()=> 'same-event',requestJson:async(url,options)=>{if(!options)return value();posts.push(options.body);if(posts.length===1)throw Error('network');return saved(JSON.parse(options.body));}});await c.open(task);draft(c);await c.appendNative(task);await c.appendNative(task);assert.equal(posts.length,1);await c.open(task,true);await c.appendNative(task);assert.equal(posts.length,2);assert.equal(posts[0],posts[1]);});
test('parallel clicks and requirement edits cannot overlap the same CAS operation',async()=>{let resolve,posts=0;const c=createTaskRequirementsController({requestJson:async(url,options)=>{if(!options)return value();posts++;return new Promise(r=>resolve=()=>r(saved(JSON.parse(options.body))));}});await c.open(task);draft(c);const active=c.appendNative(task);await c.appendNative(task);await c.save(task);assert.equal(posts,1);resolve();await active;assert.equal(c.get(task.id).nativeSubmission,null);});
test('unsaved requirement text is retained and cannot be silently overwritten by evidence save',async()=>{let posts=0;const c=createTaskRequirementsController({requestJson:async(url,options)=>{if(options)posts++;return value();}});await c.open(task);draft(c);c.edit(task.id,'goal','Owner draft');await c.appendNative(task);assert.equal(posts,0);assert.equal(c.get(task.id).goal,'Owner draft');assert.match(c.get(task.id).error,/未保存/);});
test('conflict requires reread and malformed evidence is rejected locally',async()=>{let posts=0;const c=createTaskRequirementsController({requestJson:async(url,options)=>{if(!options)return value();posts++;throw Object.assign(Error('conflict'),{status:409});}});await c.open(task);draft(c);c.editNative(task.id,'references','unsupported | label | ref');await c.appendNative(task);assert.equal(posts,0);draft(c);await c.appendNative(task);await c.appendNative(task);assert.equal(posts,1);assert.equal(c.get(task.id).loaded,false);assert.match(c.get(task.id).error,/重新读取/);});
class Node{constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.dataset={};this.events={};this.attributes={};this.ownText='';}set textContent(v){this.ownText=String(v);this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,fn){this.events[k]=fn;}}
test('same task inspector exposes bounded normal metadata fields with no execution controls',async()=>{const doc={createElement:t=>new Node(t,doc)},root=doc.createElement('div'),c=createTaskRequirementsController({requestJson:async()=>value()});await c.open(task);renderTaskRequirementsForm(root,task,c);const walk=n=>[n,...n.children.flatMap(walk)],nodes=walk(root);for(const label of ['原文字需求版本','原 native 任务名称','已核实成果摘要','实际观察时间（UTC，留空使用当前时间）','成果引用（类型 | 名称 | 来源，每行一条）'])assert(nodes.some(n=>n.attributes['aria-label']===label));assert(nodes.some(n=>n.tagName==='BUTTON'&&n.textContent==='保存成果注记'));assert(!nodes.some(n=>n.tagName==='SELECT'));assert.match(root.textContent,/不会创建请求或改变执行状态/);});

test('an unsaved source-only draft is preserved without posting evidence',async()=>{let posts=0;const c=createTaskRequirementsController({requestJson:async(url,options)=>{if(options)posts++;return value();}});await c.open(task);draft(c);c.edit(task.id,'sources','unsaved-source');await c.appendNative(task);assert.equal(posts,0);assert.equal(c.get(task.id).sources,'unsaved-source');assert.match(c.get(task.id).error,/未保存/);});
