import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createTaskRequirementsController,renderTaskRequirementsForm} from '../public/project-clarity.js';
const task={id:'original-task',state:'paused',goal:'Original goal',acceptanceCriteria:'Original criteria'};
const response=(version=0,extra={})=>({taskId:task.id,version,goal:task.goal,acceptanceCriteria:task.acceptanceCriteria,sourceReferences:{goal:[],acceptanceCriteria:[]},grantsExecution:false,...extra});
function edit(controller){controller.edit(task.id,'goal','Updated stated goal');controller.edit(task.id,'sources','source-message-1\nsource-message-2');}
test('requirements editor reads original task metadata without writing state or requesting a binding',async()=>{const calls=[],controller=createTaskRequirementsController({requestJson:async(...args)=>{calls.push(args);return response();}});await controller.open(task);assert.deepEqual(calls,[['/api/tasks/original-task/requirements']]);assert.equal(controller.get(task.id).goal,task.goal);assert.equal(task.state,'paused');});
test('save includes only changed text, original task route, independent CAS and explicit references',async()=>{const calls=[],saved=[],controller=createTaskRequirementsController({uuid:()=> 'original-event',onSaved:(...args)=>saved.push(args),requestJson:async(url,options)=>{calls.push([url,options]);return options?response(1,{goal:'Updated stated goal',sourceReferences:{goal:['source-message-1','source-message-2'],acceptanceCriteria:[]}}):response();}});await controller.open(task);edit(controller);await controller.save(task);assert.deepEqual(JSON.parse(calls[1][1].body),{eventId:'original-event',expectedVersion:0,changes:{goal:'Updated stated goal'},sourceReferences:['source-message-1','source-message-2']});assert.equal(saved[0][0],task.id);assert.equal(task.state,'paused');assert.equal(task.goal,'Original goal');assert.equal(controller.get(task.id).submission,null);});
test('unchanged text produces no new request or metadata version',async()=>{let calls=0;const controller=createTaskRequirementsController({requestJson:async()=>{calls++;return response();}});await controller.open(task);await controller.save(task);assert.equal(calls,1);assert.match(controller.get(task.id).message,/内容未变化/);});
test('uncertain save retains byte-identical payload and prevents draft changes until reconciled',async()=>{const posts=[];let tries=0;const controller=createTaskRequirementsController({uuid:()=> 'same-event',requestJson:async(url,options)=>{if(!options)return response();posts.push(options.body);if(++tries===1)throw Error('network');return response(1,{goal:'Updated stated goal',sourceReferences:{goal:['source-message-1','source-message-2'],acceptanceCriteria:[]}});}});await controller.open(task);edit(controller);await controller.save(task);controller.edit(task.id,'goal','Do not replace pending payload');await controller.save(task);assert.equal(posts[0],posts[1]);assert.equal(controller.get(task.id).submission,null);assert.match(controller.get(task.id).message,/已保存/);});
test('read-after-uncertain confirms stored content and references without repeating the write',async()=>{let posts=0,committed=false;const saved=response(1,{goal:'Updated stated goal',sourceReferences:{goal:['source-message-1','source-message-2'],acceptanceCriteria:[]}}),controller=createTaskRequirementsController({uuid:()=> 'one-event',requestJson:async(url,options)=>{if(options){posts++;committed=true;throw Error('lost response');}return committed?saved:response();}});await controller.open(task);edit(controller);await controller.save(task);assert(controller.get(task.id).submission);await controller.open(task,true);assert.equal(posts,1);assert.equal(controller.get(task.id).submission,null);assert.match(controller.get(task.id).message,/已回读确认保存/);});
test('version conflict forces deliberate reread and never silently overwrites',async()=>{let posts=0;const controller=createTaskRequirementsController({requestJson:async(url,options)=>{if(!options)return response();posts++;throw Object.assign(Error('requirements_version_conflict'),{status:409});}});await controller.open(task);edit(controller);await controller.save(task);await controller.save(task);assert.equal(posts,1);assert.equal(controller.get(task.id).loaded,false);assert.match(controller.get(task.id).error,/重新读取/);});
test('rapid save clicks cannot start parallel writes and callback errors do not undo a verified receipt',async()=>{let done,posts=0;const controller=createTaskRequirementsController({onSaved:()=>{throw Error('render');},requestJson:async(url,options)=>{if(!options)return response();posts++;return new Promise(resolve=>done=resolve);}});await controller.open(task);edit(controller);const running=controller.save(task);await controller.save(task);assert.equal(posts,1);done(response(1,{goal:'Updated stated goal',sourceReferences:{goal:['source-message-1','source-message-2'],acceptanceCriteria:[]}}));await running;assert.equal(controller.get(task.id).submission,null);assert.match(controller.get(task.id).message,/已保存/);});
test('missing, duplicate or excessive references reject locally without making a write',async()=>{for(const sources of ['', 'same\nsame',Array.from({length:6},(_,i)=>'ref-'+i).join('\n')]){let posts=0;const controller=createTaskRequirementsController({requestJson:async(url,options)=>{if(options)posts++;return response();}});await controller.open(task);edit(controller);controller.edit(task.id,'sources',sources);await controller.save(task);assert.equal(posts,0);assert.match(controller.get(task.id).error,/来源引用/);}});
class Node{constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.dataset={};this.events={};this.ownText='';this.attributes={};}set textContent(v){this.ownText=String(v);this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,fn){this.events[k]=fn;}}
test('normal task editor exposes three labeled fields, saved provenance, and no execution control',async()=>{const doc={createElement:tag=>new Node(tag,doc)},root=doc.createElement('div'),controller=createTaskRequirementsController({requestJson:async()=>response()});await controller.open(task);renderTaskRequirementsForm(root,task,controller);const walk=n=>[n,...n.children.flatMap(walk)],fields=walk(root).filter(n=>n.tagName==='TEXTAREA');assert.deepEqual(fields.map(n=>n.attributes['aria-label']),['任务目标','完成标准','来源引用（每行一个）']);assert.match(root.textContent,/需求记录版本 0/);assert.match(root.textContent,/不改变任务状态或执行安排/);assert.match(root.textContent,/目标来源/);assert(!walk(root).some(n=>n.tagName==='SELECT'));const save=walk(root).find(n=>n.dataset.focusKey==='requirements:save:'+task.id);assert.equal(save.disabled,true);fields[0].value='Edited goal';fields[0].events.input();assert.equal(save.disabled,false);});
test('editor stays in original task inspector and refreshes only goal and acceptance after saving',async()=>{const app=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert(app.includes("requirementKey='requirements:'+task.id"));assert(app.includes("renderTaskRequirementsForm(requirementForm,task,requirements)"));assert(app.includes('{...task,goal:value.goal,acceptanceCriteria:value.acceptanceCriteria}'));assert(app.includes('void requirements.open(taskById(id))'));});

test('unsupported deployment does not read or write requirement metadata',async()=>{let calls=0;const controller=createTaskRequirementsController({supported:()=>false,requestJson:async()=>{calls++;return response();}});await controller.open(task);await controller.save(task);assert.equal(calls,0);assert.equal(controller.get(task.id).loaded,false);});
test('browser editor is conditional on the ordinary configured requirements capability',async()=>{const app=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(app,/supported:\(\)=>config\?\.requirementsEnabled===true/);assert.match(app,/if\(config\?\.requirementsEnabled===true\)\{\s*const requirementEditor/);});
