import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {aggregateProjects,renderProjectOverview,projectLayout} from '../public/project-overview.js';
class Element{constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.dataset={};this.style={};this.attrs={};this.events={};this.textContent='';this.className='';this.clientWidth=390;this.classList={add:c=>this.className+=' '+c,remove:c=>this.className=this.className.replace(c,''),contains:c=>this.className.split(' ').includes(c),toggle:c=>{if(this.className.split(' ').includes(c)){this.className=this.className.replace(c,'');return false;}this.className+=' '+c;return true;}};}append(...a){this.children.push(...a);}prepend(...a){this.children.unshift(...a);}replaceChildren(...a){this.children=a;}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,v){this.events[k]=v;}set innerHTML(_){throw Error('unsafe');}}
const doc={createElement:t=>new Element(t,doc),createElementNS:(_,t)=>new Element(t,doc)},walk=n=>[n,...n.children.flatMap(walk)];
const fixture={projects:['P'],tasks:[{id:'t',project:'P',title:'Test',state:'blocked',blocker:'Waiting on review',nextAction:'Check source'}],agents:[{id:'a',name:'角色',kind:'worker',taskIds:['t'],activity:{state:'unknown'}}]};
test('one workflow has no parallel tab DOM or stale references',()=>{const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8'),app=readFileSync(new URL('../public/app.js',import.meta.url),'utf8');for(const id of ['view-projects','view-tasks','view-agents']){assert(!html.includes(id));assert(!app.includes(`$('${id}')`));}const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));for(const m of app.matchAll(/\$\('([^']+)'\)/g))assert(ids.has(m[1]),m[1]);assert(html.includes('id="content-type"'));});
test('task blockers and next steps are source-backed mapped fields',()=>{const t=aggregateProjects(fixture).projects[0].tasks[0];assert.equal(t.blocker,'Waiting on review');assert.equal(t.nextAction,'Check source');});
test('type selection filters within the same project workflow',()=>{const model=aggregateProjects(fixture);for(const [type,taskN,agentN]of [['all',1,1],['tasks',1,0],['agents',0,1]]){const c=new Element('main',doc);renderProjectOverview(c,model,{contentType:type});const nodes=walk(c);assert.equal(nodes.filter(n=>n.className==='po-task').length,taskN);assert.equal(nodes.filter(n=>n.className==='po-agent').length,agentN);assert.equal(nodes.filter(n=>n.className==='po-zone').length,1);}});
test('compact layout has enough space for source-backed task detail rows',()=>{const p=aggregateProjects(fixture).projects;const l=projectLayout(p,{compact:true,availableWidth:390});assert(l.width<=390);assert(l.zones[0].height>=160+136+110);});
test('public brand uses project-owned geometry without copied official paths',()=>{const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');assert(html.includes('class="brand-mark project-ring"'));assert(html.includes('<span>dot</span>'));assert(!html.includes('40.0391'));const css=readFileSync(new URL('../public/styles.css',import.meta.url),'utf8');assert(css.includes('.project-ring{'));assert(css.includes('border-radius:50%'));});
test('unassigned role disclosure is compact, searchable and opens real detail id',()=>{const b=structuredClone(fixture);b.agents.push({id:'root',name:'总协调',kind:'coordinator'});const calls=[],c=new Element('main',doc);renderProjectOverview(c,aggregateProjects(b,{query:'总协调'}),{onAgent:id=>calls.push(id)});const nodes=walk(c),section=nodes.find(n=>n.className==='po-unassigned');assert(section);assert.equal(section.open,true);assert.equal(nodes.filter(n=>n.className==='po-zone').length,0);nodes.find(n=>n.dataset.focusKey==='po:unassigned:root').events.click();assert.deepEqual(calls,['root']);});
test('initial viewport precedes unassigned disclosure and detailed metric help',()=>{const b=structuredClone(fixture);b.agents.push({id:'root',name:'协调',kind:'coordinator'});const c=new Element('main',doc);renderProjectOverview(c,aggregateProjects(b));const children=c.children[0].children;assert(children.findIndex(n=>n.className==='po-viewport')<children.findIndex(n=>n.className==='po-unassigned'));assert(children.findIndex(n=>n.className==='po-viewport')<children.findIndex(n=>n.className==='po-secondary'));});
test('registered project summary renders parallel numbers and explicit scope changes inside the existing workflow',()=>{
 const now=Date.parse('2026-10-07T10:00:00Z'),b=structuredClone(fixture);b.tasks[0].taskNumber=3;
 const evidence={evidenceType:'tool_result',lastExecutionObservedAt:'2026-10-07T09:59:00Z',evidenceExpiresAt:'2026-10-07T10:04:00Z'};
 b.projectTotals=[{projectId:'p',projectName:'P',registered:12,completed:5,removed:2,activeRegistered:10,current:[{taskNumber:3,...evidence},{taskNumber:8,...evidence}],unverifiedRunning:[9],scopeChanges:[{type:'registered',taskNumber:12,recordedAt:'2026-10-07T09:59:00Z'},{type:'removed',taskNumber:2,recordedAt:'2026-10-07T09:59:00Z'}],coverage:{scope:'managed_queue',totalsComplete:true,scopeChangesOmitted:4}}];
 const c=new Element('main',doc);renderProjectOverview(c,aggregateProjects(b,{now}));const nodes=walk(c),content=nodes.map(n=>n.textContent).join(' ');
 assert.match(content,/已登记 12 · 已完成 5 · 已移除 2 · 在册 10/);assert.match(content,/当前执行 #3、#8（并行 2 项）/);assert.match(content,/执行待核实 #9/);
 assert.match(content,/新增 \+1 \/ 移除 −1 · 另有 4 条未展示/);assert.match(content,/新增登记 #12/);assert.match(content,/移除 #2/);assert.match(content,/不代表项目全部计划/);
 assert(nodes.some(n=>n.className==='po-task-title'&&n.textContent==='#3 · Test'));
 const viewport=nodes.find(n=>n.className==='po-viewport'),zone=viewport.children.find(n=>n.className==='po-zone');assert(zone);const accounting=zone.children.find(n=>n.className==='po-project-accounting');assert(accounting);assert(zone.children.indexOf(accounting)<zone.children.findIndex(n=>n.className==='po-task-list'));assert(walk(accounting).some(n=>n.textContent.includes('在册 10')));
});
