import {sqliteTable,text,integer,index,uniqueIndex,check,primaryKey,foreignKey} from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
export const intakeRequests=sqliteTable('intake_requests',{
  id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),projectId:text('project_id').notNull(),clientSubmissionId:text('client_submission_id').notNull(),payloadDigest:text('payload_digest').notNull(),body:text('body').notNull(),contextTaskId:text('context_task_id'),viewedSnapshotRevision:text('viewed_snapshot_revision').notNull(),viewedSnapshotImportedAt:text('viewed_snapshot_imported_at').notNull(),contextSummary:text('context_summary').notNull(),contextStale:integer('context_stale').notNull().default(0),status:text('status').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull(),linkedTaskIds:text('linked_task_ids').notNull().default('[]'),latestSummary:text('latest_summary').notNull().default('')
},table=>[uniqueIndex('intake_requests_submission_unique').on(table.ownerId,table.clientSubmissionId),index('intake_requests_owner_project').on(table.ownerId,table.projectId)]);
export const intakeEvents=sqliteTable('intake_events',{
  id:text('id').primaryKey(),requestId:text('request_id').notNull().references(()=>intakeRequests.id),version:integer('version').notNull(),eventDigest:text('event_digest').notNull(),status:text('status').notNull(),summary:text('summary').notNull(),createdAt:text('created_at').notNull(),linkedTaskIds:text('linked_task_ids').notNull(),evidenceLinks:text('evidence_links').notNull()
},table=>[uniqueIndex('intake_events_request_version_unique').on(table.requestId,table.version)]);
export const mcpEventSubscriptions=sqliteTable('mcp_event_subscriptions',{
 id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),argumentsJson:text('arguments_json').notNull(),projectId:text('project_id').notNull(),callbackUrl:text('callback_url').notNull(),signingSecret:text('signing_secret').notNull(),previousSecret:text('previous_secret'),previousSecretUntil:text('previous_secret_until'),expiresAt:text('expires_at').notNull(),verifiedUntil:text('verified_until').notNull(),active:integer('active').notNull().default(1),startSequence:integer('start_sequence').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()
},t=>[uniqueIndex('mcp_event_subscriptions_identity').on(t.ownerId,t.callbackUrl,t.name,t.argumentsJson),index('mcp_event_subscriptions_match').on(t.ownerId,t.name,t.projectId,t.active,t.expiresAt),check('mcp_event_subscriptions_active',sql`${t.active} IN (0,1)`)]);
export const mcpEvents=sqliteTable('mcp_events',{
 sequence:integer('sequence').primaryKey({autoIncrement:true}),eventId:text('event_id').notNull(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),argumentsJson:text('arguments_json').notNull(),projectId:text('project_id').notNull(),dataJson:text('data_json').notNull(),occurredAt:text('occurred_at').notNull(),eventDigest:text('event_digest').notNull()
},t=>[uniqueIndex('mcp_events_event_id').on(t.eventId)]);
export const mcpEventOutbox=sqliteTable('mcp_event_outbox',{
 subscriptionId:text('subscription_id').notNull().references(()=>mcpEventSubscriptions.id),eventId:text('event_id').notNull().references(()=>mcpEvents.eventId),state:text('state').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttemptAt:text('next_attempt_at').notNull(),leaseToken:text('lease_token'),leaseUntil:text('lease_until'),lastReason:text('last_reason'),deliveredAt:text('delivered_at')
},t=>[primaryKey({columns:[t.subscriptionId,t.eventId]}),index('mcp_event_outbox_due').on(t.state,t.nextAttemptAt,t.leaseUntil),check('mcp_event_outbox_state',sql`${t.state} IN ('pending','retry','delivering','delivered','failed','canceled')`)]);
export const dispatchJobs=sqliteTable('dispatch_jobs',{
 id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),projectId:text('project_id').notNull(),requestId:text('request_id').notNull().references(()=>intakeRequests.id),requestVersion:integer('request_version').notNull(),priority:integer('priority').notNull().default(0),state:text('state').notNull(),version:integer('version').notNull().default(1),environmentType:text('environment_type').notNull(),environmentId:text('environment_id'),rootJobId:text('root_job_id').notNull(),continuationOf:text('continuation_of'),threadId:text('thread_id'),turnId:text('turn_id'),dispatchKey:text('dispatch_key'),dispatchAttempt:integer('dispatch_attempt').notNull().default(0),holdsSlot:integer('holds_slot').notNull().default(0),summary:text('summary').notNull().default(''),reconciliationEvidence:text('reconciliation_evidence').notNull().default(''),evidenceLinks:text('evidence_links').notNull().default('[]'),executionObservedAt:text('execution_observed_at'),executionEvidence:text('execution_evidence'),taskNumber:integer('task_number'),resourcesJson:text('resources_json').notNull().default('[]'),contextTaskId:text('context_task_id'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()
},t=>[uniqueIndex('dispatch_request_identity').on(t.ownerId,t.requestId),uniqueIndex('dispatch_project_task_number').on(t.ownerId,t.projectId,t.taskNumber),index('dispatch_queue_order').on(t.ownerId,t.state,t.priority,t.createdAt,t.id),uniqueIndex('dispatch_one_thread_writer').on(t.ownerId,t.threadId).where(sql`${t.holdsSlot}=1 AND ${t.threadId} IS NOT NULL`)]);
export const dispatchOperations=sqliteTable('dispatch_operations',{
 ownerId:text('owner_id').notNull(),eventId:text('event_id').notNull(),jobId:text('job_id'),payloadDigest:text('payload_digest').notNull(),action:text('action').notNull(),createdAt:text('created_at').notNull()
},t=>[primaryKey({columns:[t.ownerId,t.eventId]})]);

export const dispatchControls=sqliteTable('dispatch_controls',{ownerId:text('owner_id').notNull(),scope:text('scope').notNull(),targetId:text('target_id').notNull(),state:text('state').notNull(),version:integer('version').notNull(),reason:text('reason').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.scope,t.targetId]}),check('dispatch_controls_scope',sql`${t.scope} IN ('project','task')`),check('dispatch_controls_state',sql`${t.state} IN ('active','paused','deferred','canceled')`)]);
export const dispatchResourceLeases=sqliteTable('dispatch_resource_leases',{resourceKey:text('resource_key').primaryKey().notNull(),ownerId:text('owner_id').notNull(),jobId:text('job_id').notNull(),dispatchKey:text('dispatch_key').notNull(),acquiredAt:text('acquired_at').notNull(),expiresAt:text('expires_at').notNull()});
export const dispatchTaskBindings=sqliteTable('dispatch_task_bindings',{ownerId:text('owner_id').notNull(),taskId:text('task_id').notNull(),projectId:text('project_id').notNull(),threadId:text('thread_id').notNull(),environmentType:text('environment_type').notNull(),environmentId:text('environment_id'),verifiedAt:text('verified_at').notNull(),evidence:text('evidence').notNull()},t=>[primaryKey({columns:[t.ownerId,t.taskId]})]);
export const nativeDispatchJournal=sqliteTable('native_dispatch_journal',{ownerId:text('owner_id').notNull(),operationId:text('operation_id').notNull(),bindingJson:text('binding_json').notNull(),state:text('state').notNull(),receiptJson:text('receipt_json'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.operationId]}),check('native_dispatch_journal_state',sql`${t.state} IN ('reserved','admitted','uncertain')`)]);
export const boardObservationEvents=sqliteTable('board_observation_events',{ownerId:text('owner_id').notNull(),taskId:text('task_id').notNull(),eventId:text('event_id').notNull(),payloadDigest:text('payload_digest').notNull(),version:integer('version').notNull(),sourceObservedAt:text('source_observed_at').notNull(),sourceObservedMs:integer('source_observed_ms').notNull(),observationJson:text('observation_json').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.eventId]}),uniqueIndex('board_observation_task_version').on(t.ownerId,t.taskId,t.version),index('board_observation_task_latest').on(t.ownerId,t.taskId,t.version),check('board_observation_digest',sql`length(${t.payloadDigest})=64`),check('board_observation_version',sql`${t.version}>=1`),check('board_observation_json',sql`json_valid(${t.observationJson})`)]);
export const boardObservationOutbox=sqliteTable('board_observation_outbox',{
 ownerId:text('owner_id').notNull(),eventId:text('event_id').notNull(),observationEventId:text('observation_event_id').notNull(),observationDigest:text('observation_digest').notNull(),projectId:text('project_id').notNull(),taskId:text('task_id').notNull(),status:text('status').notNull(),occurredAt:text('occurred_at').notNull(),createdAt:text('created_at').notNull(),state:text('state').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttemptAt:text('next_attempt_at').notNull(),leaseToken:text('lease_token'),leaseUntil:text('lease_until'),deliveredAt:text('delivered_at')
},t=>[
 primaryKey({columns:[t.ownerId,t.eventId]}),
 uniqueIndex('board_observation_outbox_observation').on(t.ownerId,t.observationEventId),
 index('board_observation_outbox_due').on(t.ownerId,t.state,t.nextAttemptAt,t.leaseUntil),
 foreignKey({name:'board_observation_outbox_observation_fk',columns:[t.ownerId,t.observationEventId],foreignColumns:[boardObservationEvents.ownerId,boardObservationEvents.eventId]}),
 check('board_observation_outbox_digest',sql`length(${t.observationDigest})=64`),
 check('board_observation_outbox_status',sql`${t.status} IN ('unknown','partial','blocked','paused','completed','canceled')`),
 check('board_observation_outbox_state',sql`${t.state} IN ('pending','delivering','delivered')`),
 check('board_observation_outbox_attempts',sql`${t.attempts}>=0`),
 check('board_observation_outbox_lease',sql`(${t.state}='delivering' AND ${t.leaseToken} IS NOT NULL AND ${t.leaseUntil} IS NOT NULL) OR (${t.state}<>'delivering' AND ${t.leaseToken} IS NULL AND ${t.leaseUntil} IS NULL)`)
]);
export const dispatchManualAuthorizations=sqliteTable('dispatch_manual_authorizations',{ownerId:text('owner_id').notNull(),requestId:text('request_id').notNull().references(()=>intakeRequests.id),projectId:text('project_id').notNull(),taskId:text('task_id').notNull(),expiresAt:text('expires_at').notNull(),reason:text('reason').notNull()},t=>[primaryKey({columns:[t.ownerId,t.requestId]}),foreignKey({columns:[t.ownerId,t.taskId],foreignColumns:[dispatchTaskBindings.ownerId,dispatchTaskBindings.taskId]}),index('dispatch_manual_authorizations_expiry').on(t.ownerId,t.expiresAt),check('dispatch_manual_authorization_reason',sql`length(${t.reason})>0 AND length(${t.reason})<=1200`)]);

export const taskManualStatusEvents=sqliteTable('task_manual_status_events',{
 ownerId:text('owner_id').notNull(),eventId:text('event_id').notNull(),taskId:text('task_id').notNull(),payloadDigest:text('payload_digest').notNull(),version:integer('version').notNull(),state:text('state').notNull(),reason:text('reason').notNull(),updatedAt:text('updated_at').notNull()
},t=>[
 primaryKey({columns:[t.ownerId,t.eventId]}),
 uniqueIndex('task_manual_status_version').on(t.ownerId,t.taskId,t.version),
 index('task_manual_status_latest').on(t.ownerId,t.taskId,t.version),
 check('task_manual_status_digest',sql`length(${t.payloadDigest})=64`),
 check('task_manual_status_version_positive',sql`${t.version}>=1`),
 check('task_manual_status_state',sql`${t.state} IN ('queued','running','blocked','paused','completed','canceled')`),
 check('task_manual_status_reason',sql`length(${t.reason})<=1200`)
]);
